<?php

declare(strict_types=1);

/**
 * DISC assessment catalog - high band.
 *
 * Framework:        disc (scoring version disc-education-1.0)
 * Education band:   high - High (grades 10-12)
 * Question count:   28 (Option A, Question Count Decision Gate approved
 *                   2026-08-19T05:38:16Z by the Product Owner)
 * Reverse items:    D/S 3 of 7 reversed (~42.9%); I/C 4 of 7 reversed (~57.1%)
 * Review state:     published - all content, educational, bias/safety, scoring,
 *                   Product Owner, DCR, and Codex review checkpoints recorded.
 *
 * Question IDs are opaque canonical UUIDs; stable identity lives in the
 * 'code' field (namespace disc_high_*).
 */

$metadata = [
    'framework' => 'disc',
    'education_band' => 'high',
    'scoring_version' => 'disc-education-1.0',
    'question_count' => 28,
    'stable_code_namespace' => 'disc_high_',
    'review_state' => 'published',
    'review_events' => [
        ['checkpoint' => 'content_review', 'reviewer' => 'Codex lead reviewer', 'approved_at_utc' => '2026-08-20T05:05:10Z'],
        ['checkpoint' => 'educational_review', 'reviewer' => 'Codex lead reviewer', 'approved_at_utc' => '2026-08-20T05:05:10Z'],
        ['checkpoint' => 'bias_review', 'reviewer' => 'Codex lead reviewer', 'approved_at_utc' => '2026-08-20T05:05:10Z'],
        ['checkpoint' => 'scoring_review', 'reviewer' => 'Codex lead reviewer', 'approved_at_utc' => '2026-08-20T05:05:10Z'],
        ['checkpoint' => 'product_owner_approval', 'reviewer' => 'NCnguyenn', 'approved_at_utc' => '2026-08-20T05:05:10Z'],
        ['checkpoint' => 'codex_schema_review', 'reviewer' => 'Codex lead reviewer', 'approved_at_utc' => '2026-08-20T05:05:10Z'],
    ],
    'schema_hash' => '0d0fce9d20d1dac9939ff4e66f8191c6faddb8947b74ffa81efc0bec1d935292',
    'advisory_disclaimer' => 'Kết quả DISC chỉ mang tính tham khảo cho giao tiếp và làm việc nhóm, không phải công cụ đánh giá nhân sự.',
];

$likertOptions = [
    ['value' => 1, 'label' => 'Hoàn toàn không đồng ý'],
    ['value' => 2, 'label' => 'Không đồng ý'],
    ['value' => 3, 'label' => 'Bình thường'],
    ['value' => 4, 'label' => 'Đồng ý'],
    ['value' => 5, 'label' => 'Hoàn toàn đồng ý'],
];

$questions = [
    [
        'id' => 'dfd6a752-8454-47e3-a9d7-350f63a7324a',
        'code' => 'disc_high_d_001',
        'position' => 1,
        'dimension_code' => 'D:+',
        'required' => true,
        'content' => 'Bạn chủ động nhận vai trò điều phối khi nhóm làm dự án học tập.',
        'options' => $likertOptions,
    ],
    [
        'id' => '09d4ba6e-38b8-4eb3-8f0a-a098eaa9875d',
        'code' => 'disc_high_i_002',
        'position' => 2,
        'dimension_code' => 'I:-',
        'required' => true,
        'content' => 'Bạn ít khi chủ động bắt chuyện trong sinh hoạt câu lạc bộ.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'c39a5103-b74a-469e-beed-ff5fff01ed3d',
        'code' => 'disc_high_s_003',
        'position' => 3,
        'dimension_code' => 'S:+',
        'required' => true,
        'content' => 'Bạn kiên nhẫn khi thành viên khác cần hỗ trợ.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'b0f538b2-18ad-418d-a8cf-e40fbdb29df0',
        'code' => 'disc_high_c_004',
        'position' => 4,
        'dimension_code' => 'C:-',
        'required' => true,
        'content' => 'Bạn thường bỏ qua bước rà soát lỗi chính tả của bài thuyết trình.',
        'options' => $likertOptions,
    ],
    [
        'id' => '2a70727f-d0a7-4677-a150-0f704b0ab3f7',
        'code' => 'disc_high_d_005',
        'position' => 5,
        'dimension_code' => 'D:-',
        'required' => true,
        'content' => 'Bạn thường do dự và chờ người khác ra quyết định khi nhóm đối mặt thử thách.',
        'options' => $likertOptions,
    ],
    [
        'id' => '0abba71f-58ce-4a65-9dce-d1fe4c78aa2e',
        'code' => 'disc_high_i_006',
        'position' => 6,
        'dimension_code' => 'I:+',
        'required' => true,
        'content' => 'Bạn thích truyền cảm hứng và tạo bầu không khí sôi nổi khi làm việc nhóm.',
        'options' => $likertOptions,
    ],
    [
        'id' => '6de86b07-e4d6-4b63-b0aa-36860876ee8d',
        'code' => 'disc_high_s_007',
        'position' => 7,
        'dimension_code' => 'S:-',
        'required' => true,
        'content' => 'Bạn cảm thấy bực bội khi phải điều chỉnh tiến độ cá nhân theo các bạn khác.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'ace08b18-b7c5-454e-9816-3f04023bb706',
        'code' => 'disc_high_c_008',
        'position' => 8,
        'dimension_code' => 'C:+',
        'required' => true,
        'content' => 'Bạn lập dàn ý chi tiết trước khi làm bài.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'ae87b9d1-d65f-4ec7-816a-c3ef0bc96947',
        'code' => 'disc_high_d_009',
        'position' => 9,
        'dimension_code' => 'D:+',
        'required' => true,
        'content' => 'Bạn quyết đoán đưa ra hướng giải quyết khi nhóm gặp bế tắc về ý tưởng.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'ecf6742a-0543-4487-81e2-7a0c223d344a',
        'code' => 'disc_high_i_010',
        'position' => 10,
        'dimension_code' => 'I:-',
        'required' => true,
        'content' => 'Bạn ngại trình bày quan điểm trước nhóm người chưa quen.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'ac12f133-4ad4-4750-b200-b3fb35e5eb7a',
        'code' => 'disc_high_s_011',
        'position' => 11,
        'dimension_code' => 'S:+',
        'required' => true,
        'content' => 'Bạn ưu tiên giữ bầu không khí hòa thuận trong nhóm.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'd6135879-24f1-4434-8527-307ab37c6616',
        'code' => 'disc_high_c_012',
        'position' => 12,
        'dimension_code' => 'C:-',
        'required' => true,
        'content' => 'Bạn ít khi kiểm tra lại các số liệu và dẫn chứng trước khi nộp báo cáo.',
        'options' => $likertOptions,
    ],
    [
        'id' => '06e41be9-a74c-4f58-80f2-9142acedb38d',
        'code' => 'disc_high_d_013',
        'position' => 13,
        'dimension_code' => 'D:-',
        'required' => true,
        'content' => 'Bạn thường tránh né việc nhận trách nhiệm chính trong các hoạt động lớn.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'e9650d7b-4a9a-49cd-943c-b776bf587688',
        'code' => 'disc_high_i_014',
        'position' => 14,
        'dimension_code' => 'I:+',
        'required' => true,
        'content' => 'Bạn dễ dàng kết nối và tạo thiện cảm với các bạn mới trong trường.',
        'options' => $likertOptions,
    ],
    [
        'id' => '4e9f6857-1320-48af-a916-8195a19388e4',
        'code' => 'disc_high_s_015',
        'position' => 15,
        'dimension_code' => 'S:-',
        'required' => true,
        'content' => 'Bạn thiếu kiên nhẫn khi phải giải thích lại một vấn đề nhiều lần cho bạn bè.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'ac877df2-4181-4625-a3fe-e7f7d1deb5c3',
        'code' => 'disc_high_c_016',
        'position' => 16,
        'dimension_code' => 'C:+',
        'required' => true,
        'content' => 'Bạn cẩn thận đối chiếu các nguồn tài liệu để đảm bảo bài viết chính xác.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'de2885f3-81fb-4258-a9f7-17acbb35d5e1',
        'code' => 'disc_high_d_017',
        'position' => 17,
        'dimension_code' => 'D:+',
        'required' => true,
        'content' => 'Bạn thúc đẩy nhóm hướng tới mục tiêu đã thống nhất.',
        'options' => $likertOptions,
    ],
    [
        'id' => '4d2ca4d2-e00e-43ce-80de-8e23b9fb4c6c',
        'code' => 'disc_high_i_018',
        'position' => 18,
        'dimension_code' => 'I:-',
        'required' => true,
        'content' => 'Bạn cảm thấy mệt mỏi khi tương tác liên tục trong các sự kiện ngoại khóa.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'a1633a81-d234-4f5c-bf03-798370ef6560',
        'code' => 'disc_high_s_019',
        'position' => 19,
        'dimension_code' => 'S:+',
        'required' => true,
        'content' => 'Bạn lắng nghe khi bạn bè muốn chia sẻ.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'e67e7a4b-eb8e-4290-bf29-2556163849f0',
        'code' => 'disc_high_c_020',
        'position' => 20,
        'dimension_code' => 'C:-',
        'required' => true,
        'content' => 'Bạn có xu hướng làm việc theo ngẫu hứng thay vì bám sát kế hoạch đã định.',
        'options' => $likertOptions,
    ],
    [
        'id' => '4e935f8a-56c9-43ec-a098-4a5e3b3f7b5c',
        'code' => 'disc_high_d_021',
        'position' => 21,
        'dimension_code' => 'D:-',
        'required' => true,
        'content' => 'Bạn ngại đưa ra phản biện khi nhóm thống nhất một quyết định chưa tối ưu.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'e74b1469-dbcb-4fdf-8e83-2bd15da11c05',
        'code' => 'disc_high_i_022',
        'position' => 22,
        'dimension_code' => 'I:+',
        'required' => true,
        'content' => 'Bạn thích lôi cuốn mọi người cùng trao đổi về ý tưởng mới.',
        'options' => $likertOptions,
    ],
    [
        'id' => '91fe1189-e066-412b-b158-4e130daa7057',
        'code' => 'disc_high_s_023',
        'position' => 23,
        'dimension_code' => 'S:-',
        'required' => true,
        'content' => 'Bạn khó thích nghi khi lịch trình làm việc nhóm bị thay đổi đột ngột.',
        'options' => $likertOptions,
    ],
    [
        'id' => '000f16a0-be60-4ae1-a8f7-8d7083378340',
        'code' => 'disc_high_c_024',
        'position' => 24,
        'dimension_code' => 'C:+',
        'required' => true,
        'content' => 'Bạn sắp xếp thời gian học theo kế hoạch rõ ràng.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'c5a56935-fdf1-40a3-8451-fb127a454faa',
        'code' => 'disc_high_d_025',
        'position' => 25,
        'dimension_code' => 'D:+',
        'required' => true,
        'content' => 'Bạn chủ động nhận phần việc khó khi nhóm cần người phụ trách.',
        'options' => $likertOptions,
    ],
    [
        'id' => '5e4a137f-2fa7-4ca4-b7a3-0fb53c7cac0b',
        'code' => 'disc_high_i_026',
        'position' => 26,
        'dimension_code' => 'I:-',
        'required' => true,
        'content' => 'Bạn ít khi kể chuyện cá nhân với bạn bè trong nhóm.',
        'options' => $likertOptions,
    ],
    [
        'id' => '2abff094-02ce-43f3-836b-c9e3f4c56f8e',
        'code' => 'disc_high_s_027',
        'position' => 27,
        'dimension_code' => 'S:+',
        'required' => true,
        'content' => 'Bạn kiên trì theo đuổi nhiệm vụ dù tiến độ kéo dài.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'd0ec66c3-563a-46b4-a6b6-4e6cd7b90f77',
        'code' => 'disc_high_c_028',
        'position' => 28,
        'dimension_code' => 'C:-',
        'required' => true,
        'content' => 'Bạn thường bỏ qua các tiêu chí phụ trong bảng đánh giá bài tập.',
        'options' => $likertOptions,
    ],
];

return ['metadata' => $metadata, 'questions' => $questions];
