<?php

declare(strict_types=1);

/**
 * DISC assessment catalog - middle band.
 *
 * Framework:        disc (scoring version disc-education-1.0)
 * Education band:   middle - Middle (grades 6-9)
 * Question count:   28 (Option A, Question Count Decision Gate approved
 *                   2026-08-19T05:38:16Z by the Product Owner)
 * Reverse items:    D/S 3 of 7 reversed (~42.9%); I/C 4 of 7 reversed (~57.1%)
 * Review state:     published - all content, educational, bias/safety, scoring,
 *                   Product Owner, DCR, and Codex review checkpoints recorded.
 *
 * Question IDs are opaque canonical UUIDs; stable identity lives in the
 * 'code' field (namespace disc_middle_*).
 */

$metadata = [
    'framework' => 'disc',
    'education_band' => 'middle',
    'scoring_version' => 'disc-education-1.0',
    'question_count' => 28,
    'stable_code_namespace' => 'disc_middle_',
    'review_state' => 'published',
    'review_events' => [
        ['checkpoint' => 'content_review', 'reviewer' => 'Codex lead reviewer', 'approved_at_utc' => '2026-08-20T05:05:10Z'],
        ['checkpoint' => 'educational_review', 'reviewer' => 'Codex lead reviewer', 'approved_at_utc' => '2026-08-20T05:05:10Z'],
        ['checkpoint' => 'bias_review', 'reviewer' => 'Codex lead reviewer', 'approved_at_utc' => '2026-08-20T05:05:10Z'],
        ['checkpoint' => 'scoring_review', 'reviewer' => 'Codex lead reviewer', 'approved_at_utc' => '2026-08-20T05:05:10Z'],
        ['checkpoint' => 'product_owner_approval', 'reviewer' => 'NCnguyenn', 'approved_at_utc' => '2026-08-20T05:05:10Z'],
        ['checkpoint' => 'codex_schema_review', 'reviewer' => 'Codex lead reviewer', 'approved_at_utc' => '2026-08-20T05:05:10Z'],
    ],
    'schema_hash' => 'd3e366bc18e73ffcad54b5f307798626e3f95019b2179a633055fa814d9242c5',
    'advisory_disclaimer' => 'Kết quả DISC chỉ mang tính tham khảo cho giao tiếp và làm việc nhóm, không phải công cụ đánh giá nhân sự.',
];

$likertOptions = [
    ['value' => 1, 'label' => 'Hoàn toàn không đồng ý'],
    ['value' => 2, 'label' => 'Không đồng ý'],
    ['value' => 3, 'label' => 'Bình thường'],
    ['value' => 4, 'label' => 'Đồng ý'],
    ['value' => 5, 'label' => 'Hoàn toàn đồng ý'],
];

$questions = [
    [
        'id' => '5a6faca2-f10c-4f5e-98c4-a427f305ce2f',
        'code' => 'disc_middle_d_001',
        'position' => 1,
        'dimension_code' => 'D:+',
        'required' => true,
        'content' => 'Bạn thích xung phong làm nhóm trưởng khi làm bài tập.',
        'options' => $likertOptions,
    ],
    [
        'id' => '92819fc7-0f18-4261-995f-22d3361bae22',
        'code' => 'disc_middle_i_002',
        'position' => 2,
        'dimension_code' => 'I:-',
        'required' => true,
        'content' => 'Bạn ngại bắt chuyện với các bạn mới quen trong lớp.',
        'options' => $likertOptions,
    ],
    [
        'id' => '6bbaa0a7-e514-49c0-bbe9-df3b5bb87427',
        'code' => 'disc_middle_s_003',
        'position' => 3,
        'dimension_code' => 'S:+',
        'required' => true,
        'content' => 'Bạn kiên nhẫn lắng nghe khi bạn bè chia sẻ câu chuyện.',
        'options' => $likertOptions,
    ],
    [
        'id' => '4ed080da-4390-4f25-974e-f067ad59b12e',
        'code' => 'disc_middle_c_004',
        'position' => 4,
        'dimension_code' => 'C:-',
        'required' => true,
        'content' => 'Bạn ít khi kiểm tra lại bài trước khi nộp cho thầy cô.',
        'options' => $likertOptions,
    ],
    [
        'id' => '5b65700d-be72-488f-93cd-4ac3d25fa08e',
        'code' => 'disc_middle_d_005',
        'position' => 5,
        'dimension_code' => 'D:-',
        'required' => true,
        'content' => 'Bạn thường chờ bạn khác đưa ra quyết định cho cả nhóm.',
        'options' => $likertOptions,
    ],
    [
        'id' => '1f2239ef-bfa8-47ad-aa1d-3805101a94c2',
        'code' => 'disc_middle_i_006',
        'position' => 6,
        'dimension_code' => 'I:+',
        'required' => true,
        'content' => 'Bạn thích khuấy động không khí vui vẻ cho cả nhóm.',
        'options' => $likertOptions,
    ],
    [
        'id' => '2f68dded-b52e-4f47-b161-85a5d096fa28',
        'code' => 'disc_middle_s_007',
        'position' => 7,
        'dimension_code' => 'S:-',
        'required' => true,
        'content' => 'Bạn thấy khó chịu khi phải chờ bạn khác làm bài xong.',
        'options' => $likertOptions,
    ],
    [
        'id' => '00f6154a-c330-420a-adae-06c3c1057e22',
        'code' => 'disc_middle_c_008',
        'position' => 8,
        'dimension_code' => 'C:+',
        'required' => true,
        'content' => 'Bạn làm bài theo các bước đã được hướng dẫn.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'e751f35b-e8d8-4172-b33b-10694e0e25c5',
        'code' => 'disc_middle_d_009',
        'position' => 9,
        'dimension_code' => 'D:+',
        'required' => true,
        'content' => 'Bạn nhanh chóng đưa ra cách làm khi nhóm gặp bài khó.',
        'options' => $likertOptions,
    ],
    [
        'id' => '3a904e0f-d977-442d-8f96-59d1af1e0654',
        'code' => 'disc_middle_i_010',
        'position' => 10,
        'dimension_code' => 'I:-',
        'required' => true,
        'content' => 'Bạn ít khi phát biểu ý kiến trước cả lớp.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'd7e30541-222e-43ed-98b8-d865f797e479',
        'code' => 'disc_middle_s_011',
        'position' => 11,
        'dimension_code' => 'S:+',
        'required' => true,
        'content' => 'Bạn sẵn lòng giúp đỡ bạn cùng bàn giải bài tập khó.',
        'options' => $likertOptions,
    ],
    [
        'id' => '2e040632-2696-4d16-bebf-db5f5ed328ee',
        'code' => 'disc_middle_c_012',
        'position' => 12,
        'dimension_code' => 'C:-',
        'required' => true,
        'content' => 'Bạn hay quên xếp lại đồ dùng học tập gọn gàng.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'c94f64d5-0f5e-402e-a421-9d43102647ef',
        'code' => 'disc_middle_d_013',
        'position' => 13,
        'dimension_code' => 'D:-',
        'required' => true,
        'content' => 'Bạn ngại nhận nhiệm vụ mới khi nhóm phân công việc.',
        'options' => $likertOptions,
    ],
    [
        'id' => '7870a3fc-167c-44d3-a3b5-fa4f6ca769a8',
        'code' => 'disc_middle_i_014',
        'position' => 14,
        'dimension_code' => 'I:+',
        'required' => true,
        'content' => 'Bạn dễ dàng làm quen và kết bạn với người mới.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'a086d4cd-5dde-4dab-9983-a3c9db874007',
        'code' => 'disc_middle_s_015',
        'position' => 15,
        'dimension_code' => 'S:-',
        'required' => true,
        'content' => 'Bạn dễ nổi nóng khi bạn bè làm việc chậm chạp.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'b4fac70d-4344-4759-bd6b-0b2c2adb77a0',
        'code' => 'disc_middle_c_016',
        'position' => 16,
        'dimension_code' => 'C:+',
        'required' => true,
        'content' => 'Bạn thích kiểm tra kỹ từng phép tính trong bài toán.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'efc530cb-deec-4d04-9076-2365d8e0983c',
        'code' => 'disc_middle_d_017',
        'position' => 17,
        'dimension_code' => 'D:+',
        'required' => true,
        'content' => 'Bạn chủ động quyết định hướng làm khi nhóm cần bắt đầu.',
        'options' => $likertOptions,
    ],
    [
        'id' => '341af4d5-0beb-4087-8f29-b1d632a79507',
        'code' => 'disc_middle_i_018',
        'position' => 18,
        'dimension_code' => 'I:-',
        'required' => true,
        'content' => 'Bạn không hào hứng tham gia các hoạt động tập thể.',
        'options' => $likertOptions,
    ],
    [
        'id' => '4ef66660-d3e3-447a-9851-21a0cf9c3b50',
        'code' => 'disc_middle_s_019',
        'position' => 19,
        'dimension_code' => 'S:+',
        'required' => true,
        'content' => 'Bạn giữ bình tĩnh khi trao đổi về bất đồng với bạn bè.',
        'options' => $likertOptions,
    ],
    [
        'id' => '53b8b5b1-2da8-40a1-8e9a-b79b3123e561',
        'code' => 'disc_middle_c_020',
        'position' => 20,
        'dimension_code' => 'C:-',
        'required' => true,
        'content' => 'Bạn thường làm bài theo cảm tính mà không theo dàn ý.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'f19ea1fd-d4cb-41fb-b39d-cccb12243211',
        'code' => 'disc_middle_d_021',
        'position' => 21,
        'dimension_code' => 'D:-',
        'required' => true,
        'content' => 'Bạn ngập ngừng khi phải chọn một phương án cho nhóm.',
        'options' => $likertOptions,
    ],
    [
        'id' => '8b16a1a3-d819-483a-bb33-877687bf832d',
        'code' => 'disc_middle_i_022',
        'position' => 22,
        'dimension_code' => 'I:+',
        'required' => true,
        'content' => 'Bạn thích chia sẻ những ý tưởng thú vị với cả lớp.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'aad2ec23-49f5-4f9c-8672-32c7caf13f6e',
        'code' => 'disc_middle_s_023',
        'position' => 23,
        'dimension_code' => 'S:-',
        'required' => true,
        'content' => 'Bạn ngại nhường nhịn khi có sự tranh luận trong nhóm.',
        'options' => $likertOptions,
    ],
    [
        'id' => '051fedcc-f951-4e35-a164-66ad9173156a',
        'code' => 'disc_middle_c_024',
        'position' => 24,
        'dimension_code' => 'C:+',
        'required' => true,
        'content' => 'Bạn chuẩn bị sách vở theo thời khóa biểu trước khi đến lớp.',
        'options' => $likertOptions,
    ],
    [
        'id' => '2624d9e2-b8d7-4aa0-9f42-240e443681b6',
        'code' => 'disc_middle_d_025',
        'position' => 25,
        'dimension_code' => 'D:+',
        'required' => true,
        'content' => 'Khi nhóm cần chốt phương án, bạn thường đứng ra quyết định.',
        'options' => $likertOptions,
    ],
    [
        'id' => '9dac0e43-f3b1-4b7d-909a-3317a7c1b0b2',
        'code' => 'disc_middle_i_026',
        'position' => 26,
        'dimension_code' => 'I:-',
        'required' => true,
        'content' => 'Bạn thích ngồi yên một góc hơn là hòa vào trò chơi chung.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'a2386f20-adeb-431b-bb0b-0457bb79b624',
        'code' => 'disc_middle_s_027',
        'position' => 27,
        'dimension_code' => 'S:+',
        'required' => true,
        'content' => 'Bạn giữ nhịp làm việc đều khi nhiệm vụ kéo dài.',
        'options' => $likertOptions,
    ],
    [
        'id' => '6555ba78-2815-49ea-b10d-ebe2fa8dad57',
        'code' => 'disc_middle_c_028',
        'position' => 28,
        'dimension_code' => 'C:-',
        'required' => true,
        'content' => 'Bạn thường bỏ qua các chi tiết nhỏ khi làm bài tập.',
        'options' => $likertOptions,
    ],
];

return ['metadata' => $metadata, 'questions' => $questions];
