<?php

declare(strict_types=1);

/**
 * DISC assessment catalog - college band.
 *
 * Framework:        disc (scoring version disc-education-1.0)
 * Education band:   college - College (vocational/university students)
 * Question count:   28 (Option A, Question Count Decision Gate approved
 *                   2026-08-19T05:38:16Z by the Product Owner)
 * Reverse items:    D/S 3 of 7 reversed (~42.9%); I/C 4 of 7 reversed (~57.1%)
 * Review state:     published - all content, educational, bias/safety, scoring,
 *                   Product Owner, DCR, and Codex review checkpoints recorded.
 *
 * Question IDs are opaque canonical UUIDs; stable identity lives in the
 * 'code' field (namespace disc_college_*).
 */

$metadata = [
    'framework' => 'disc',
    'education_band' => 'college',
    'scoring_version' => 'disc-education-1.0',
    'question_count' => 28,
    'stable_code_namespace' => 'disc_college_',
    'review_state' => 'published',
    'review_events' => [
        ['checkpoint' => 'content_review', 'reviewer' => 'Codex lead reviewer', 'approved_at_utc' => '2026-08-20T05:05:10Z'],
        ['checkpoint' => 'educational_review', 'reviewer' => 'Codex lead reviewer', 'approved_at_utc' => '2026-08-20T05:05:10Z'],
        ['checkpoint' => 'bias_review', 'reviewer' => 'Codex lead reviewer', 'approved_at_utc' => '2026-08-20T05:05:10Z'],
        ['checkpoint' => 'scoring_review', 'reviewer' => 'Codex lead reviewer', 'approved_at_utc' => '2026-08-20T05:05:10Z'],
        ['checkpoint' => 'product_owner_approval', 'reviewer' => 'NCnguyenn', 'approved_at_utc' => '2026-08-20T05:05:10Z'],
        ['checkpoint' => 'codex_schema_review', 'reviewer' => 'Codex lead reviewer', 'approved_at_utc' => '2026-08-20T05:05:10Z'],
    ],
    'schema_hash' => 'b39d01aa0b69a6db33a4f9799417215057d63b0dee8549e3400496632955eb67',
    'advisory_disclaimer' => 'Kết quả DISC chỉ mang tính tham khảo cho giao tiếp và làm việc nhóm, không phải công cụ đánh giá nhân sự.',
];

$likertOptions = [
    ['value' => 1, 'label' => 'Hoàn toàn không đồng ý'],
    ['value' => 2, 'label' => 'Không đồng ý'],
    ['value' => 3, 'label' => 'Bình thường'],
    ['value' => 4, 'label' => 'Đồng ý'],
    ['value' => 5, 'label' => 'Hoàn toàn đồng ý'],
];

$questions = [
    [
        'id' => '2615d8a2-4f1e-44cb-ba17-9d7669c2df46',
        'code' => 'disc_college_d_001',
        'position' => 1,
        'dimension_code' => 'D:+',
        'required' => true,
        'content' => 'Bạn chủ động dẫn dắt và phân chia đầu việc khi nhóm thực hiện đồ án học phần.',
        'options' => $likertOptions,
    ],
    [
        'id' => '166124a5-15fd-4b74-925b-4c365bda661e',
        'code' => 'disc_college_i_002',
        'position' => 2,
        'dimension_code' => 'I:-',
        'required' => true,
        'content' => 'Bạn ít khi chủ động bắt chuyện với người mới trong buổi học.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'be634dc2-041c-4d1b-bd52-06aa48445f07',
        'code' => 'disc_college_s_003',
        'position' => 3,
        'dimension_code' => 'S:+',
        'required' => true,
        'content' => 'Bạn kiên trì hỗ trợ đồng đội khi tiến độ gặp trở ngại.',
        'options' => $likertOptions,
    ],
    [
        'id' => '12825048-3c30-42fb-8da0-1723c3feae4c',
        'code' => 'disc_college_c_004',
        'position' => 4,
        'dimension_code' => 'C:-',
        'required' => true,
        'content' => 'Bạn thường bỏ qua khâu kiểm chứng định dạng trích dẫn tài liệu tham khảo.',
        'options' => $likertOptions,
    ],
    [
        'id' => '281b00d1-7ea0-486a-a228-f9a2d347b7a3',
        'code' => 'disc_college_d_005',
        'position' => 5,
        'dimension_code' => 'D:-',
        'required' => true,
        'content' => 'Bạn thường e ngại việc đưa ra quyết định then chốt khi nhóm đối mặt với tranh cãi.',
        'options' => $likertOptions,
    ],
    [
        'id' => '7a05cc40-f6a7-4cb9-9766-f46c7f504be2',
        'code' => 'disc_college_i_006',
        'position' => 6,
        'dimension_code' => 'I:+',
        'required' => true,
        'content' => 'Bạn thích kết nối các thành viên và truyền năng lượng tích cực khi thảo luận.',
        'options' => $likertOptions,
    ],
    [
        'id' => '33c106d6-579b-43c8-8387-b99f495dc5bd',
        'code' => 'disc_college_s_007',
        'position' => 7,
        'dimension_code' => 'S:-',
        'required' => true,
        'content' => 'Bạn cảm thấy thiếu kiên nhẫn khi phải giải thích quy trình nhiều lần cho người mới.',
        'options' => $likertOptions,
    ],
    [
        'id' => '667c1547-4abf-4c32-87d7-1ce8c020e6c2',
        'code' => 'disc_college_c_008',
        'position' => 8,
        'dimension_code' => 'C:+',
        'required' => true,
        'content' => 'Bạn kiểm tra kỹ phương pháp nghiên cứu trước khi bắt đầu.',
        'options' => $likertOptions,
    ],
    [
        'id' => '416a519c-7e12-418f-86a5-e1307a99c019',
        'code' => 'disc_college_d_009',
        'position' => 9,
        'dimension_code' => 'D:+',
        'required' => true,
        'content' => 'Bạn quyết đoán điều chỉnh kế hoạch để đảm bảo đồ án đạt kết quả cao nhất.',
        'options' => $likertOptions,
    ],
    [
        'id' => '61e65daf-9cf5-4ef9-bb5c-68d4cd9faa2c',
        'code' => 'disc_college_i_010',
        'position' => 10,
        'dimension_code' => 'I:-',
        'required' => true,
        'content' => 'Bạn ngại trình bày ý tưởng trước nhóm người chưa quen.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'b9d4bcac-745f-4f08-bfd1-38dce17148d5',
        'code' => 'disc_college_s_011',
        'position' => 11,
        'dimension_code' => 'S:+',
        'required' => true,
        'content' => 'Bạn lắng nghe để giữ sự hòa thuận trong nhóm.',
        'options' => $likertOptions,
    ],
    [
        'id' => '4a6adc91-d44a-436f-bb16-c1a0d9b3e975',
        'code' => 'disc_college_c_012',
        'position' => 12,
        'dimension_code' => 'C:-',
        'required' => true,
        'content' => 'Bạn ít khi đối chiếu chéo số liệu thực nghiệm trước khi đưa vào báo cáo tổng kết.',
        'options' => $likertOptions,
    ],
    [
        'id' => '4de5982d-980e-423d-b986-7b5b9e6b8fac',
        'code' => 'disc_college_d_013',
        'position' => 13,
        'dimension_code' => 'D:-',
        'required' => true,
        'content' => 'Bạn thường tránh nhận vai trò nhóm trưởng trong các dự án.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'd887e2d1-36ab-4fc7-9679-093ea0f52960',
        'code' => 'disc_college_i_014',
        'position' => 14,
        'dimension_code' => 'I:+',
        'required' => true,
        'content' => 'Bạn chủ động làm quen với người học khác trong lớp.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'ff934aed-c5cd-482b-8c87-7a50f7eb84c1',
        'code' => 'disc_college_s_015',
        'position' => 15,
        'dimension_code' => 'S:-',
        'required' => true,
        'content' => 'Bạn dễ cảm thấy áp lực khi nhịp độ làm việc của nhóm liên tục biến động.',
        'options' => $likertOptions,
    ],
    [
        'id' => '9c1f8450-0345-4c8d-8921-feace33006ba',
        'code' => 'disc_college_c_016',
        'position' => 16,
        'dimension_code' => 'C:+',
        'required' => true,
        'content' => 'Bạn tỉ mỉ rà soát từng chi tiết trong bản thảo đề tài để đảm bảo tính chuẩn xác.',
        'options' => $likertOptions,
    ],
    [
        'id' => '1e94ce95-af0a-4202-93ca-f03838c49f88',
        'code' => 'disc_college_d_017',
        'position' => 17,
        'dimension_code' => 'D:+',
        'required' => true,
        'content' => 'Bạn thúc đẩy nhóm tiếp tục khi dự án gặp trở ngại.',
        'options' => $likertOptions,
    ],
    [
        'id' => '450a491d-d8af-4c3e-a1a1-4d3e73572753',
        'code' => 'disc_college_i_018',
        'position' => 18,
        'dimension_code' => 'I:-',
        'required' => true,
        'content' => 'Bạn thích làm việc độc lập trong không gian riêng hơn là hoạt động nhóm đông người.',
        'options' => $likertOptions,
    ],
    [
        'id' => '96386b08-e7e7-4472-b190-b6e5455d32cb',
        'code' => 'disc_college_s_019',
        'position' => 19,
        'dimension_code' => 'S:+',
        'required' => true,
        'content' => 'Bạn duy trì nhịp làm việc ổn định khi nhiệm vụ kéo dài.',
        'options' => $likertOptions,
    ],
    [
        'id' => '5ddc8c9a-3b10-4df6-bc52-f36c2e6f34c3',
        'code' => 'disc_college_c_020',
        'position' => 20,
        'dimension_code' => 'C:-',
        'required' => true,
        'content' => 'Bạn có xu hướng giải quyết bài tập lớn theo cảm tính thay vì lập kế hoạch bài bản.',
        'options' => $likertOptions,
    ],
    [
        'id' => '4c67f461-938b-4440-82a0-4d41c7940ff3',
        'code' => 'disc_college_d_021',
        'position' => 21,
        'dimension_code' => 'D:-',
        'required' => true,
        'content' => 'Bạn ngập ngừng khi cần phản hồi thẳng thắn về phần việc chưa đạt của bạn cùng nhóm.',
        'options' => $likertOptions,
    ],
    [
        'id' => '4c5bf147-ea51-46cc-adbf-a5163894334f',
        'code' => 'disc_college_i_022',
        'position' => 22,
        'dimension_code' => 'I:+',
        'required' => true,
        'content' => 'Bạn thích khích lệ mọi người cùng trao đổi về ý tưởng mới.',
        'options' => $likertOptions,
    ],
    [
        'id' => '6cf969cc-b995-417c-bc78-b13b983f9a0f',
        'code' => 'disc_college_s_023',
        'position' => 23,
        'dimension_code' => 'S:-',
        'required' => true,
        'content' => 'Bạn thấy khó thích nghi khi quy trình nhóm thay đổi.',
        'options' => $likertOptions,
    ],
    [
        'id' => '956ae993-1305-4543-9dc3-89171e1e6d89',
        'code' => 'disc_college_c_024',
        'position' => 24,
        'dimension_code' => 'C:+',
        'required' => true,
        'content' => 'Bạn chủ động xây dựng bảng kế hoạch chi tiết với các mốc kiểm tra tiến độ rõ ràng.',
        'options' => $likertOptions,
    ],
    [
        'id' => '5e03b4ec-130d-4bdd-bbe1-086ad015c43e',
        'code' => 'disc_college_d_025',
        'position' => 25,
        'dimension_code' => 'D:+',
        'required' => true,
        'content' => 'Bạn chủ động nhận phần việc khó khi dự án cần người phụ trách.',
        'options' => $likertOptions,
    ],
    [
        'id' => '9425c1e1-d45a-453c-aaff-3832d4eb1532',
        'code' => 'disc_college_i_026',
        'position' => 26,
        'dimension_code' => 'I:-',
        'required' => true,
        'content' => 'Bạn ít khi chia sẻ kinh nghiệm học tập với bạn cùng lớp.',
        'options' => $likertOptions,
    ],
    [
        'id' => '07be33f1-31a9-4651-8dc6-0cede703edc2',
        'code' => 'disc_college_s_027',
        'position' => 27,
        'dimension_code' => 'S:+',
        'required' => true,
        'content' => 'Bạn giữ bình tĩnh khi làm việc nhóm trong thời gian dài.',
        'options' => $likertOptions,
    ],
    [
        'id' => '74ed3428-d84d-4bb2-82aa-cc563b4c7558',
        'code' => 'disc_college_c_028',
        'position' => 28,
        'dimension_code' => 'C:-',
        'required' => true,
        'content' => 'Bạn thường bỏ qua tiêu chí phụ khi nộp bài.',
        'options' => $likertOptions,
    ],
];

return ['metadata' => $metadata, 'questions' => $questions];
