<?php

declare(strict_types=1);

/**
 * Holland RIASEC assessment catalog - college band.
 *
 * Framework:        holland (scoring version holland-riasec-1.0)
 * Education band:   college - College (vocational/university students)
 * Question count:   30 (Option A, Question Count Decision Gate approved
 *                   2026-08-19T05:38:16Z by the Product Owner)
 * Reverse items:    R/A/E 2 of 5 reversed (40%); I/S/C 3 of 5 reversed (60%)
 * Review state:     published - all content, educational, bias/safety, scoring,
 *                   Product Owner, DCR, and Codex review checkpoints recorded.
 *
 * Question IDs are opaque canonical UUIDs; stable identity lives in the
 * 'code' field (namespace holland_college_*).
 */

$metadata = [
    'framework' => 'holland',
    'education_band' => 'college',
    'scoring_version' => 'holland-riasec-1.0',
    'question_count' => 30,
    'stable_code_namespace' => 'holland_college_',
    'review_state' => 'published',
    'review_events' => [
        ['checkpoint' => 'content_review', 'reviewer' => 'Codex lead reviewer', 'approved_at_utc' => '2026-08-20T05:05:10Z'],
        ['checkpoint' => 'educational_review', 'reviewer' => 'Codex lead reviewer', 'approved_at_utc' => '2026-08-20T05:05:10Z'],
        ['checkpoint' => 'bias_review', 'reviewer' => 'Codex lead reviewer', 'approved_at_utc' => '2026-08-20T05:05:10Z'],
        ['checkpoint' => 'scoring_review', 'reviewer' => 'Codex lead reviewer', 'approved_at_utc' => '2026-08-20T05:05:10Z'],
        ['checkpoint' => 'product_owner_approval', 'reviewer' => 'NCnguyenn', 'approved_at_utc' => '2026-08-20T05:05:10Z'],
        ['checkpoint' => 'codex_schema_review', 'reviewer' => 'Codex lead reviewer', 'approved_at_utc' => '2026-08-20T05:05:10Z'],
    ],
    'schema_hash' => '1897bcc607459fa92c0cbe7ce44d701ee3d0ed251a19e99aa0ba7a42f4ef7389',
    'advisory_disclaimer' => 'Kết quả Holland chỉ mang tính định hướng nghề nghiệp, không phải chẩn đoán tâm lý hay xác nhận nghề nghiệp.',
];

$likertOptions = [
    ['value' => 1, 'label' => 'Hoàn toàn không đồng ý'],
    ['value' => 2, 'label' => 'Không đồng ý'],
    ['value' => 3, 'label' => 'Bình thường'],
    ['value' => 4, 'label' => 'Đồng ý'],
    ['value' => 5, 'label' => 'Hoàn toàn đồng ý'],
];

$questions = [
    [
        'id' => '8cc66ca8-508b-4e19-a8f4-e7d5c51659f2',
        'code' => 'holland_college_r_001',
        'position' => 1,
        'dimension_code' => 'R:+',
        'required' => true,
        'content' => 'Bạn thích vận hành, bảo trì máy móc và thiết bị kỹ thuật trong thực tế.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'a955ca26-e916-48c8-a1d3-3d12080abcfc',
        'code' => 'holland_college_i_002',
        'position' => 2,
        'dimension_code' => 'I:-',
        'required' => true,
        'content' => 'Bạn ít dành thời gian tự tìm hiểu cơ sở khoa học của các vấn đề chuyên môn.',
        'options' => $likertOptions,
    ],
    [
        'id' => '2bdc0c6f-183d-45b7-9698-6a8bd8cb610f',
        'code' => 'holland_college_a_003',
        'position' => 3,
        'dimension_code' => 'A:+',
        'required' => true,
        'content' => 'Bạn thích thể hiện ý tưởng qua thiết kế, viết lách hoặc các hình thức nghệ thuật.',
        'options' => $likertOptions,
    ],
    [
        'id' => '11fa5327-09cf-416b-ab5b-2c4c4a664d8c',
        'code' => 'holland_college_s_004',
        'position' => 4,
        'dimension_code' => 'S:-',
        'required' => true,
        'content' => 'Bạn ít khi chủ động hỗ trợ bạn học hoặc đồng nghiệp trong công việc.',
        'options' => $likertOptions,
    ],
    [
        'id' => '941797a0-78f5-4dd0-9b5b-fcf51750a7d9',
        'code' => 'holland_college_e_005',
        'position' => 5,
        'dimension_code' => 'E:+',
        'required' => true,
        'content' => 'Bạn thích đề xuất sáng kiến và thuyết phục người khác cùng thực hiện.',
        'options' => $likertOptions,
    ],
    [
        'id' => '4a470f78-aba1-4d91-b0b3-4ec4fee1a3e8',
        'code' => 'holland_college_c_006',
        'position' => 6,
        'dimension_code' => 'C:-',
        'required' => true,
        'content' => 'Bạn không thích làm việc theo quy trình chuẩn và các biểu mẫu chi tiết.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'dc1c6e82-aaf6-4f45-a420-33f8e0f51d3b',
        'code' => 'holland_college_r_007',
        'position' => 7,
        'dimension_code' => 'R:-',
        'required' => true,
        'content' => 'Bạn ít hứng thú với các công việc đòi hỏi thao tác kỹ thuật trực tiếp.',
        'options' => $likertOptions,
    ],
    [
        'id' => '5d7abe7b-42e3-4799-97f3-341481c2cca3',
        'code' => 'holland_college_i_008',
        'position' => 8,
        'dimension_code' => 'I:+',
        'required' => true,
        'content' => 'Bạn thích phân tích dữ liệu và lập luận để giải quyết vấn đề phức tạp.',
        'options' => $likertOptions,
    ],
    [
        'id' => '5bbaefda-0c43-41cf-81f5-aa8ef3397fd6',
        'code' => 'holland_college_a_009',
        'position' => 9,
        'dimension_code' => 'A:-',
        'required' => true,
        'content' => 'Bạn ít hứng thú với các công việc đòi hỏi sự sáng tạo và thẩm mỹ.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'cee0195a-9d7d-4795-b33b-ff9951fe4854',
        'code' => 'holland_college_s_010',
        'position' => 10,
        'dimension_code' => 'S:+',
        'required' => true,
        'content' => 'Bạn thích tham gia các hoạt động phục vụ cộng đồng.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'cf510f12-83a3-4a3d-a8ae-fd2f7acf0f63',
        'code' => 'holland_college_e_011',
        'position' => 11,
        'dimension_code' => 'E:-',
        'required' => true,
        'content' => 'Bạn thường để người khác dẫn dắt và quyết định hướng đi của nhóm.',
        'options' => $likertOptions,
    ],
    [
        'id' => '28af44f4-745c-4f3a-86f9-5b45d922718b',
        'code' => 'holland_college_c_012',
        'position' => 12,
        'dimension_code' => 'C:+',
        'required' => true,
        'content' => 'Bạn thích tổ chức tài liệu, dữ liệu và hồ sơ một cách hệ thống.',
        'options' => $likertOptions,
    ],
    [
        'id' => '786f1981-4c94-4dda-8438-fc71601429e5',
        'code' => 'holland_college_r_013',
        'position' => 13,
        'dimension_code' => 'R:+',
        'required' => true,
        'content' => 'Bạn muốn được thực hành trong xưởng, phòng thí nghiệm hoặc công trường.',
        'options' => $likertOptions,
    ],
    [
        'id' => '4d793622-6c24-45fb-bc97-f438c9561f96',
        'code' => 'holland_college_i_014',
        'position' => 14,
        'dimension_code' => 'I:-',
        'required' => true,
        'content' => 'Bạn không hứng thú với việc đọc tài liệu chuyên sâu để mở rộng hiểu biết.',
        'options' => $likertOptions,
    ],
    [
        'id' => '31118899-36c9-46a2-9564-9fede8802464',
        'code' => 'holland_college_a_015',
        'position' => 15,
        'dimension_code' => 'A:+',
        'required' => true,
        'content' => 'Bạn muốn tạo ra sản phẩm mang phong cách và dấu ấn cá nhân.',
        'options' => $likertOptions,
    ],
    [
        'id' => '76ae4eb3-808f-4598-acd4-ef81dc37a095',
        'code' => 'holland_college_s_016',
        'position' => 16,
        'dimension_code' => 'S:-',
        'required' => true,
        'content' => 'Bạn ít hứng thú với các công việc tư vấn hoặc hỗ trợ người khác.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'ad302989-d23e-47d2-a981-67ec145fb814',
        'code' => 'holland_college_e_017',
        'position' => 17,
        'dimension_code' => 'E:+',
        'required' => true,
        'content' => 'Bạn muốn tổ chức sự kiện, câu lạc bộ hoặc dự án khởi nghiệp.',
        'options' => $likertOptions,
    ],
    [
        'id' => '536761d1-1ce9-4871-80e6-0ed2b7d219ae',
        'code' => 'holland_college_c_018',
        'position' => 18,
        'dimension_code' => 'C:-',
        'required' => true,
        'content' => 'Bạn thấy gò bó khi phải tuân thủ nghiêm ngặt các quy định và thời hạn.',
        'options' => $likertOptions,
    ],
    [
        'id' => '886d64a2-7ac6-4bbe-9971-a4a8f6ed1ee1',
        'code' => 'holland_college_r_019',
        'position' => 19,
        'dimension_code' => 'R:-',
        'required' => true,
        'content' => 'Bạn không thích các ngành nghề gắn với dụng cụ và thiết bị cơ khí.',
        'options' => $likertOptions,
    ],
    [
        'id' => '5a626615-c801-4c99-bc27-be9645701ea0',
        'code' => 'holland_college_i_020',
        'position' => 20,
        'dimension_code' => 'I:+',
        'required' => true,
        'content' => 'Bạn muốn tham gia các nhóm nghiên cứu hoặc dự án tìm giải pháp mới.',
        'options' => $likertOptions,
    ],
    [
        'id' => '3ec3c853-928c-4802-972f-7b403f72444f',
        'code' => 'holland_college_a_021',
        'position' => 21,
        'dimension_code' => 'A:-',
        'required' => true,
        'content' => 'Bạn không thích các dự án đòi hỏi trí tưởng tượng và cách tiếp cận mới.',
        'options' => $likertOptions,
    ],
    [
        'id' => '97f6402c-8695-48eb-b692-08dbbf7fcaed',
        'code' => 'holland_college_s_022',
        'position' => 22,
        'dimension_code' => 'S:+',
        'required' => true,
        'content' => 'Bạn thấy có động lực khi giúp người khác học tập và phát triển.',
        'options' => $likertOptions,
    ],
    [
        'id' => '0ca0fae1-dc92-498c-baa5-8a59791289b0',
        'code' => 'holland_college_e_023',
        'position' => 23,
        'dimension_code' => 'E:-',
        'required' => true,
        'content' => 'Bạn ít khi xung phong đảm nhận vai trò lãnh đạo trong các dự án.',
        'options' => $likertOptions,
    ],
    [
        'id' => '13276164-e08a-410b-9514-aa807385165d',
        'code' => 'holland_college_c_024',
        'position' => 24,
        'dimension_code' => 'C:+',
        'required' => true,
        'content' => 'Bạn thích lập kế hoạch chi tiết và theo dõi tiến độ công việc cẩn thận.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'e488f490-8e42-4c21-acfc-f9a20bdd4895',
        'code' => 'holland_college_r_025',
        'position' => 25,
        'dimension_code' => 'R:+',
        'required' => true,
        'content' => 'Bạn thấy hứng thú với các học phần thiên về thực hành và thao tác kỹ thuật.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'c00ecc70-4681-4280-9b37-933b4dbfbccf',
        'code' => 'holland_college_i_026',
        'position' => 26,
        'dimension_code' => 'I:-',
        'required' => true,
        'content' => 'Bạn ít hứng thú với việc suy luận và kiểm chứng giả thuyết.',
        'options' => $likertOptions,
    ],
    [
        'id' => '7d43be1c-ba89-476f-85f0-bc44853f7d13',
        'code' => 'holland_college_a_027',
        'position' => 27,
        'dimension_code' => 'A:+',
        'required' => true,
        'content' => 'Bạn thấy hứng thú khi được tự do sáng tạo trong các đồ án môn học.',
        'options' => $likertOptions,
    ],
    [
        'id' => '5b40704b-1736-479b-8b29-5ea0e34e74d3',
        'code' => 'holland_college_s_028',
        'position' => 28,
        'dimension_code' => 'S:-',
        'required' => true,
        'content' => 'Bạn ít khi để ý đến cảm xúc và nhu cầu của người khác.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'baa58ee8-a22b-45e5-8f27-e800840f966e',
        'code' => 'holland_college_e_029',
        'position' => 29,
        'dimension_code' => 'E:+',
        'required' => true,
        'content' => 'Bạn thấy hứng thú với các cuộc thi kinh doanh và thử thách lãnh đạo.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'aa29dbe4-0e2c-4c7e-a871-48fb7d454653',
        'code' => 'holland_college_c_030',
        'position' => 30,
        'dimension_code' => 'C:-',
        'required' => true,
        'content' => 'Bạn ít khi kiểm tra và đối chiếu thông tin trước khi hoàn thành công việc.',
        'options' => $likertOptions,
    ],
];

return ['metadata' => $metadata, 'questions' => $questions];
