<?php

declare(strict_types=1);

/**
 * Holland RIASEC assessment catalog - high band.
 *
 * Framework:        holland (scoring version holland-riasec-1.0)
 * Education band:   high - High (grades 10-12)
 * Question count:   30 (Option A, Question Count Decision Gate approved
 *                   2026-08-19T05:38:16Z by the Product Owner)
 * Reverse items:    R/A/E 2 of 5 reversed (40%); I/S/C 3 of 5 reversed (60%)
 * Review state:     published - all content, educational, bias/safety, scoring,
 *                   Product Owner, DCR, and Codex review checkpoints recorded.
 *
 * Question IDs are opaque canonical UUIDs; stable identity lives in the
 * 'code' field (namespace holland_high_*).
 */

$metadata = [
    'framework' => 'holland',
    'education_band' => 'high',
    'scoring_version' => 'holland-riasec-1.0',
    'question_count' => 30,
    'stable_code_namespace' => 'holland_high_',
    'review_state' => 'published',
    'review_events' => [
        ['checkpoint' => 'content_review', 'reviewer' => 'Codex lead reviewer', 'approved_at_utc' => '2026-08-20T05:05:10Z'],
        ['checkpoint' => 'educational_review', 'reviewer' => 'Codex lead reviewer', 'approved_at_utc' => '2026-08-20T05:05:10Z'],
        ['checkpoint' => 'bias_review', 'reviewer' => 'Codex lead reviewer', 'approved_at_utc' => '2026-08-20T05:05:10Z'],
        ['checkpoint' => 'scoring_review', 'reviewer' => 'Codex lead reviewer', 'approved_at_utc' => '2026-08-20T05:05:10Z'],
        ['checkpoint' => 'product_owner_approval', 'reviewer' => 'NCnguyenn', 'approved_at_utc' => '2026-08-20T05:05:10Z'],
        ['checkpoint' => 'codex_schema_review', 'reviewer' => 'Codex lead reviewer', 'approved_at_utc' => '2026-08-20T05:05:10Z'],
    ],
    'schema_hash' => '6ae9fe0b9404cdf70c6b3d785b384247ddf6861ad338f960663538aa4bb2f998',
    'advisory_disclaimer' => 'Kết quả Holland chỉ mang tính định hướng nghề nghiệp, không phải chẩn đoán tâm lý hay xác nhận nghề nghiệp.',
];

$likertOptions = [
    ['value' => 1, 'label' => 'Hoàn toàn không đồng ý'],
    ['value' => 2, 'label' => 'Không đồng ý'],
    ['value' => 3, 'label' => 'Bình thường'],
    ['value' => 4, 'label' => 'Đồng ý'],
    ['value' => 5, 'label' => 'Hoàn toàn đồng ý'],
];

$questions = [
    [
        'id' => '416dbd91-8553-40fb-99ed-bf7d673133c3',
        'code' => 'holland_high_r_001',
        'position' => 1,
        'dimension_code' => 'R:+',
        'required' => true,
        'content' => 'Bạn thích tìm hiểu cách máy móc và thiết bị hoạt động.',
        'options' => $likertOptions,
    ],
    [
        'id' => '2fa554ea-8931-42d5-b5f4-30beb5734a2c',
        'code' => 'holland_high_i_002',
        'position' => 2,
        'dimension_code' => 'I:-',
        'required' => true,
        'content' => 'Bạn ít dành thời gian tìm hiểu nguyên nhân của các hiện tượng.',
        'options' => $likertOptions,
    ],
    [
        'id' => '40389b5a-eef5-4e94-a595-2bf9305d2133',
        'code' => 'holland_high_a_003',
        'position' => 3,
        'dimension_code' => 'A:+',
        'required' => true,
        'content' => 'Bạn thích thể hiện ý tưởng qua vẽ, viết hoặc âm nhạc.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'ae6090be-2945-47a3-8ec8-a07bd7c72b9a',
        'code' => 'holland_high_s_004',
        'position' => 4,
        'dimension_code' => 'S:-',
        'required' => true,
        'content' => 'Bạn ít khi chủ động hỗ trợ bạn bè trong học tập.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'b1265963-afa2-4514-b4b9-4876e9a4e7b9',
        'code' => 'holland_high_e_005',
        'position' => 5,
        'dimension_code' => 'E:+',
        'required' => true,
        'content' => 'Bạn thích đề xuất ý tưởng và thuyết phục người khác.',
        'options' => $likertOptions,
    ],
    [
        'id' => '9d4d3ae9-6986-4b81-80c0-05ca052343c8',
        'code' => 'holland_high_c_006',
        'position' => 6,
        'dimension_code' => 'C:-',
        'required' => true,
        'content' => 'Bạn không thích làm việc theo quy trình và thời khóa biểu.',
        'options' => $likertOptions,
    ],
    [
        'id' => '52795f8e-4103-47e6-a30d-3ebe52f683fa',
        'code' => 'holland_high_r_007',
        'position' => 7,
        'dimension_code' => 'R:-',
        'required' => true,
        'content' => 'Bạn ít hứng thú với các công việc kỹ thuật, sửa chữa.',
        'options' => $likertOptions,
    ],
    [
        'id' => '7c9946b0-2e0f-4f17-9b99-6db433c0e204',
        'code' => 'holland_high_i_008',
        'position' => 8,
        'dimension_code' => 'I:+',
        'required' => true,
        'content' => 'Bạn thích phân tích số liệu để hiểu một vấn đề.',
        'options' => $likertOptions,
    ],
    [
        'id' => '97409d81-ffb3-493f-853e-5a895a332aac',
        'code' => 'holland_high_a_009',
        'position' => 9,
        'dimension_code' => 'A:-',
        'required' => true,
        'content' => 'Bạn ít hứng thú với các môn nghệ thuật và sáng tạo.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'dbaa064a-c10a-4ce1-8c9a-4ce3fb7c2432',
        'code' => 'holland_high_s_010',
        'position' => 10,
        'dimension_code' => 'S:+',
        'required' => true,
        'content' => 'Bạn thích tham gia các hoạt động tình nguyện, cộng đồng.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'db081882-153f-49c8-81e1-9af5c768d8d5',
        'code' => 'holland_high_e_011',
        'position' => 11,
        'dimension_code' => 'E:-',
        'required' => true,
        'content' => 'Bạn thường để người khác dẫn dắt trong làm việc nhóm.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'e165b8b9-6a06-4f1e-a06d-e335bd566e5c',
        'code' => 'holland_high_c_012',
        'position' => 12,
        'dimension_code' => 'C:+',
        'required' => true,
        'content' => 'Bạn thích sắp xếp tài liệu học tập một cách hệ thống.',
        'options' => $likertOptions,
    ],
    [
        'id' => '0c6bade7-7da5-4b10-8082-ca5b77578162',
        'code' => 'holland_high_r_013',
        'position' => 13,
        'dimension_code' => 'R:+',
        'required' => true,
        'content' => 'Bạn thích chế tạo, lắp ráp mô hình hoặc tìm hiểu về robotics.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'cc90fa56-90eb-4c91-88ce-12e5fa807167',
        'code' => 'holland_high_i_014',
        'position' => 14,
        'dimension_code' => 'I:-',
        'required' => true,
        'content' => 'Bạn không thích đào sâu suy nghĩ về các câu hỏi khó.',
        'options' => $likertOptions,
    ],
    [
        'id' => '4f0a13b4-4d84-4310-9f67-600d3ff8d1f8',
        'code' => 'holland_high_a_015',
        'position' => 15,
        'dimension_code' => 'A:+',
        'required' => true,
        'content' => 'Bạn thích tạo ra sản phẩm mang dấu ấn cá nhân.',
        'options' => $likertOptions,
    ],
    [
        'id' => '0e6aacc8-ed9c-406f-b552-a7061c729482',
        'code' => 'holland_high_s_016',
        'position' => 16,
        'dimension_code' => 'S:-',
        'required' => true,
        'content' => 'Bạn ít hứng thú với việc hỗ trợ người khác trong hoạt động nhóm.',
        'options' => $likertOptions,
    ],
    [
        'id' => '5cac5980-e1a1-4f3c-844d-60a088dba8d2',
        'code' => 'holland_high_e_017',
        'position' => 17,
        'dimension_code' => 'E:+',
        'required' => true,
        'content' => 'Bạn thích tổ chức sự kiện hoặc hoạt động cho lớp.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'b0d62071-29bd-4b76-a114-bcdd9fe047fb',
        'code' => 'holland_high_c_018',
        'position' => 18,
        'dimension_code' => 'C:-',
        'required' => true,
        'content' => 'Bạn thấy gò bó khi phải tuân thủ các quy định chi tiết.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'a6928e26-7ba4-49c3-94ed-d9cfdc56271e',
        'code' => 'holland_high_r_019',
        'position' => 19,
        'dimension_code' => 'R:-',
        'required' => true,
        'content' => 'Bạn không thích làm việc với dụng cụ và thiết bị.',
        'options' => $likertOptions,
    ],
    [
        'id' => '8e337585-cd58-407a-abde-754ce5fdbe64',
        'code' => 'holland_high_i_020',
        'position' => 20,
        'dimension_code' => 'I:+',
        'required' => true,
        'content' => 'Bạn thích tự nghiên cứu một chủ đề mình quan tâm.',
        'options' => $likertOptions,
    ],
    [
        'id' => '4ef3fb66-b32d-476c-841a-5657eea8ba6f',
        'code' => 'holland_high_a_021',
        'position' => 21,
        'dimension_code' => 'A:-',
        'required' => true,
        'content' => 'Bạn không thích các hoạt động đòi hỏi trí tưởng tượng.',
        'options' => $likertOptions,
    ],
    [
        'id' => '27ba930e-1b04-46c2-88d6-1e6002bb295b',
        'code' => 'holland_high_s_022',
        'position' => 22,
        'dimension_code' => 'S:+',
        'required' => true,
        'content' => 'Bạn thấy vui khi giúp người khác hiểu một vấn đề.',
        'options' => $likertOptions,
    ],
    [
        'id' => '571bbff8-72e8-4222-940d-c0048dabeab9',
        'code' => 'holland_high_e_023',
        'position' => 23,
        'dimension_code' => 'E:-',
        'required' => true,
        'content' => 'Bạn ít khi nhận vai trò trưởng nhóm.',
        'options' => $likertOptions,
    ],
    [
        'id' => '7627c88c-6a0a-4675-916b-2a81b60fd60d',
        'code' => 'holland_high_c_024',
        'position' => 24,
        'dimension_code' => 'C:+',
        'required' => true,
        'content' => 'Bạn thích lập kế hoạch và theo dõi tiến độ công việc.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'd34409a7-f697-4071-88d8-4d1000c83b24',
        'code' => 'holland_high_r_025',
        'position' => 25,
        'dimension_code' => 'R:+',
        'required' => true,
        'content' => 'Bạn thấy hứng thú với các hoạt động thực hành kỹ thuật.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'a84de476-029d-4f65-89d5-4cbc67a6f785',
        'code' => 'holland_high_i_026',
        'position' => 26,
        'dimension_code' => 'I:-',
        'required' => true,
        'content' => 'Bạn ít hứng thú với việc lập luận và kiểm chứng một vấn đề.',
        'options' => $likertOptions,
    ],
    [
        'id' => '3fc174d8-441e-4a8e-9516-c43f1e355ec8',
        'code' => 'holland_high_a_027',
        'position' => 27,
        'dimension_code' => 'A:+',
        'required' => true,
        'content' => 'Bạn thấy hứng thú khi được tự do sáng tạo trong học tập.',
        'options' => $likertOptions,
    ],
    [
        'id' => '86f866ec-893f-4717-9c67-1d27842971ae',
        'code' => 'holland_high_s_028',
        'position' => 28,
        'dimension_code' => 'S:-',
        'required' => true,
        'content' => 'Bạn ít quan tâm đến việc xây dựng mối quan hệ bạn bè.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'bed5d883-da25-4c5f-ae77-ffa6bab0e83e',
        'code' => 'holland_high_e_029',
        'position' => 29,
        'dimension_code' => 'E:+',
        'required' => true,
        'content' => 'Bạn thấy hứng thú với các cuộc thi lãnh đạo hoặc kinh doanh.',
        'options' => $likertOptions,
    ],
    [
        'id' => '41a193f8-029b-414f-8a26-4caf8c63ec2e',
        'code' => 'holland_high_c_030',
        'position' => 30,
        'dimension_code' => 'C:-',
        'required' => true,
        'content' => 'Bạn ít khi ghi chú và kiểm tra lại thông tin cẩn thận.',
        'options' => $likertOptions,
    ],
];

return ['metadata' => $metadata, 'questions' => $questions];
