<?php

declare(strict_types=1);

/**
 * Holland RIASEC assessment catalog - middle band.
 *
 * Framework:        holland (scoring version holland-riasec-1.0)
 * Education band:   middle - Middle (grades 6-9)
 * Question count:   30 (Option A, Question Count Decision Gate approved
 *                   2026-08-19T05:38:16Z by the Product Owner)
 * Reverse items:    R/A/E 2 of 5 reversed (40%); I/S/C 3 of 5 reversed (60%)
 * Review state:     published - all content, educational, bias/safety, scoring,
 *                   Product Owner, DCR, and Codex review checkpoints recorded.
 *
 * Question IDs are opaque canonical UUIDs; stable identity lives in the
 * 'code' field (namespace holland_middle_*).
 */

$metadata = [
    'framework' => 'holland',
    'education_band' => 'middle',
    'scoring_version' => 'holland-riasec-1.0',
    'question_count' => 30,
    'stable_code_namespace' => 'holland_middle_',
    'review_state' => 'published',
    'review_events' => [
        ['checkpoint' => 'content_review', 'reviewer' => 'Codex lead reviewer', 'approved_at_utc' => '2026-08-20T05:05:10Z'],
        ['checkpoint' => 'educational_review', 'reviewer' => 'Codex lead reviewer', 'approved_at_utc' => '2026-08-20T05:05:10Z'],
        ['checkpoint' => 'bias_review', 'reviewer' => 'Codex lead reviewer', 'approved_at_utc' => '2026-08-20T05:05:10Z'],
        ['checkpoint' => 'scoring_review', 'reviewer' => 'Codex lead reviewer', 'approved_at_utc' => '2026-08-20T05:05:10Z'],
        ['checkpoint' => 'product_owner_approval', 'reviewer' => 'NCnguyenn', 'approved_at_utc' => '2026-08-20T05:05:10Z'],
        ['checkpoint' => 'codex_schema_review', 'reviewer' => 'Codex lead reviewer', 'approved_at_utc' => '2026-08-20T05:05:10Z'],
    ],
    'schema_hash' => '8425c2f8f9d4ffe4850831b372a1e3e6ecc8da58b2342f602f6cbcf09719528c',
    'advisory_disclaimer' => 'Kết quả Holland chỉ mang tính định hướng nghề nghiệp, không phải chẩn đoán tâm lý hay xác nhận nghề nghiệp.',
];

$likertOptions = [
    ['value' => 1, 'label' => 'Hoàn toàn không đồng ý'],
    ['value' => 2, 'label' => 'Không đồng ý'],
    ['value' => 3, 'label' => 'Bình thường'],
    ['value' => 4, 'label' => 'Đồng ý'],
    ['value' => 5, 'label' => 'Hoàn toàn đồng ý'],
];

$questions = [
    [
        'id' => '6c894f00-208d-465a-b8c7-aac88f23665f',
        'code' => 'holland_middle_r_001',
        'position' => 1,
        'dimension_code' => 'R:+',
        'required' => true,
        'content' => 'Bạn thích lắp ráp và sửa chữa đồ vật trong nhà.',
        'options' => $likertOptions,
    ],
    [
        'id' => '6bf175e1-f60d-46e1-8e42-3f18d057b0b4',
        'code' => 'holland_middle_i_002',
        'position' => 2,
        'dimension_code' => 'I:-',
        'required' => true,
        'content' => 'Bạn thấy chán khi phải tìm hiểu vì sao sự việc xảy ra.',
        'options' => $likertOptions,
    ],
    [
        'id' => '01f0806d-4c23-40db-a901-30d5902485f0',
        'code' => 'holland_middle_a_003',
        'position' => 3,
        'dimension_code' => 'A:+',
        'required' => true,
        'content' => 'Bạn thích vẽ, nặn đất sét hoặc làm đồ thủ công.',
        'options' => $likertOptions,
    ],
    [
        'id' => '470dc5f6-bdb1-4855-8528-844b18279cd5',
        'code' => 'holland_middle_s_004',
        'position' => 4,
        'dimension_code' => 'S:-',
        'required' => true,
        'content' => 'Bạn không thích giúp đỡ bạn bè trong lớp.',
        'options' => $likertOptions,
    ],
    [
        'id' => '349efac7-5ff7-4a8b-b53c-701df1cce2ee',
        'code' => 'holland_middle_e_005',
        'position' => 5,
        'dimension_code' => 'E:+',
        'required' => true,
        'content' => 'Bạn thích đứng ra tổ chức trò chơi cho lớp.',
        'options' => $likertOptions,
    ],
    [
        'id' => '252c1ef3-3cb6-4bfe-bd18-0d23e6afb58e',
        'code' => 'holland_middle_c_006',
        'position' => 6,
        'dimension_code' => 'C:-',
        'required' => true,
        'content' => 'Bạn không thích sắp xếp đồ đạc ngăn nắp.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'f272bfe0-d5e4-4a76-b37f-27318fec7a22',
        'code' => 'holland_middle_r_007',
        'position' => 7,
        'dimension_code' => 'R:-',
        'required' => true,
        'content' => 'Bạn không thích dùng dụng cụ để sửa đồ.',
        'options' => $likertOptions,
    ],
    [
        'id' => '18ff60b5-3a1a-4501-a625-ffd4fa3a3d7c',
        'code' => 'holland_middle_i_008',
        'position' => 8,
        'dimension_code' => 'I:+',
        'required' => true,
        'content' => 'Bạn thích đặt câu hỏi để hiểu sâu hơn về sự vật.',
        'options' => $likertOptions,
    ],
    [
        'id' => '244e9964-7550-41d8-94cd-4c41c95d21c8',
        'code' => 'holland_middle_a_009',
        'position' => 9,
        'dimension_code' => 'A:-',
        'required' => true,
        'content' => 'Bạn ít hứng thú với các hoạt động nghệ thuật.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'a1b04df4-3fe4-44b2-ac59-d0a974f9c635',
        'code' => 'holland_middle_s_010',
        'position' => 10,
        'dimension_code' => 'S:+',
        'required' => true,
        'content' => 'Bạn thích hướng dẫn bạn khác cùng làm bài.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'b80362a5-07bb-446e-bf30-7eb3487fd028',
        'code' => 'holland_middle_e_011',
        'position' => 11,
        'dimension_code' => 'E:-',
        'required' => true,
        'content' => 'Bạn thường chờ người khác quyết định trước.',
        'options' => $likertOptions,
    ],
    [
        'id' => '512acc63-3e0f-4e63-8c3d-ab57a07a4cbb',
        'code' => 'holland_middle_c_012',
        'position' => 12,
        'dimension_code' => 'C:+',
        'required' => true,
        'content' => 'Bạn thích ghi chép bài vở cẩn thận, rõ ràng.',
        'options' => $likertOptions,
    ],
    [
        'id' => '13540f32-d232-432d-ac79-7efd758f7d26',
        'code' => 'holland_middle_r_013',
        'position' => 13,
        'dimension_code' => 'R:+',
        'required' => true,
        'content' => 'Bạn thấy vui khi tự tay làm ra một món đồ.',
        'options' => $likertOptions,
    ],
    [
        'id' => '460b8bbf-7fc0-48c7-bbc5-226851d1f50f',
        'code' => 'holland_middle_i_014',
        'position' => 14,
        'dimension_code' => 'I:-',
        'required' => true,
        'content' => 'Bạn ít tò mò về cách mọi thứ hoạt động.',
        'options' => $likertOptions,
    ],
    [
        'id' => '17375e5f-4990-4b52-88e6-26abfe848bcb',
        'code' => 'holland_middle_a_015',
        'position' => 15,
        'dimension_code' => 'A:+',
        'required' => true,
        'content' => 'Bạn thích tự trang trí góc học tập của mình.',
        'options' => $likertOptions,
    ],
    [
        'id' => '3877173a-9e82-4b5a-aa61-1aa9887f8af8',
        'code' => 'holland_middle_s_016',
        'position' => 16,
        'dimension_code' => 'S:-',
        'required' => true,
        'content' => 'Bạn ít quan tâm đến cảm xúc của người xung quanh.',
        'options' => $likertOptions,
    ],
    [
        'id' => '244f854c-da58-4c5a-833d-b14629bcf2cc',
        'code' => 'holland_middle_e_017',
        'position' => 17,
        'dimension_code' => 'E:+',
        'required' => true,
        'content' => 'Bạn thích thuyết phục bạn bè cùng làm một việc.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'a69b70a1-6638-4896-af26-478d95cd35dc',
        'code' => 'holland_middle_c_018',
        'position' => 18,
        'dimension_code' => 'C:-',
        'required' => true,
        'content' => 'Bạn thấy phiền khi phải làm việc theo kế hoạch.',
        'options' => $likertOptions,
    ],
    [
        'id' => '727c864f-18eb-4b4f-a32d-ee03e0871b9c',
        'code' => 'holland_middle_r_019',
        'position' => 19,
        'dimension_code' => 'R:-',
        'required' => true,
        'content' => 'Bạn ít hứng thú với việc tháo lắp máy móc.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'd79b2e11-04ea-46b3-ac51-6a1e153ba943',
        'code' => 'holland_middle_i_020',
        'position' => 20,
        'dimension_code' => 'I:+',
        'required' => true,
        'content' => 'Bạn thích làm các thí nghiệm đơn giản.',
        'options' => $likertOptions,
    ],
    [
        'id' => '2a64cdd3-eb6c-4174-ac82-715244e1e8c1',
        'code' => 'holland_middle_a_021',
        'position' => 21,
        'dimension_code' => 'A:-',
        'required' => true,
        'content' => 'Bạn không thích tưởng tượng ra những điều mới lạ.',
        'options' => $likertOptions,
    ],
    [
        'id' => '40e60272-2887-4c67-abb9-59c920138b1e',
        'code' => 'holland_middle_s_022',
        'position' => 22,
        'dimension_code' => 'S:+',
        'required' => true,
        'content' => 'Bạn thích cùng bạn bè hợp tác để hoàn thành nhiệm vụ chung.',
        'options' => $likertOptions,
    ],
    [
        'id' => '19dd9921-e7ff-4efc-86b9-cccd782190eb',
        'code' => 'holland_middle_e_023',
        'position' => 23,
        'dimension_code' => 'E:-',
        'required' => true,
        'content' => 'Bạn ít khi xung phong nhận nhiệm vụ mới.',
        'options' => $likertOptions,
    ],
    [
        'id' => '0ebf5b37-5315-4184-b55e-090d9be4de1e',
        'code' => 'holland_middle_c_024',
        'position' => 24,
        'dimension_code' => 'C:+',
        'required' => true,
        'content' => 'Bạn thích lập danh sách những việc cần làm.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'f64acc77-9f16-471e-869d-18f472832682',
        'code' => 'holland_middle_r_025',
        'position' => 25,
        'dimension_code' => 'R:+',
        'required' => true,
        'content' => 'Bạn thích các hoạt động ngoài trời và vận động.',
        'options' => $likertOptions,
    ],
    [
        'id' => '5863357f-f732-4048-8406-da0dc305412b',
        'code' => 'holland_middle_i_026',
        'position' => 26,
        'dimension_code' => 'I:-',
        'required' => true,
        'content' => 'Bạn ít hứng thú với việc tìm lời giải cho một vấn đề khó.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'fc1fd8f1-c320-4fb8-88d6-1c531813aaba',
        'code' => 'holland_middle_a_027',
        'position' => 27,
        'dimension_code' => 'A:+',
        'required' => true,
        'content' => 'Bạn thấy vui khi được sáng tạo theo cách riêng.',
        'options' => $likertOptions,
    ],
    [
        'id' => '12047d93-eb04-4e5f-9e88-04ea82737ae4',
        'code' => 'holland_middle_s_028',
        'position' => 28,
        'dimension_code' => 'S:-',
        'required' => true,
        'content' => 'Bạn ít hứng thú với việc lắng nghe và hỗ trợ bạn bè.',
        'options' => $likertOptions,
    ],
    [
        'id' => '41faba95-f8ed-4007-b8af-89fd2a9c60dc',
        'code' => 'holland_middle_e_029',
        'position' => 29,
        'dimension_code' => 'E:+',
        'required' => true,
        'content' => 'Bạn thích dẫn đầu một nhóm nhỏ trong lớp.',
        'options' => $likertOptions,
    ],
    [
        'id' => '81a92de1-7b6d-452a-a06f-df6e34b63abc',
        'code' => 'holland_middle_c_030',
        'position' => 30,
        'dimension_code' => 'C:-',
        'required' => true,
        'content' => 'Bạn ít khi kiểm tra lại bài trước khi nộp.',
        'options' => $likertOptions,
    ],
];

return ['metadata' => $metadata, 'questions' => $questions];
