<?php

declare(strict_types=1);

/**
 * MBTI assessment catalog - middle band.
 *
 * Framework:        mbti (scoring version mbti-education-1.0)
 * Education band:   middle - Middle (grades 6-9)
 * Question count:   32 (Option A, Question Count Decision Gate approved
 *                   2026-08-19T05:38:16Z by the Product Owner)
 * Balance:          4 stated items per pole across 8 poles (E, I, S, N, T, F, J, P)
 * Review state:     published - all content, educational, bias/safety, scoring,
 *                   Product Owner, DCR, and Codex review checkpoints recorded.
 *
 * Question IDs are opaque canonical UUIDs; stable identity lives in the
 * 'code' field (namespace mbti_middle_*).
 */

$metadata = [
    'framework' => 'mbti',
    'education_band' => 'middle',
    'scoring_version' => 'mbti-education-1.0',
    'question_count' => 32,
    'stable_code_namespace' => 'mbti_middle_',
    'review_state' => 'published',
    'review_events' => [
        ['checkpoint' => 'content_review', 'reviewer' => 'Codex lead reviewer', 'approved_at_utc' => '2026-08-20T05:05:10Z'],
        ['checkpoint' => 'educational_review', 'reviewer' => 'Codex lead reviewer', 'approved_at_utc' => '2026-08-20T05:05:10Z'],
        ['checkpoint' => 'bias_review', 'reviewer' => 'Codex lead reviewer', 'approved_at_utc' => '2026-08-20T05:05:10Z'],
        ['checkpoint' => 'scoring_review', 'reviewer' => 'Codex lead reviewer', 'approved_at_utc' => '2026-08-20T05:05:10Z'],
        ['checkpoint' => 'product_owner_approval', 'reviewer' => 'NCnguyenn', 'approved_at_utc' => '2026-08-20T05:05:10Z'],
        ['checkpoint' => 'codex_schema_review', 'reviewer' => 'Codex lead reviewer', 'approved_at_utc' => '2026-08-20T05:05:10Z'],
    ],
    'schema_hash' => '35a05b672397725097da7937d38d515c12b9074fd2a57db3167c0e6c5fbe7f12',
    'advisory_disclaimer' => 'Đây là bộ câu hỏi định hướng học tập nội bộ, không phải công cụ MBTI chính thức hay đánh giá tâm lý.',
];

$likertOptions = [
    ['value' => 1, 'label' => 'Hoàn toàn không đồng ý'],
    ['value' => 2, 'label' => 'Không đồng ý'],
    ['value' => 3, 'label' => 'Bình thường'],
    ['value' => 4, 'label' => 'Đồng ý'],
    ['value' => 5, 'label' => 'Hoàn toàn đồng ý'],
];

$questions = [
    [
        'id' => '030d54b1-bcc1-4f3b-7bd4-9077fc8c7aea',
        'code' => 'mbti_middle_ei_e_001',
        'position' => 1,
        'dimension_code' => 'EI:E',
        'required' => true,
        'content' => 'Bạn thích trao đổi và học cùng các bạn trong lớp.',
        'options' => $likertOptions,
    ],
    [
        'id' => '3931bcab-19be-4685-241d-32c2f52f1c32',
        'code' => 'mbti_middle_ei_i_002',
        'position' => 2,
        'dimension_code' => 'EI:I',
        'required' => true,
        'content' => 'Bạn thích tự đọc sách ở nơi yên tĩnh một mình.',
        'options' => $likertOptions,
    ],
    [
        'id' => '897c7920-b119-487e-37c1-56edf9f0c40f',
        'code' => 'mbti_middle_sn_s_003',
        'position' => 3,
        'dimension_code' => 'SN:S',
        'required' => true,
        'content' => 'Bạn thích làm bài tập có hướng dẫn từng bước rõ ràng.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'bc36ca66-9f8e-4008-7888-4078954f1c5f',
        'code' => 'mbti_middle_sn_n_004',
        'position' => 4,
        'dimension_code' => 'SN:N',
        'required' => true,
        'content' => 'Bạn thích tưởng tượng ra những ý tưởng mới lạ.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'c9d7ea2c-cfa8-4628-dcfd-6afdf9e59156',
        'code' => 'mbti_middle_tf_t_005',
        'position' => 5,
        'dimension_code' => 'TF:T',
        'required' => true,
        'content' => 'Bạn coi trọng lập luận có căn cứ rõ ràng.',
        'options' => $likertOptions,
    ],
    [
        'id' => '7c1d7bbf-b5a4-4241-d6ac-7b13f32ab71f',
        'code' => 'mbti_middle_tf_f_006',
        'position' => 6,
        'dimension_code' => 'TF:F',
        'required' => true,
        'content' => 'Khi làm việc nhóm, bạn chú ý đến cảm xúc của bạn bè.',
        'options' => $likertOptions,
    ],
    [
        'id' => '578ebec8-4724-4f41-3e85-328e1b30a3de',
        'code' => 'mbti_middle_jp_j_007',
        'position' => 7,
        'dimension_code' => 'JP:J',
        'required' => true,
        'content' => 'Bạn thích lập kế hoạch học tập trước khi bắt đầu.',
        'options' => $likertOptions,
    ],
    [
        'id' => '411155d0-eb62-43ea-6e91-7d9900985c5e',
        'code' => 'mbti_middle_jp_p_008',
        'position' => 8,
        'dimension_code' => 'JP:P',
        'required' => true,
        'content' => 'Bạn thích giữ cách làm bài linh hoạt.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'cfcef627-bbbf-4dcf-efc6-897f90d1f22e',
        'code' => 'mbti_middle_ei_e_009',
        'position' => 9,
        'dimension_code' => 'EI:E',
        'required' => true,
        'content' => 'Bạn cảm thấy vui khi được thảo luận sôi nổi trên lớp.',
        'options' => $likertOptions,
    ],
    [
        'id' => '50e38d14-5e1f-4ee4-cabc-491928696082',
        'code' => 'mbti_middle_ei_i_010',
        'position' => 10,
        'dimension_code' => 'EI:I',
        'required' => true,
        'content' => 'Bạn cần không gian riêng để tập trung suy nghĩ kỹ hơn.',
        'options' => $likertOptions,
    ],
    [
        'id' => '5088af16-be7d-41f4-ab31-c542f5625d8b',
        'code' => 'mbti_middle_sn_s_011',
        'position' => 11,
        'dimension_code' => 'SN:S',
        'required' => true,
        'content' => 'Bạn chú ý đến các chi tiết thực tế trong bài học.',
        'options' => $likertOptions,
    ],
    [
        'id' => '598b3934-cd93-441c-96a3-4b3e3805a12c',
        'code' => 'mbti_middle_sn_n_012',
        'position' => 12,
        'dimension_code' => 'SN:N',
        'required' => true,
        'content' => 'Bạn thích sáng tạo những cách tiếp cận mới cho bài học.',
        'options' => $likertOptions,
    ],
    [
        'id' => '2400535c-9828-407b-4b73-8f7a7d47f38d',
        'code' => 'mbti_middle_tf_t_013',
        'position' => 13,
        'dimension_code' => 'TF:T',
        'required' => true,
        'content' => 'Khi chọn cách giải, bạn ưu tiên bằng chứng rõ ràng.',
        'options' => $likertOptions,
    ],
    [
        'id' => '3b9d2697-c510-448b-32b1-1e38c733dbd9',
        'code' => 'mbti_middle_tf_f_014',
        'position' => 14,
        'dimension_code' => 'TF:F',
        'required' => true,
        'content' => 'Bạn thích lắng nghe và giúp đỡ bạn học khi gặp khó khăn.',
        'options' => $likertOptions,
    ],
    [
        'id' => '56d1db26-a15f-4b11-4457-a548940c8c94',
        'code' => 'mbti_middle_jp_j_015',
        'position' => 15,
        'dimension_code' => 'JP:J',
        'required' => true,
        'content' => 'Bạn thích hoàn thành bài tập theo kế hoạch trước ngày nộp.',
        'options' => $likertOptions,
    ],
    [
        'id' => '26f80f6b-6d48-4cc9-0cb4-d7f3dece70d6',
        'code' => 'mbti_middle_jp_p_016',
        'position' => 16,
        'dimension_code' => 'JP:P',
        'required' => true,
        'content' => 'Bạn cảm thấy thoải mái khi điều chỉnh kế hoạch học tập.',
        'options' => $likertOptions,
    ],
    [
        'id' => '40cee00e-c72a-406e-9779-853ae153872e',
        'code' => 'mbti_middle_ei_e_017',
        'position' => 17,
        'dimension_code' => 'EI:E',
        'required' => true,
        'content' => 'Bạn thích tham gia các hoạt động tập thể cùng bạn bè.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'dcd0a47d-87e0-47f7-efef-ccedf1811a79',
        'code' => 'mbti_middle_ei_i_018',
        'position' => 18,
        'dimension_code' => 'EI:I',
        'required' => true,
        'content' => 'Bạn thấy thoải mái khi tự mình nghiên cứu bài học mới.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'c739f102-c7f5-4a03-32e3-8add0e015223',
        'code' => 'mbti_middle_sn_s_019',
        'position' => 19,
        'dimension_code' => 'SN:S',
        'required' => true,
        'content' => 'Bạn thích học qua ví dụ thực tế.',
        'options' => $likertOptions,
    ],
    [
        'id' => '44eab23d-f3ed-4066-fe57-e1db59c8bd73',
        'code' => 'mbti_middle_sn_n_020',
        'position' => 20,
        'dimension_code' => 'SN:N',
        'required' => true,
        'content' => 'Bạn thích tìm hiểu khả năng xảy ra trong tương lai.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'a1f760e5-d66b-40fa-5010-b81644b92d62',
        'code' => 'mbti_middle_tf_t_021',
        'position' => 21,
        'dimension_code' => 'TF:T',
        'required' => true,
        'content' => 'Bạn thích phân tích nguyên nhân của một kết quả.',
        'options' => $likertOptions,
    ],
    [
        'id' => '7c90a237-b64d-405b-ca59-b1350e206d40',
        'code' => 'mbti_middle_tf_f_022',
        'position' => 22,
        'dimension_code' => 'TF:F',
        'required' => true,
        'content' => 'Khi làm việc nhóm, bạn ưu tiên duy trì sự hòa hợp.',
        'options' => $likertOptions,
    ],
    [
        'id' => '0ecbafe6-c1ab-4525-65dc-9fd064dcf3bb',
        'code' => 'mbti_middle_jp_j_023',
        'position' => 23,
        'dimension_code' => 'JP:J',
        'required' => true,
        'content' => 'Bạn thích giữ sách vở và bàn học ngăn nắp.',
        'options' => $likertOptions,
    ],
    [
        'id' => '505eeb9c-410c-4bfc-d4af-a5b2c62010b2',
        'code' => 'mbti_middle_jp_p_024',
        'position' => 24,
        'dimension_code' => 'JP:P',
        'required' => true,
        'content' => 'Bạn thích để ngỏ cách làm cho đến khi bắt đầu bài tập.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'ddf1be30-127b-4c40-0848-f32a9c1ded09',
        'code' => 'mbti_middle_ei_e_025',
        'position' => 25,
        'dimension_code' => 'EI:E',
        'required' => true,
        'content' => 'Bạn dễ dàng làm quen và trò chuyện với bạn học mới.',
        'options' => $likertOptions,
    ],
    [
        'id' => '84bd92cb-4fb3-4dc3-a935-4fb0eb57217a',
        'code' => 'mbti_middle_ei_i_026',
        'position' => 26,
        'dimension_code' => 'EI:I',
        'required' => true,
        'content' => 'Bạn thường suy nghĩ cẩn thận trước khi phát biểu ý kiến.',
        'options' => $likertOptions,
    ],
    [
        'id' => '794910f6-11cb-4670-86c4-0ee23d1469c7',
        'code' => 'mbti_middle_sn_s_027',
        'position' => 27,
        'dimension_code' => 'SN:S',
        'required' => true,
        'content' => 'Bạn thích dựa vào sự thật và kinh nghiệm đã có sẵn.',
        'options' => $likertOptions,
    ],
    [
        'id' => '148aad22-dd30-45a6-af37-0ff72fe6a5db',
        'code' => 'mbti_middle_sn_n_028',
        'position' => 28,
        'dimension_code' => 'SN:N',
        'required' => true,
        'content' => 'Bạn thích liên tưởng bài học tới những ý tưởng tương lai.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'df8a8ffe-4379-4b5b-d410-a8533ccb594f',
        'code' => 'mbti_middle_tf_t_029',
        'position' => 29,
        'dimension_code' => 'TF:T',
        'required' => true,
        'content' => 'Khi có tranh luận, bạn tập trung vào lập luận và bằng chứng.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'f31b86ea-c057-4c39-1cda-27cec33eca5d',
        'code' => 'mbti_middle_tf_f_030',
        'position' => 30,
        'dimension_code' => 'TF:F',
        'required' => true,
        'content' => 'Bạn muốn khích lệ bạn cùng nhóm khi họ gặp khó khăn.',
        'options' => $likertOptions,
    ],
    [
        'id' => '1946c52f-b482-4c4f-7366-9b49478b3908',
        'code' => 'mbti_middle_jp_j_031',
        'position' => 31,
        'dimension_code' => 'JP:J',
        'required' => true,
        'content' => 'Bạn thích biết trước kế hoạch hoạt động của ngày mai.',
        'options' => $likertOptions,
    ],
    [
        'id' => '799c02f2-22c1-4608-c2ab-e88676f83f14',
        'code' => 'mbti_middle_jp_p_032',
        'position' => 32,
        'dimension_code' => 'JP:P',
        'required' => true,
        'content' => 'Bạn thích ứng biến khi có việc bất ngờ phát sinh.',
        'options' => $likertOptions,
    ],
];

return ['metadata' => $metadata, 'questions' => $questions];
