<?php

declare(strict_types=1);

/**
 * MBTI assessment catalog - college band.
 *
 * Framework:        mbti (scoring version mbti-education-1.0)
 * Education band:   college - College (vocational/university students)
 * Question count:   32 (Option A, Question Count Decision Gate approved
 *                   2026-08-19T05:38:16Z by the Product Owner)
 * Balance:          4 stated items per pole across 8 poles (E, I, S, N, T, F, J, P)
 * Review state:     published - all content, educational, bias/safety, scoring,
 *                   Product Owner, DCR, and Codex review checkpoints recorded.
 *
 * Question IDs are opaque canonical UUIDs; stable identity lives in the
 * 'code' field (namespace mbti_college_*).
 */

$metadata = [
    'framework' => 'mbti',
    'education_band' => 'college',
    'scoring_version' => 'mbti-education-1.0',
    'question_count' => 32,
    'stable_code_namespace' => 'mbti_college_',
    'review_state' => 'published',
    'review_events' => [
        ['checkpoint' => 'content_review', 'reviewer' => 'Codex lead reviewer', 'approved_at_utc' => '2026-08-20T05:05:10Z'],
        ['checkpoint' => 'educational_review', 'reviewer' => 'Codex lead reviewer', 'approved_at_utc' => '2026-08-20T05:05:10Z'],
        ['checkpoint' => 'bias_review', 'reviewer' => 'Codex lead reviewer', 'approved_at_utc' => '2026-08-20T05:05:10Z'],
        ['checkpoint' => 'scoring_review', 'reviewer' => 'Codex lead reviewer', 'approved_at_utc' => '2026-08-20T05:05:10Z'],
        ['checkpoint' => 'product_owner_approval', 'reviewer' => 'NCnguyenn', 'approved_at_utc' => '2026-08-20T05:05:10Z'],
        ['checkpoint' => 'codex_schema_review', 'reviewer' => 'Codex lead reviewer', 'approved_at_utc' => '2026-08-20T05:05:10Z'],
    ],
    'schema_hash' => '6d4948b80b48c98caf5a182cbb16df76af5ba1e1458cfdbf50cd31a902c16d82',
    'advisory_disclaimer' => 'Đây là bộ câu hỏi định hướng học tập nội bộ, không phải công cụ MBTI chính thức hay đánh giá tâm lý.',
];

$likertOptions = [
    ['value' => 1, 'label' => 'Hoàn toàn không đồng ý'],
    ['value' => 2, 'label' => 'Không đồng ý'],
    ['value' => 3, 'label' => 'Bình thường'],
    ['value' => 4, 'label' => 'Đồng ý'],
    ['value' => 5, 'label' => 'Hoàn toàn đồng ý'],
];

$questions = [
    [
        'id' => '3e84a57c-29cd-4e97-bb89-77e62461535d',
        'code' => 'mbti_college_ei_e_001',
        'position' => 1,
        'dimension_code' => 'EI:E',
        'required' => true,
        'content' => 'Bạn chủ động thảo luận học thuật và trao đổi chuyên đề cùng giảng viên và bạn học trong khoa.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'b77063cf-5f94-4c44-1af8-fc43175ffe12',
        'code' => 'mbti_college_ei_i_002',
        'position' => 2,
        'dimension_code' => 'EI:I',
        'required' => true,
        'content' => 'Bạn thích nghiên cứu độc lập trong không gian yên tĩnh.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'cf02eb59-a26a-4ac4-1e00-7af494e6971d',
        'code' => 'mbti_college_sn_s_003',
        'position' => 3,
        'dimension_code' => 'SN:S',
        'required' => true,
        'content' => 'Bạn thích bắt đầu từ dữ liệu và bằng chứng cụ thể.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'f5dc5c6c-c9dd-459a-5e44-2b1ecff147b8',
        'code' => 'mbti_college_sn_n_004',
        'position' => 4,
        'dimension_code' => 'SN:N',
        'required' => true,
        'content' => 'Bạn thích dự phóng những xu hướng phát triển trong tương lai.',
        'options' => $likertOptions,
    ],
    [
        'id' => '1dd74c39-917f-4d8c-cb03-c40cd3f55e0d',
        'code' => 'mbti_college_tf_t_005',
        'position' => 5,
        'dimension_code' => 'TF:T',
        'required' => true,
        'content' => 'Khi phản biện đồ án, bạn sử dụng các lập luận logic và tiêu chuẩn đánh giá mang tính khách quan.',
        'options' => $likertOptions,
    ],
    [
        'id' => '2d2052c9-0bd5-481b-9e72-e187f693382f',
        'code' => 'mbti_college_tf_f_006',
        'position' => 6,
        'dimension_code' => 'TF:F',
        'required' => true,
        'content' => 'Khi làm đề tài nhóm, bạn chú trọng sự đồng thuận.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'e01ea751-2f2a-4ce9-0d66-92df10b5e769',
        'code' => 'mbti_college_jp_j_007',
        'position' => 7,
        'dimension_code' => 'JP:J',
        'required' => true,
        'content' => 'Bạn thích lập tiến độ chi tiết cho đồ án.',
        'options' => $likertOptions,
    ],
    [
        'id' => '34123129-60db-4769-7dc9-9d90be829e88',
        'code' => 'mbti_college_jp_p_008',
        'position' => 8,
        'dimension_code' => 'JP:P',
        'required' => true,
        'content' => 'Bạn giữ cách làm việc linh hoạt để sẵn sàng cập nhật dữ liệu và hướng tiếp cận nghiên cứu mới.',
        'options' => $likertOptions,
    ],
    [
        'id' => '21b0288e-c9de-4336-d33d-054ac8d4101a',
        'code' => 'mbti_college_ei_e_009',
        'position' => 9,
        'dimension_code' => 'EI:E',
        'required' => true,
        'content' => 'Bạn thích tham gia thảo luận chuyên môn cùng người khác.',
        'options' => $likertOptions,
    ],
    [
        'id' => '9a27066a-f391-4319-a7ce-80bae6037911',
        'code' => 'mbti_college_ei_i_010',
        'position' => 10,
        'dimension_code' => 'EI:I',
        'required' => true,
        'content' => 'Bạn dành nhiều thời gian tự chiêm nghiệm, đọc tài liệu sâu trước khi đưa ra nhận định chuyên môn.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'b4d3264b-65af-465f-8171-504d8e0cf316',
        'code' => 'mbti_college_sn_s_011',
        'position' => 11,
        'dimension_code' => 'SN:S',
        'required' => true,
        'content' => 'Bạn thích vận dụng các quy trình đã được kiểm chứng trong thực tế.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'fc8208e6-d354-4c67-0474-0678f311afbd',
        'code' => 'mbti_college_sn_n_012',
        'position' => 12,
        'dimension_code' => 'SN:N',
        'required' => true,
        'content' => 'Bạn thích tìm kiếm những cách tiếp cận mới cho vấn đề phức tạp.',
        'options' => $likertOptions,
    ],
    [
        'id' => '498f0125-3c01-4ff7-b5fd-d6ab639f0361',
        'code' => 'mbti_college_tf_t_013',
        'position' => 13,
        'dimension_code' => 'TF:T',
        'required' => true,
        'content' => 'Bạn đưa ra kết luận dựa trên phân tích nguyên nhân - kết quả và bằng chứng khách quan.',
        'options' => $likertOptions,
    ],
    [
        'id' => '865ef0fe-a820-4830-e3c7-3b504a41cd91',
        'code' => 'mbti_college_tf_f_014',
        'position' => 14,
        'dimension_code' => 'TF:F',
        'required' => true,
        'content' => 'Bạn quan tâm đến tác động xã hội và mức độ phù hợp của giải pháp đối với con người.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'b1d6cfaf-360d-4e5a-7e25-95f8eb0e9b72',
        'code' => 'mbti_college_jp_j_015',
        'position' => 15,
        'dimension_code' => 'JP:J',
        'required' => true,
        'content' => 'Bạn thích theo sát kế hoạch học tập đã xác định từ đầu kỳ.',
        'options' => $likertOptions,
    ],
    [
        'id' => '468f04a6-f116-49b5-dacd-f511d555aa79',
        'code' => 'mbti_college_jp_p_016',
        'position' => 16,
        'dimension_code' => 'JP:P',
        'required' => true,
        'content' => 'Bạn thích ứng với những thay đổi trong môi trường học tập.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'e965b1c9-d9ae-4ac8-02e9-fc82e10c26bf',
        'code' => 'mbti_college_ei_e_017',
        'position' => 17,
        'dimension_code' => 'EI:E',
        'required' => true,
        'content' => 'Bạn thích làm việc nhóm và trao đổi kinh nghiệm học tập.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'fec4be18-b007-4ca3-c0c8-838fa37ac877',
        'code' => 'mbti_college_ei_i_018',
        'position' => 18,
        'dimension_code' => 'EI:I',
        'required' => true,
        'content' => 'Bạn tập trung tốt hơn khi tự phân tích tài liệu và viết báo cáo chuyên ngành một mình.',
        'options' => $likertOptions,
    ],
    [
        'id' => '8ed8e8cb-e66e-4dfd-cd26-7c3df5980a6a',
        'code' => 'mbti_college_sn_s_019',
        'position' => 19,
        'dimension_code' => 'SN:S',
        'required' => true,
        'content' => 'Bạn chú trọng các chi tiết cụ thể trong đề tài.',
        'options' => $likertOptions,
    ],
    [
        'id' => '9a1f4123-f613-4ebc-68df-c7306741450c',
        'code' => 'mbti_college_sn_n_020',
        'position' => 20,
        'dimension_code' => 'SN:N',
        'required' => true,
        'content' => 'Bạn thích liên kết các khái niệm liên ngành để khám phá những góc nhìn học thuật đa chiều.',
        'options' => $likertOptions,
    ],
    [
        'id' => '2346eb6d-25a6-4a24-6865-d01bd29b468b',
        'code' => 'mbti_college_tf_t_021',
        'position' => 21,
        'dimension_code' => 'TF:T',
        'required' => true,
        'content' => 'Bạn ưu tiên sự nhất quán khi đánh giá các phương pháp nghiên cứu.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'b8a54fe0-3b6d-429c-7eb1-1590ec57fae5',
        'code' => 'mbti_college_tf_f_022',
        'position' => 22,
        'dimension_code' => 'TF:F',
        'required' => true,
        'content' => 'Bạn ghi nhận đóng góp của các thành viên trong nhóm.',
        'options' => $likertOptions,
    ],
    [
        'id' => '99c9d10f-27be-420b-3c12-4c2a2a8a87e5',
        'code' => 'mbti_college_jp_j_023',
        'position' => 23,
        'dimension_code' => 'JP:J',
        'required' => true,
        'content' => 'Bạn thích sắp xếp tài liệu học tập có hệ thống.',
        'options' => $likertOptions,
    ],
    [
        'id' => '091a270b-e445-46e2-23a6-f3e737d0026f',
        'code' => 'mbti_college_jp_p_024',
        'position' => 24,
        'dimension_code' => 'JP:P',
        'required' => true,
        'content' => 'Bạn thoải mái khám phá nhiều phương án thay thế trước khi đưa ra quyết định cuối cùng.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'bd864d2e-2065-4996-fed0-f81fa38dbddb',
        'code' => 'mbti_college_ei_e_025',
        'position' => 25,
        'dimension_code' => 'EI:E',
        'required' => true,
        'content' => 'Bạn thích thuyết trình báo cáo học thuật trước người khác.',
        'options' => $likertOptions,
    ],
    [
        'id' => '70275408-d643-4e76-2fec-ee847ca1c530',
        'code' => 'mbti_college_ei_i_026',
        'position' => 26,
        'dimension_code' => 'EI:I',
        'required' => true,
        'content' => 'Bạn thích suy nghĩ và chuẩn bị ý kiến trước khi trao đổi.',
        'options' => $likertOptions,
    ],
    [
        'id' => '9eaeb220-5475-4445-6ff6-b7c1a23cc279',
        'code' => 'mbti_college_sn_s_027',
        'position' => 27,
        'dimension_code' => 'SN:S',
        'required' => true,
        'content' => 'Bạn thích chú ý đến tính khả thi của giải pháp.',
        'options' => $likertOptions,
    ],
    [
        'id' => '7e8ba656-b9d6-4fe9-999f-9fc672947a23',
        'code' => 'mbti_college_sn_n_028',
        'position' => 28,
        'dimension_code' => 'SN:N',
        'required' => true,
        'content' => 'Bạn thích tìm hiểu các khái niệm nền tảng phía sau phát kiến.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'c571ed34-f65e-45d6-5290-b6e6746f996b',
        'code' => 'mbti_college_tf_t_029',
        'position' => 29,
        'dimension_code' => 'TF:T',
        'required' => true,
        'content' => 'Khi giải quyết vấn đề, bạn ưu tiên tiêu chí hiệu quả và bằng chứng.',
        'options' => $likertOptions,
    ],
    [
        'id' => '01a0394a-e9da-4f0c-71df-909835556e92',
        'code' => 'mbti_college_tf_f_030',
        'position' => 30,
        'dimension_code' => 'TF:F',
        'required' => true,
        'content' => 'Bạn coi trọng sự thấu cảm khi hợp tác học thuật.',
        'options' => $likertOptions,
    ],
    [
        'id' => '5b58c2e9-c946-428b-7711-72e44bfa68c7',
        'code' => 'mbti_college_jp_j_031',
        'position' => 31,
        'dimension_code' => 'JP:J',
        'required' => true,
        'content' => 'Bạn thích xây dựng cấu trúc làm việc rõ ràng.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'b6baf9ec-8f9f-46f1-674e-38185fe49351',
        'code' => 'mbti_college_jp_p_032',
        'position' => 32,
        'dimension_code' => 'JP:P',
        'required' => true,
        'content' => 'Bạn thích giữ tư duy linh hoạt trước những hướng nghiên cứu mới.',
        'options' => $likertOptions,
    ],
];

return ['metadata' => $metadata, 'questions' => $questions];
