<?php

declare(strict_types=1);

/**
 * MBTI assessment catalog - high band.
 *
 * Framework:        mbti (scoring version mbti-education-1.0)
 * Education band:   high - High (grades 10-12)
 * Question count:   32 (Option A, Question Count Decision Gate approved
 *                   2026-08-19T05:38:16Z by the Product Owner)
 * Balance:          4 stated items per pole across 8 poles (E, I, S, N, T, F, J, P)
 * Review state:     published - all content, educational, bias/safety, scoring,
 *                   Product Owner, DCR, and Codex review checkpoints recorded.
 *
 * Question IDs are opaque canonical UUIDs; stable identity lives in the
 * 'code' field (namespace mbti_high_*).
 */

$metadata = [
    'framework' => 'mbti',
    'education_band' => 'high',
    'scoring_version' => 'mbti-education-1.0',
    'question_count' => 32,
    'stable_code_namespace' => 'mbti_high_',
    'review_state' => 'published',
    'review_events' => [
        ['checkpoint' => 'content_review', 'reviewer' => 'Codex lead reviewer', 'approved_at_utc' => '2026-08-20T05:05:10Z'],
        ['checkpoint' => 'educational_review', 'reviewer' => 'Codex lead reviewer', 'approved_at_utc' => '2026-08-20T05:05:10Z'],
        ['checkpoint' => 'bias_review', 'reviewer' => 'Codex lead reviewer', 'approved_at_utc' => '2026-08-20T05:05:10Z'],
        ['checkpoint' => 'scoring_review', 'reviewer' => 'Codex lead reviewer', 'approved_at_utc' => '2026-08-20T05:05:10Z'],
        ['checkpoint' => 'product_owner_approval', 'reviewer' => 'NCnguyenn', 'approved_at_utc' => '2026-08-20T05:05:10Z'],
        ['checkpoint' => 'codex_schema_review', 'reviewer' => 'Codex lead reviewer', 'approved_at_utc' => '2026-08-20T05:05:10Z'],
    ],
    'schema_hash' => '2f53e999afa732f0cae590bb69b515c81d8eac079ec1d689115712d1fb98bce6',
    'advisory_disclaimer' => 'Đây là bộ câu hỏi định hướng học tập nội bộ, không phải công cụ MBTI chính thức hay đánh giá tâm lý.',
];

$likertOptions = [
    ['value' => 1, 'label' => 'Hoàn toàn không đồng ý'],
    ['value' => 2, 'label' => 'Không đồng ý'],
    ['value' => 3, 'label' => 'Bình thường'],
    ['value' => 4, 'label' => 'Đồng ý'],
    ['value' => 5, 'label' => 'Hoàn toàn đồng ý'],
];

$questions = [
    [
        'id' => 'bf142c0f-0543-4a36-f45e-79b8648e39c9',
        'code' => 'mbti_high_ei_e_001',
        'position' => 1,
        'dimension_code' => 'EI:E',
        'required' => true,
        'content' => 'Bạn nạp lại năng lượng khi cùng bạn bè thảo luận các chủ đề học tập thú vị.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'b8f334c9-9d16-4f64-ea69-99b39cb87554',
        'code' => 'mbti_high_ei_i_002',
        'position' => 2,
        'dimension_code' => 'EI:I',
        'required' => true,
        'content' => 'Bạn thích học trong không gian yên tĩnh.',
        'options' => $likertOptions,
    ],
    [
        'id' => '20b3c1be-42fc-4d81-4aff-17b5fa0c5557',
        'code' => 'mbti_high_sn_s_003',
        'position' => 3,
        'dimension_code' => 'SN:S',
        'required' => true,
        'content' => 'Bạn thích nắm vững kiến thức thực tế và dữ liệu cụ thể trước khi áp dụng.',
        'options' => $likertOptions,
    ],
    [
        'id' => '5a9e5a14-81dd-40cc-e49b-7f14c255308d',
        'code' => 'mbti_high_sn_n_004',
        'position' => 4,
        'dimension_code' => 'SN:N',
        'required' => true,
        'content' => 'Bạn thích khám phá những khả năng mới trong bài học.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'd220d8a5-7c97-46a1-7376-4d654e75f42f',
        'code' => 'mbti_high_tf_t_005',
        'position' => 5,
        'dimension_code' => 'TF:T',
        'required' => true,
        'content' => 'Khi đánh giá một vấn đề, bạn ưu tiên tiêu chí logic và tính khách quan.',
        'options' => $likertOptions,
    ],
    [
        'id' => '57447382-8af1-4ed6-dca2-ab17c298c7bc',
        'code' => 'mbti_high_tf_f_006',
        'position' => 6,
        'dimension_code' => 'TF:F',
        'required' => true,
        'content' => 'Khi đưa ra quyết định nhóm, bạn coi trọng sự thấu hiểu và cảm xúc của bạn bè.',
        'options' => $likertOptions,
    ],
    [
        'id' => '08d564c4-6b1c-49b4-d38b-1379f0b04acc',
        'code' => 'mbti_high_jp_j_007',
        'position' => 7,
        'dimension_code' => 'JP:J',
        'required' => true,
        'content' => 'Bạn thích lập kế hoạch chi tiết cho kỳ thi.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'c6f24d56-c410-4a8e-149a-61d067f59bc3',
        'code' => 'mbti_high_jp_p_008',
        'position' => 8,
        'dimension_code' => 'JP:P',
        'required' => true,
        'content' => 'Bạn thích giữ lịch trình linh hoạt để dễ thích ứng với cơ hội học tập mới.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'a83fa1e7-3ec4-4f93-41ec-f5a1713fe02a',
        'code' => 'mbti_high_ei_e_009',
        'position' => 9,
        'dimension_code' => 'EI:E',
        'required' => true,
        'content' => 'Bạn thích chủ động chia sẻ ý kiến trong nhóm học tập.',
        'options' => $likertOptions,
    ],
    [
        'id' => '6a5d8e95-e475-4b61-5e08-a190630fe53f',
        'code' => 'mbti_high_ei_i_010',
        'position' => 10,
        'dimension_code' => 'EI:I',
        'required' => true,
        'content' => 'Bạn thường suy ngẫm sâu sắc một mình trước khi chia sẻ quan điểm với người khác.',
        'options' => $likertOptions,
    ],
    [
        'id' => '7f91e9bc-0e46-407b-0004-81dda1c11c5e',
        'code' => 'mbti_high_sn_s_011',
        'position' => 11,
        'dimension_code' => 'SN:S',
        'required' => true,
        'content' => 'Bạn tin tưởng vào những phương pháp học tập đã được kiểm chứng qua thực tế.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'fc2055ed-9197-4c9b-f35b-caaa63ff2945',
        'code' => 'mbti_high_sn_n_012',
        'position' => 12,
        'dimension_code' => 'SN:N',
        'required' => true,
        'content' => 'Bạn thích khám phá những ý tưởng theo cách khác với thường lệ.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'b9d973ce-84c0-4e6e-c2ab-320784ded854',
        'code' => 'mbti_high_tf_t_013',
        'position' => 13,
        'dimension_code' => 'TF:T',
        'required' => true,
        'content' => 'Bạn thích phân tích ưu và khuyết điểm dựa trên lý lẽ.',
        'options' => $likertOptions,
    ],
    [
        'id' => '53c7c1fb-cdcb-4441-2ec0-d24e900bc3e3',
        'code' => 'mbti_high_tf_f_014',
        'position' => 14,
        'dimension_code' => 'TF:F',
        'required' => true,
        'content' => 'Bạn quan tâm đến cảm xúc của bạn cùng lớp.',
        'options' => $likertOptions,
    ],
    [
        'id' => '2bd12a26-2284-45c6-b9e6-821a23517b12',
        'code' => 'mbti_high_jp_j_015',
        'position' => 15,
        'dimension_code' => 'JP:J',
        'required' => true,
        'content' => 'Bạn yên tâm khi bài tập dự án có mục tiêu và hạn chót hoàn thành rõ ràng.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'f3ccc878-10a0-457c-b66c-5b7e64b1b66c',
        'code' => 'mbti_high_jp_p_016',
        'position' => 16,
        'dimension_code' => 'JP:P',
        'required' => true,
        'content' => 'Bạn thích xử lý các việc phát sinh vào phút chót.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'b0d61ec7-b44b-48dd-09c0-902f9a4acfef',
        'code' => 'mbti_high_ei_e_017',
        'position' => 17,
        'dimension_code' => 'EI:E',
        'required' => true,
        'content' => 'Bạn thích tham gia các câu lạc bộ và mở rộng mạng lưới giao lưu học đường.',
        'options' => $likertOptions,
    ],
    [
        'id' => '88c220cf-43b6-4b38-29c3-ead49de16635',
        'code' => 'mbti_high_ei_i_018',
        'position' => 18,
        'dimension_code' => 'EI:I',
        'required' => true,
        'content' => 'Bạn chọn làm việc độc lập để có thể tập trung tối đa vào việc tự nghiên cứu.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'e28217e8-5fd4-4040-8aa8-4c26dfc49f0a',
        'code' => 'mbti_high_sn_s_019',
        'position' => 19,
        'dimension_code' => 'SN:S',
        'required' => true,
        'content' => 'Bạn chú ý đến các chi tiết cụ thể trong bài tập.',
        'options' => $likertOptions,
    ],
    [
        'id' => '8a5ca0f0-aa0f-45bb-e81e-eee67cd6918d',
        'code' => 'mbti_high_sn_n_020',
        'position' => 20,
        'dimension_code' => 'SN:N',
        'required' => true,
        'content' => 'Bạn thích nhìn nhận bức tranh tổng thể và xu hướng phát triển của vấn đề.',
        'options' => $likertOptions,
    ],
    [
        'id' => '30c375b4-3ad5-41fe-e975-f5cfa35c1668',
        'code' => 'mbti_high_tf_t_021',
        'position' => 21,
        'dimension_code' => 'TF:T',
        'required' => true,
        'content' => 'Bạn dựa vào các nguyên tắc công bằng và nhất quán khi giải quyết mâu thuẫn.',
        'options' => $likertOptions,
    ],
    [
        'id' => '43224ff4-e90c-4b88-1fa0-cbcd6781c7a0',
        'code' => 'mbti_high_tf_f_022',
        'position' => 22,
        'dimension_code' => 'TF:F',
        'required' => true,
        'content' => 'Bạn ưu tiên lắng nghe cảm xúc của bạn bè.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'd2f987c8-f147-4262-9132-99efbaaa2ee5',
        'code' => 'mbti_high_jp_j_023',
        'position' => 23,
        'dimension_code' => 'JP:J',
        'required' => true,
        'content' => 'Bạn thích sắp xếp đầu việc theo thứ tự ưu tiên.',
        'options' => $likertOptions,
    ],
    [
        'id' => '414cb5f3-aa3a-47ca-0ed3-65a80f887ffc',
        'code' => 'mbti_high_jp_p_024',
        'position' => 24,
        'dimension_code' => 'JP:P',
        'required' => true,
        'content' => 'Bạn thích giữ nhiều lựa chọn mở thay vì chốt ngay một phương án cố định.',
        'options' => $likertOptions,
    ],
    [
        'id' => '25e39a36-05dc-4e4f-7f23-e49d52917626',
        'code' => 'mbti_high_ei_e_025',
        'position' => 25,
        'dimension_code' => 'EI:E',
        'required' => true,
        'content' => 'Bạn thích trình bày ý tưởng trước tập thể.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'eaa4bd8f-2597-4df9-b628-e768a8227e00',
        'code' => 'mbti_high_ei_i_026',
        'position' => 26,
        'dimension_code' => 'EI:I',
        'required' => true,
        'content' => 'Bạn thích suy nghĩ một mình trước khi chia sẻ ý kiến.',
        'options' => $likertOptions,
    ],
    [
        'id' => '68b85755-a453-4f1c-8f27-30ef057433f5',
        'code' => 'mbti_high_sn_s_027',
        'position' => 27,
        'dimension_code' => 'SN:S',
        'required' => true,
        'content' => 'Bạn đánh giá cao các bài tập có thể áp dụng trực tiếp vào thực tế đời sống.',
        'options' => $likertOptions,
    ],
    [
        'id' => '23e62ed4-2a0e-436a-492f-4db59c899dd4',
        'code' => 'mbti_high_sn_n_028',
        'position' => 28,
        'dimension_code' => 'SN:N',
        'required' => true,
        'content' => 'Bạn thích suy ngẫm về những khái niệm trừu tượng và các mối liên hệ ngầm.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'ad808631-1e52-43f8-9860-30fadb0adae1',
        'code' => 'mbti_high_tf_t_029',
        'position' => 29,
        'dimension_code' => 'TF:T',
        'required' => true,
        'content' => 'Bạn coi trọng lập luận có căn cứ hơn cảm nhận nhất thời.',
        'options' => $likertOptions,
    ],
    [
        'id' => '81b07680-be7c-48e5-cf9e-2362e6a0c258',
        'code' => 'mbti_high_tf_f_030',
        'position' => 30,
        'dimension_code' => 'TF:F',
        'required' => true,
        'content' => 'Bạn quan tâm đến những băn khoăn của bạn bè.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'f9be04ac-12aa-497f-4c4a-1e385254e3ab',
        'code' => 'mbti_high_jp_j_031',
        'position' => 31,
        'dimension_code' => 'JP:J',
        'required' => true,
        'content' => 'Bạn thích chuẩn bị tài liệu và kế hoạch trước khi bắt đầu một dự án học tập.',
        'options' => $likertOptions,
    ],
    [
        'id' => '97e2ff5c-b89b-4936-2701-43aa81d24bd6',
        'code' => 'mbti_high_jp_p_032',
        'position' => 32,
        'dimension_code' => 'JP:P',
        'required' => true,
        'content' => 'Bạn sẵn sàng thay đổi phương pháp làm việc khi xuất hiện ý tưởng mới mẻ hơn.',
        'options' => $likertOptions,
    ],
];

return ['metadata' => $metadata, 'questions' => $questions];
