<?php

declare(strict_types=1);

/**
 * Multiple Intelligence assessment catalog - middle band.
 *
 * Framework:        multiple_intelligence (scoring version multiple-intelligence-1.0)
 * Education band:   middle - Middle (grades 6-9)
 * Question count:   32 (Option A, Question Count Decision Gate approved
 *                   2026-08-19T05:38:16Z by the Product Owner)
 * Reverse items:    2 of 4 reversed (50.0%) per dimension across 8 dimensions
 * Review state:     published - all content, educational, bias/safety, scoring,
 *                   Product Owner, DCR, and Codex review checkpoints recorded.
 *
 * Question IDs are opaque canonical UUIDs; stable identity lives in the
 * 'code' field (namespace multiple_intelligence_middle_*).
 */

$metadata = [
    'framework' => 'multiple_intelligence',
    'education_band' => 'middle',
    'scoring_version' => 'multiple-intelligence-1.0',
    'question_count' => 32,
    'stable_code_namespace' => 'multiple_intelligence_middle_',
    'review_state' => 'published',
    'review_events' => [
        ['checkpoint' => 'content_review', 'reviewer' => 'Codex lead reviewer', 'approved_at_utc' => '2026-08-20T05:05:10Z'],
        ['checkpoint' => 'educational_review', 'reviewer' => 'Codex lead reviewer', 'approved_at_utc' => '2026-08-20T05:05:10Z'],
        ['checkpoint' => 'bias_review', 'reviewer' => 'Codex lead reviewer', 'approved_at_utc' => '2026-08-20T05:05:10Z'],
        ['checkpoint' => 'scoring_review', 'reviewer' => 'Codex lead reviewer', 'approved_at_utc' => '2026-08-20T05:05:10Z'],
        ['checkpoint' => 'product_owner_approval', 'reviewer' => 'NCnguyenn', 'approved_at_utc' => '2026-08-20T05:05:10Z'],
        ['checkpoint' => 'codex_schema_review', 'reviewer' => 'Codex lead reviewer', 'approved_at_utc' => '2026-08-20T05:05:10Z'],
    ],
    'schema_hash' => '07a8af65d16454386b2f7b9232550f9ea7697f07bd527b2f56f38f61564f9149',
    'advisory_disclaimer' => 'Định hướng đa trí thông minh giúp chọn trải nghiệm học tập, không phải chỉ số năng lực hay chẩn đoán.',
];

$likertOptions = [
    ['value' => 1, 'label' => 'Hoàn toàn không đồng ý'],
    ['value' => 2, 'label' => 'Không đồng ý'],
    ['value' => 3, 'label' => 'Bình thường'],
    ['value' => 4, 'label' => 'Đồng ý'],
    ['value' => 5, 'label' => 'Hoàn toàn đồng ý'],
];

$questions = [
    [
        'id' => 'bcacf1df-300b-4916-a83a-4d471525afa1',
        'code' => 'multiple_intelligence_middle_ling_001',
        'position' => 1,
        'dimension_code' => 'LING:+',
        'required' => true,
        'content' => 'Bạn thích diễn đạt trải nghiệm của mình bằng lời viết.',
        'options' => $likertOptions,
    ],
    [
        'id' => '4c0755ea-8e67-4f5c-98bb-7d666b11f312',
        'code' => 'multiple_intelligence_middle_logi_002',
        'position' => 2,
        'dimension_code' => 'LOGI:+',
        'required' => true,
        'content' => 'Bạn thích tìm ra quy luật trong các câu đố toán học.',
        'options' => $likertOptions,
    ],
    [
        'id' => '4f1abd3e-c1dc-4aa6-b777-cf052af7c0ad',
        'code' => 'multiple_intelligence_middle_spat_003',
        'position' => 3,
        'dimension_code' => 'SPAT:+',
        'required' => true,
        'content' => 'Bạn dễ dàng nhớ đường đi đến những nơi đã từng tới.',
        'options' => $likertOptions,
    ],
    [
        'id' => '0df127ae-00bb-4df3-8cae-e1868ad2db3b',
        'code' => 'multiple_intelligence_middle_body_004',
        'position' => 4,
        'dimension_code' => 'BODY:+',
        'required' => true,
        'content' => 'Bạn thích học kỹ năng mới qua thao tác trực tiếp.',
        'options' => $likertOptions,
    ],
    [
        'id' => '480201f4-94ad-445f-bec8-4abc09636e84',
        'code' => 'multiple_intelligence_middle_music_005',
        'position' => 5,
        'dimension_code' => 'MUSIC:+',
        'required' => true,
        'content' => 'Bạn dễ dàng nhận ra giai điệu quen thuộc của một bài hát.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'a1317c49-6c0a-4865-98ff-91a5d724d062',
        'code' => 'multiple_intelligence_middle_inter_006',
        'position' => 6,
        'dimension_code' => 'INTER:+',
        'required' => true,
        'content' => 'Bạn thích bắt chuyện với bạn mới trong lớp.',
        'options' => $likertOptions,
    ],
    [
        'id' => '541d7871-986a-4248-a2fc-99f0ef7f267b',
        'code' => 'multiple_intelligence_middle_intra_007',
        'position' => 7,
        'dimension_code' => 'INTRA:+',
        'required' => true,
        'content' => 'Bạn tự nhận biết rõ điểm mạnh và sở thích của bản thân.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'df8ff542-59f7-450a-8214-2b5f96fc4a7e',
        'code' => 'multiple_intelligence_middle_nat_008',
        'position' => 8,
        'dimension_code' => 'NAT:+',
        'required' => true,
        'content' => 'Bạn thích quan sát các loài cây cối và vật nuôi xung quanh.',
        'options' => $likertOptions,
    ],
    [
        'id' => '3378af47-7072-4c62-bdf6-1f76c8e5f635',
        'code' => 'multiple_intelligence_middle_ling_009',
        'position' => 9,
        'dimension_code' => 'LING:-',
        'required' => true,
        'content' => 'Bạn thấy chán khi phải đọc những đoạn văn bản dài.',
        'options' => $likertOptions,
    ],
    [
        'id' => '33bef3b8-3a23-4c95-a0f7-dcc71acbad60',
        'code' => 'multiple_intelligence_middle_logi_010',
        'position' => 10,
        'dimension_code' => 'LOGI:-',
        'required' => true,
        'content' => 'Bạn ngại giải các bài toán có nhiều bước suy luận.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'fd9a2826-57fd-4143-8e87-719b3316e505',
        'code' => 'multiple_intelligence_middle_spat_011',
        'position' => 11,
        'dimension_code' => 'SPAT:-',
        'required' => true,
        'content' => 'Bạn khó hình dung các khối hình học trong không gian.',
        'options' => $likertOptions,
    ],
    [
        'id' => '8117801d-1d68-4ae1-abfc-dd7a1309daa8',
        'code' => 'multiple_intelligence_middle_body_012',
        'position' => 12,
        'dimension_code' => 'BODY:-',
        'required' => true,
        'content' => 'Bạn khó học một thao tác mới cần phối hợp tay và mắt.',
        'options' => $likertOptions,
    ],
    [
        'id' => '09d4af5c-e58d-4106-8344-5a622f226355',
        'code' => 'multiple_intelligence_middle_music_013',
        'position' => 13,
        'dimension_code' => 'MUSIC:-',
        'required' => true,
        'content' => 'Bạn ít khi để ý đến tiết tấu hay nhạc điệu xung quanh.',
        'options' => $likertOptions,
    ],
    [
        'id' => '0a0a8bb9-8019-4bf3-bcb1-1bf156cc202e',
        'code' => 'multiple_intelligence_middle_inter_014',
        'position' => 14,
        'dimension_code' => 'INTER:-',
        'required' => true,
        'content' => 'Bạn ngại bắt chuyện với người khác khi làm việc nhóm.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'd460a462-0009-419f-a4c3-7be369057931',
        'code' => 'multiple_intelligence_middle_intra_015',
        'position' => 15,
        'dimension_code' => 'INTRA:-',
        'required' => true,
        'content' => 'Bạn ít khi dành thời gian suy nghĩ về cảm xúc của mình.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'fc3baf79-f4f8-46c5-9edc-e1167054162b',
        'code' => 'multiple_intelligence_middle_nat_016',
        'position' => 16,
        'dimension_code' => 'NAT:-',
        'required' => true,
        'content' => 'Bạn ít quan tâm đến việc chăm sóc cây cối trong vườn.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'c2dcbdb0-9049-4733-813d-1b10f99dc4f6',
        'code' => 'multiple_intelligence_middle_ling_017',
        'position' => 17,
        'dimension_code' => 'LING:+',
        'required' => true,
        'content' => 'Bạn thích dùng từ ngữ phong phú khi kể lại câu chuyện.',
        'options' => $likertOptions,
    ],
    [
        'id' => '887303eb-43f7-430a-b094-a7c3d3b4c5b0',
        'code' => 'multiple_intelligence_middle_logi_018',
        'position' => 18,
        'dimension_code' => 'LOGI:+',
        'required' => true,
        'content' => 'Bạn thích sắp xếp mọi thứ theo thứ tự logic rõ ràng.',
        'options' => $likertOptions,
    ],
    [
        'id' => '3d2f3875-4d9a-436e-b820-c8353dcb6929',
        'code' => 'multiple_intelligence_middle_spat_019',
        'position' => 19,
        'dimension_code' => 'SPAT:+',
        'required' => true,
        'content' => 'Bạn dễ hình dung cách sắp xếp các phần trên một trang giấy.',
        'options' => $likertOptions,
    ],
    [
        'id' => '2c1bfbd3-d528-4f8a-b35d-a02d01b36fce',
        'code' => 'multiple_intelligence_middle_body_020',
        'position' => 20,
        'dimension_code' => 'BODY:+',
        'required' => true,
        'content' => 'Bạn thích học kỹ năng mới bằng cách tự thao tác.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'c7615833-0d3b-46d1-a046-bc8431797f16',
        'code' => 'multiple_intelligence_middle_music_021',
        'position' => 21,
        'dimension_code' => 'MUSIC:+',
        'required' => true,
        'content' => 'Bạn thường nhận ra nhịp điệu của một bài nhạc.',
        'options' => $likertOptions,
    ],
    [
        'id' => '32778957-448a-4129-8661-44a8007bcbe2',
        'code' => 'multiple_intelligence_middle_inter_022',
        'position' => 22,
        'dimension_code' => 'INTER:+',
        'required' => true,
        'content' => 'Bạn nhanh chóng nhận ra khi bạn bè cùng lớp đang buồn.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'd667a83c-1ccd-4645-83fc-76a1baeecbb8',
        'code' => 'multiple_intelligence_middle_intra_023',
        'position' => 23,
        'dimension_code' => 'INTRA:+',
        'required' => true,
        'content' => 'Bạn thích tự đặt ra mục tiêu học tập cho riêng mình.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'da533fff-1334-4825-8a2b-4160114408da',
        'code' => 'multiple_intelligence_middle_nat_024',
        'position' => 24,
        'dimension_code' => 'NAT:+',
        'required' => true,
        'content' => 'Bạn thích tìm hiểu đời sống của các loài động vật.',
        'options' => $likertOptions,
    ],
    [
        'id' => '8470aa12-5fc3-40ed-b449-38c91914c5a2',
        'code' => 'multiple_intelligence_middle_ling_025',
        'position' => 25,
        'dimension_code' => 'LING:-',
        'required' => true,
        'content' => 'Bạn thấy khó khăn khi phải diễn đạt ý nghĩ thành lời văn.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'ceb5494b-de8a-4bfc-b32d-dda4e5c611af',
        'code' => 'multiple_intelligence_middle_logi_026',
        'position' => 26,
        'dimension_code' => 'LOGI:-',
        'required' => true,
        'content' => 'Bạn ít khi quan tâm đến các con số hay biểu đồ thống kê.',
        'options' => $likertOptions,
    ],
    [
        'id' => '3ff49527-df80-4cec-ad72-a8797d0e4ec5',
        'code' => 'multiple_intelligence_middle_spat_027',
        'position' => 27,
        'dimension_code' => 'SPAT:-',
        'required' => true,
        'content' => 'Bạn khó nhớ phương hướng khi đến một nơi xa lạ.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'bfe323da-37da-4372-bf0f-396c256a15c2',
        'code' => 'multiple_intelligence_middle_body_028',
        'position' => 28,
        'dimension_code' => 'BODY:-',
        'required' => true,
        'content' => 'Bạn khó phối hợp các động tác khi học một kỹ năng mới.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'b446b926-1773-4e45-96d3-8fa2bab4842c',
        'code' => 'multiple_intelligence_middle_music_029',
        'position' => 29,
        'dimension_code' => 'MUSIC:-',
        'required' => true,
        'content' => 'Bạn khó phân biệt sự khác nhau giữa các nốt nhạc.',
        'options' => $likertOptions,
    ],
    [
        'id' => '6f48de11-fdc6-4219-9876-eb10e2720dda',
        'code' => 'multiple_intelligence_middle_inter_030',
        'position' => 30,
        'dimension_code' => 'INTER:-',
        'required' => true,
        'content' => 'Bạn khó nhận ra cảm xúc người khác khi làm việc nhóm.',
        'options' => $likertOptions,
    ],
    [
        'id' => '137707fd-700c-4e64-a54c-363d810a0cda',
        'code' => 'multiple_intelligence_middle_intra_031',
        'position' => 31,
        'dimension_code' => 'INTRA:-',
        'required' => true,
        'content' => 'Bạn khó gọi tên cảm xúc của mình.',
        'options' => $likertOptions,
    ],
    [
        'id' => '89d8e0bf-27d0-4917-ae4a-e33bc3dd0365',
        'code' => 'multiple_intelligence_middle_nat_032',
        'position' => 32,
        'dimension_code' => 'NAT:-',
        'required' => true,
        'content' => 'Bạn ít hứng thú quan sát những thay đổi của thiên nhiên.',
        'options' => $likertOptions,
    ],
];

return ['metadata' => $metadata, 'questions' => $questions];
