<?php

declare(strict_types=1);

/**
 * Multiple Intelligence assessment catalog - high band.
 *
 * Framework:        multiple_intelligence (scoring version multiple-intelligence-1.0)
 * Education band:   high - High (grades 10-12)
 * Question count:   32 (Option A, Question Count Decision Gate approved
 *                   2026-08-19T05:38:16Z by the Product Owner)
 * Reverse items:    2 of 4 reversed (50.0%) per dimension across 8 dimensions
 * Review state:     published - all content, educational, bias/safety, scoring,
 *                   Product Owner, DCR, and Codex review checkpoints recorded.
 *
 * Question IDs are opaque canonical UUIDs; stable identity lives in the
 * 'code' field (namespace multiple_intelligence_high_*).
 */

$metadata = [
    'framework' => 'multiple_intelligence',
    'education_band' => 'high',
    'scoring_version' => 'multiple-intelligence-1.0',
    'question_count' => 32,
    'stable_code_namespace' => 'multiple_intelligence_high_',
    'review_state' => 'published',
    'review_events' => [
        ['checkpoint' => 'content_review', 'reviewer' => 'Codex lead reviewer', 'approved_at_utc' => '2026-08-20T05:05:10Z'],
        ['checkpoint' => 'educational_review', 'reviewer' => 'Codex lead reviewer', 'approved_at_utc' => '2026-08-20T05:05:10Z'],
        ['checkpoint' => 'bias_review', 'reviewer' => 'Codex lead reviewer', 'approved_at_utc' => '2026-08-20T05:05:10Z'],
        ['checkpoint' => 'scoring_review', 'reviewer' => 'Codex lead reviewer', 'approved_at_utc' => '2026-08-20T05:05:10Z'],
        ['checkpoint' => 'product_owner_approval', 'reviewer' => 'NCnguyenn', 'approved_at_utc' => '2026-08-20T05:05:10Z'],
        ['checkpoint' => 'codex_schema_review', 'reviewer' => 'Codex lead reviewer', 'approved_at_utc' => '2026-08-20T05:05:10Z'],
    ],
    'schema_hash' => '52591b809ef0dd03ceef261d7a0b2a0a64689d0a818f5a66c055107762925591',
    'advisory_disclaimer' => 'Định hướng đa trí thông minh giúp chọn trải nghiệm học tập, không phải chỉ số năng lực hay chẩn đoán.',
];

$likertOptions = [
    ['value' => 1, 'label' => 'Hoàn toàn không đồng ý'],
    ['value' => 2, 'label' => 'Không đồng ý'],
    ['value' => 3, 'label' => 'Bình thường'],
    ['value' => 4, 'label' => 'Đồng ý'],
    ['value' => 5, 'label' => 'Hoàn toàn đồng ý'],
];

$questions = [
    [
        'id' => 'd3033283-f16b-4c6b-adda-7d6c61b9e919',
        'code' => 'multiple_intelligence_high_ling_001',
        'position' => 1,
        'dimension_code' => 'LING:+',
        'required' => true,
        'content' => 'Bạn thích viết bài nêu rõ quan điểm của mình.',
        'options' => $likertOptions,
    ],
    [
        'id' => '08eb36e5-27b7-4570-9507-787e75f6b792',
        'code' => 'multiple_intelligence_high_logi_002',
        'position' => 2,
        'dimension_code' => 'LOGI:+',
        'required' => true,
        'content' => 'Bạn thích tìm nguyên nhân của một hiện tượng.',
        'options' => $likertOptions,
    ],
    [
        'id' => '65d8afcb-1278-4a1e-a44e-2da08fcb0086',
        'code' => 'multiple_intelligence_high_spat_003',
        'position' => 3,
        'dimension_code' => 'SPAT:+',
        'required' => true,
        'content' => 'Bạn dễ hình dung một vật thể khi xoay nó trong đầu.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'c9d0309b-5860-4435-8d2d-a82b9b4d3681',
        'code' => 'multiple_intelligence_high_body_004',
        'position' => 4,
        'dimension_code' => 'BODY:+',
        'required' => true,
        'content' => 'Bạn dễ học thao tác cần phối hợp tay và mắt.',
        'options' => $likertOptions,
    ],
    [
        'id' => '6ac41cf9-4bfb-4389-a9ea-edb2005d971c',
        'code' => 'multiple_intelligence_high_music_005',
        'position' => 5,
        'dimension_code' => 'MUSIC:+',
        'required' => true,
        'content' => 'Bạn chú ý đến nhịp điệu và giai điệu của bản nhạc.',
        'options' => $likertOptions,
    ],
    [
        'id' => '6090c68c-980e-45ac-84da-b861ae9ae180',
        'code' => 'multiple_intelligence_high_inter_006',
        'position' => 6,
        'dimension_code' => 'INTER:+',
        'required' => true,
        'content' => 'Bạn dễ nhận ra cảm xúc của người khác khi trò chuyện.',
        'options' => $likertOptions,
    ],
    [
        'id' => '9cadd909-20f9-4948-be82-95fe1d59c20e',
        'code' => 'multiple_intelligence_high_intra_007',
        'position' => 7,
        'dimension_code' => 'INTRA:+',
        'required' => true,
        'content' => 'Bạn thường xuyên tự đánh giá quá trình học để điều chỉnh kế hoạch.',
        'options' => $likertOptions,
    ],
    [
        'id' => '3f7de511-12c4-43cf-b960-88ccc3e613cd',
        'code' => 'multiple_intelligence_high_nat_008',
        'position' => 8,
        'dimension_code' => 'NAT:+',
        'required' => true,
        'content' => 'Bạn thích tìm hiểu quan hệ giữa sinh vật và môi trường sống.',
        'options' => $likertOptions,
    ],
    [
        'id' => '5c1b0f52-93fc-4f16-907f-6bb43b888d2f',
        'code' => 'multiple_intelligence_high_ling_009',
        'position' => 9,
        'dimension_code' => 'LING:-',
        'required' => true,
        'content' => 'Bạn ngại đọc những bài viết dài.',
        'options' => $likertOptions,
    ],
    [
        'id' => '566b9b3e-57b7-4ad5-b4f4-811071e64a60',
        'code' => 'multiple_intelligence_high_logi_010',
        'position' => 10,
        'dimension_code' => 'LOGI:-',
        'required' => true,
        'content' => 'Bạn khó nhận ra xu hướng trong một biểu đồ.',
        'options' => $likertOptions,
    ],
    [
        'id' => '79cac6c9-7f14-4eba-b973-1de91153c8cf',
        'code' => 'multiple_intelligence_high_spat_011',
        'position' => 11,
        'dimension_code' => 'SPAT:-',
        'required' => true,
        'content' => 'Bạn khó hình dung cách sắp xếp hình ảnh trên một trang trình chiếu.',
        'options' => $likertOptions,
    ],
    [
        'id' => '6fdd12e1-06c2-403f-b7b8-b0cafafb0e3a',
        'code' => 'multiple_intelligence_high_body_012',
        'position' => 12,
        'dimension_code' => 'BODY:-',
        'required' => true,
        'content' => 'Bạn khó thực hiện một chuỗi động tác theo hướng dẫn.',
        'options' => $likertOptions,
    ],
    [
        'id' => '856a0150-d2f7-4ada-b975-7e0e9015a260',
        'code' => 'multiple_intelligence_high_music_013',
        'position' => 13,
        'dimension_code' => 'MUSIC:-',
        'required' => true,
        'content' => 'Bạn ít khi để ý đến nhịp điệu trong các bài hát.',
        'options' => $likertOptions,
    ],
    [
        'id' => '2fc62c74-0295-456b-97f8-bf361f1da4d6',
        'code' => 'multiple_intelligence_high_inter_014',
        'position' => 14,
        'dimension_code' => 'INTER:-',
        'required' => true,
        'content' => 'Bạn khó nhận ra cảm xúc của người khác khi giao tiếp.',
        'options' => $likertOptions,
    ],
    [
        'id' => '56ea5b83-4210-4757-9de1-62503c9f3888',
        'code' => 'multiple_intelligence_high_intra_015',
        'position' => 15,
        'dimension_code' => 'INTRA:-',
        'required' => true,
        'content' => 'Bạn ít khi tự hỏi điều gì khiến mình hài lòng hoặc không hài lòng.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'd01618a4-00a6-4660-8e8a-4929417273d5',
        'code' => 'multiple_intelligence_high_nat_016',
        'position' => 16,
        'dimension_code' => 'NAT:-',
        'required' => true,
        'content' => 'Bạn ít hứng thú quan sát cách cây hoặc con vật thay đổi theo thời gian.',
        'options' => $likertOptions,
    ],
    [
        'id' => '1bb71d33-a312-4829-a264-1028481b2552',
        'code' => 'multiple_intelligence_high_ling_017',
        'position' => 17,
        'dimension_code' => 'LING:+',
        'required' => true,
        'content' => 'Bạn có thể chọn từ phù hợp để giải thích một ý khó.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'e87115f1-1e6b-4b31-92dc-8c51c7f9cd5e',
        'code' => 'multiple_intelligence_high_logi_018',
        'position' => 18,
        'dimension_code' => 'LOGI:+',
        'required' => true,
        'content' => 'Bạn thích tìm quy luật trong một chuỗi thông tin.',
        'options' => $likertOptions,
    ],
    [
        'id' => '6ed4c70c-43d0-403f-a071-7dbb0e45a7e0',
        'code' => 'multiple_intelligence_high_spat_019',
        'position' => 19,
        'dimension_code' => 'SPAT:+',
        'required' => true,
        'content' => 'Bạn thích dùng hình vẽ để sắp xếp ý tưởng.',
        'options' => $likertOptions,
    ],
    [
        'id' => '027c0e96-4b83-4e11-82f8-5de23d832331',
        'code' => 'multiple_intelligence_high_body_020',
        'position' => 20,
        'dimension_code' => 'BODY:+',
        'required' => true,
        'content' => 'Bạn thích tự làm thử khi học một kỹ năng mới.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'ba9dfc44-c1e3-4cc6-9700-34bd5b64c260',
        'code' => 'multiple_intelligence_high_music_021',
        'position' => 21,
        'dimension_code' => 'MUSIC:+',
        'required' => true,
        'content' => 'Bạn có khả năng nhận biết và phân biệt âm sắc của các loại nhạc cụ.',
        'options' => $likertOptions,
    ],
    [
        'id' => '32b369a6-5fa9-4e12-8764-c34d866296da',
        'code' => 'multiple_intelligence_high_inter_022',
        'position' => 22,
        'dimension_code' => 'INTER:+',
        'required' => true,
        'content' => 'Bạn thường nhận ra khi hai bạn đang không thoải mái với nhau.',
        'options' => $likertOptions,
    ],
    [
        'id' => '59394cc7-3cce-4828-af21-149367f69427',
        'code' => 'multiple_intelligence_high_intra_023',
        'position' => 23,
        'dimension_code' => 'INTRA:+',
        'required' => true,
        'content' => 'Bạn biết những giá trị nào quan trọng với mình.',
        'options' => $likertOptions,
    ],
    [
        'id' => '5ccefd08-1da8-48ea-8aee-5fd6a7b07894',
        'code' => 'multiple_intelligence_high_nat_024',
        'position' => 24,
        'dimension_code' => 'NAT:+',
        'required' => true,
        'content' => 'Bạn thích quan sát các sinh vật và môi trường sống của chúng.',
        'options' => $likertOptions,
    ],
    [
        'id' => '51171375-3260-4890-bb56-4edcf6c441c6',
        'code' => 'multiple_intelligence_high_ling_025',
        'position' => 25,
        'dimension_code' => 'LING:-',
        'required' => true,
        'content' => 'Bạn khó diễn đạt một ý phức tạp bằng lời.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'e30655bf-524a-414b-ae12-c57c818ed441',
        'code' => 'multiple_intelligence_high_logi_026',
        'position' => 26,
        'dimension_code' => 'LOGI:-',
        'required' => true,
        'content' => 'Bạn ít khi tự tìm kiếm nguyên nhân logic đằng sau các hiện tượng.',
        'options' => $likertOptions,
    ],
    [
        'id' => '992fcd36-f68b-4849-96a0-8c9b557caf84',
        'code' => 'multiple_intelligence_high_spat_027',
        'position' => 27,
        'dimension_code' => 'SPAT:-',
        'required' => true,
        'content' => 'Bạn dễ bị mất phương hướng khi di chuyển trong tòa nhà rộng lớn.',
        'options' => $likertOptions,
    ],
    [
        'id' => '245a3888-a75d-4940-85d8-7a537b25a8a5',
        'code' => 'multiple_intelligence_high_body_028',
        'position' => 28,
        'dimension_code' => 'BODY:-',
        'required' => true,
        'content' => 'Bạn khó duy trì sự phối hợp khi thực hiện một chuỗi động tác.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'd7a05107-34f2-4d0b-a0fe-c6ba48a648dd',
        'code' => 'multiple_intelligence_high_music_029',
        'position' => 29,
        'dimension_code' => 'MUSIC:-',
        'required' => true,
        'content' => 'Bạn khó hòa nhịp theo một giai điệu mới.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'a6dea801-7eec-4e91-a9d5-eb8909327e22',
        'code' => 'multiple_intelligence_high_inter_030',
        'position' => 30,
        'dimension_code' => 'INTER:-',
        'required' => true,
        'content' => 'Bạn khó hiểu điều người khác mong đợi khi phối hợp.',
        'options' => $likertOptions,
    ],
    [
        'id' => '24d5a6c7-5e84-4cac-8c46-ce92fce11c6a',
        'code' => 'multiple_intelligence_high_intra_031',
        'position' => 31,
        'dimension_code' => 'INTRA:-',
        'required' => true,
        'content' => 'Bạn khó tự đặt mục tiêu cho việc học của mình.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'fecfe6f8-a96b-4d5c-9465-67cf388dc1c6',
        'code' => 'multiple_intelligence_high_nat_032',
        'position' => 32,
        'dimension_code' => 'NAT:-',
        'required' => true,
        'content' => 'Bạn ít hứng thú quan sát những thay đổi trong tự nhiên.',
        'options' => $likertOptions,
    ],
];

return ['metadata' => $metadata, 'questions' => $questions];
