<?php

declare(strict_types=1);

/**
 * Multiple Intelligence assessment catalog - college band.
 *
 * Framework:        multiple_intelligence (scoring version multiple-intelligence-1.0)
 * Education band:   college - College (vocational/university students)
 * Question count:   32 (Option A, Question Count Decision Gate approved
 *                   2026-08-19T05:38:16Z by the Product Owner)
 * Reverse items:    2 of 4 reversed (50.0%) per dimension across 8 dimensions
 * Review state:     published - all content, educational, bias/safety, scoring,
 *                   Product Owner, DCR, and Codex review checkpoints recorded.
 *
 * Question IDs are opaque canonical UUIDs; stable identity lives in the
 * 'code' field (namespace multiple_intelligence_college_*).
 */

$metadata = [
    'framework' => 'multiple_intelligence',
    'education_band' => 'college',
    'scoring_version' => 'multiple-intelligence-1.0',
    'question_count' => 32,
    'stable_code_namespace' => 'multiple_intelligence_college_',
    'review_state' => 'published',
    'review_events' => [
        ['checkpoint' => 'content_review', 'reviewer' => 'Codex lead reviewer', 'approved_at_utc' => '2026-08-20T05:05:10Z'],
        ['checkpoint' => 'educational_review', 'reviewer' => 'Codex lead reviewer', 'approved_at_utc' => '2026-08-20T05:05:10Z'],
        ['checkpoint' => 'bias_review', 'reviewer' => 'Codex lead reviewer', 'approved_at_utc' => '2026-08-20T05:05:10Z'],
        ['checkpoint' => 'scoring_review', 'reviewer' => 'Codex lead reviewer', 'approved_at_utc' => '2026-08-20T05:05:10Z'],
        ['checkpoint' => 'product_owner_approval', 'reviewer' => 'NCnguyenn', 'approved_at_utc' => '2026-08-20T05:05:10Z'],
        ['checkpoint' => 'codex_schema_review', 'reviewer' => 'Codex lead reviewer', 'approved_at_utc' => '2026-08-20T05:05:10Z'],
    ],
    'schema_hash' => '16a672944020511848e1b486bd27bdb5712ee162cf84838493f414cf0b61f210',
    'advisory_disclaimer' => 'Định hướng đa trí thông minh giúp chọn trải nghiệm học tập, không phải chỉ số năng lực hay chẩn đoán.',
];

$likertOptions = [
    ['value' => 1, 'label' => 'Hoàn toàn không đồng ý'],
    ['value' => 2, 'label' => 'Không đồng ý'],
    ['value' => 3, 'label' => 'Bình thường'],
    ['value' => 4, 'label' => 'Đồng ý'],
    ['value' => 5, 'label' => 'Hoàn toàn đồng ý'],
];

$questions = [
    [
        'id' => 'a30728ff-5109-47e0-adf9-c379c4421d47',
        'code' => 'multiple_intelligence_college_ling_001',
        'position' => 1,
        'dimension_code' => 'LING:+',
        'required' => true,
        'content' => 'Bạn thích diễn đạt ý chính của tài liệu bằng văn bản.',
        'options' => $likertOptions,
    ],
    [
        'id' => '9c1658af-011f-47ba-800e-e584fec87201',
        'code' => 'multiple_intelligence_college_logi_002',
        'position' => 2,
        'dimension_code' => 'LOGI:+',
        'required' => true,
        'content' => 'Bạn thích tìm cách biểu diễn một vấn đề bằng số liệu.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'c59b9c0a-ef53-4128-96d4-28b0188da808',
        'code' => 'multiple_intelligence_college_spat_003',
        'position' => 3,
        'dimension_code' => 'SPAT:+',
        'required' => true,
        'content' => 'Bạn dễ hình dung mối quan hệ giữa các phần của một hệ thống.',
        'options' => $likertOptions,
    ],
    [
        'id' => '0a1126c8-cc45-45ce-bdf7-602208af62c6',
        'code' => 'multiple_intelligence_college_body_004',
        'position' => 4,
        'dimension_code' => 'BODY:+',
        'required' => true,
        'content' => 'Bạn thích học kỹ năng qua thao tác thực hành.',
        'options' => $likertOptions,
    ],
    [
        'id' => '61e330b4-9bd8-459f-a1fd-88545f06b438',
        'code' => 'multiple_intelligence_college_music_005',
        'position' => 5,
        'dimension_code' => 'MUSIC:+',
        'required' => true,
        'content' => 'Bạn dễ nhận ra sự thay đổi về nhịp điệu trong một bản nhạc.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'a9ea8f00-3782-4363-b5ba-624822962151',
        'code' => 'multiple_intelligence_college_inter_006',
        'position' => 6,
        'dimension_code' => 'INTER:+',
        'required' => true,
        'content' => 'Bạn dễ nhận ra cảm xúc của người khác trong thảo luận.',
        'options' => $likertOptions,
    ],
    [
        'id' => '07b63846-cfef-4222-9f67-0d6b9a5e6203',
        'code' => 'multiple_intelligence_college_intra_007',
        'position' => 7,
        'dimension_code' => 'INTRA:+',
        'required' => true,
        'content' => 'Bạn thường xem lại mục tiêu của mình để điều chỉnh cách học.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'a4db1b60-f558-477e-b62e-771ea24240cf',
        'code' => 'multiple_intelligence_college_nat_008',
        'position' => 8,
        'dimension_code' => 'NAT:+',
        'required' => true,
        'content' => 'Bạn thích tìm hiểu sự tương tác giữa sinh vật và môi trường.',
        'options' => $likertOptions,
    ],
    [
        'id' => '8089f9aa-6cd8-4e6b-885e-a6ec9e36cf68',
        'code' => 'multiple_intelligence_college_ling_009',
        'position' => 9,
        'dimension_code' => 'LING:-',
        'required' => true,
        'content' => 'Bạn ngại đọc các bài viết dài.',
        'options' => $likertOptions,
    ],
    [
        'id' => '46b9b050-bded-4630-b72f-a665877ffc52',
        'code' => 'multiple_intelligence_college_logi_010',
        'position' => 10,
        'dimension_code' => 'LOGI:-',
        'required' => true,
        'content' => 'Bạn khó theo dõi một lập luận có nhiều bước.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'f58ab9da-adcf-4c87-a37f-34fe2a5b2eeb',
        'code' => 'multiple_intelligence_college_spat_011',
        'position' => 11,
        'dimension_code' => 'SPAT:-',
        'required' => true,
        'content' => 'Bạn khó hình dung cấu trúc của một vật thể trong không gian.',
        'options' => $likertOptions,
    ],
    [
        'id' => '2dd21a3e-b45d-4f23-b612-2bc81b50c6b4',
        'code' => 'multiple_intelligence_college_body_012',
        'position' => 12,
        'dimension_code' => 'BODY:-',
        'required' => true,
        'content' => 'Bạn khó học một kỹ năng thực hành qua việc tự thao tác.',
        'options' => $likertOptions,
    ],
    [
        'id' => '93cc1c73-2e19-497c-ad1f-a3bf8ba1e9b0',
        'code' => 'multiple_intelligence_college_music_013',
        'position' => 13,
        'dimension_code' => 'MUSIC:-',
        'required' => true,
        'content' => 'Bạn ít khi để ý đến nhịp điệu trong âm nhạc.',
        'options' => $likertOptions,
    ],
    [
        'id' => '15951caa-72cb-4be5-adb7-148508cd3281',
        'code' => 'multiple_intelligence_college_inter_014',
        'position' => 14,
        'dimension_code' => 'INTER:-',
        'required' => true,
        'content' => 'Bạn khó trao đổi khi ý kiến của mình khác với người khác.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'b9b5c02d-0b9a-4ef8-91d0-f25b4c235b29',
        'code' => 'multiple_intelligence_college_intra_015',
        'position' => 15,
        'dimension_code' => 'INTRA:-',
        'required' => true,
        'content' => 'Bạn ít dành thời gian suy nghĩ về điều mình coi trọng.',
        'options' => $likertOptions,
    ],
    [
        'id' => '03095d4b-7c86-4944-8a35-33e9c8d52b59',
        'code' => 'multiple_intelligence_college_nat_016',
        'position' => 16,
        'dimension_code' => 'NAT:-',
        'required' => true,
        'content' => 'Bạn ít hứng thú quan sát sinh vật trong môi trường tự nhiên.',
        'options' => $likertOptions,
    ],
    [
        'id' => '86dfac77-4052-4090-9522-a009c941851a',
        'code' => 'multiple_intelligence_college_ling_017',
        'position' => 17,
        'dimension_code' => 'LING:+',
        'required' => true,
        'content' => 'Bạn thích dùng từ ngữ chính xác để giải thích một ý tưởng.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'c0e2f0b9-f73c-4bca-a47b-7bb246816253',
        'code' => 'multiple_intelligence_college_logi_018',
        'position' => 18,
        'dimension_code' => 'LOGI:+',
        'required' => true,
        'content' => 'Bạn hứng thú với việc kiểm chứng giả thuyết bằng các phương pháp suy luận có cấu trúc.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'eb5dbbc7-c5d2-4881-8179-e754dbec7a95',
        'code' => 'multiple_intelligence_college_spat_019',
        'position' => 19,
        'dimension_code' => 'SPAT:+',
        'required' => true,
        'content' => 'Bạn dễ hiểu thông tin được trình bày bằng biểu đồ.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'e122d36c-7d90-455a-a35a-9d2a151fa98a',
        'code' => 'multiple_intelligence_college_body_020',
        'position' => 20,
        'dimension_code' => 'BODY:+',
        'required' => true,
        'content' => 'Bạn thích luyện một thao tác cho đến khi thành thạo.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'c3c3ce31-ab48-4dcc-bd14-8658fcf21a6c',
        'code' => 'multiple_intelligence_college_music_021',
        'position' => 21,
        'dimension_code' => 'MUSIC:+',
        'required' => true,
        'content' => 'Bạn dễ nhận ra sự thay đổi về cao độ trong một giai điệu.',
        'options' => $likertOptions,
    ],
    [
        'id' => '9ee45646-8120-4bcc-878f-c7e63b9c8ffe',
        'code' => 'multiple_intelligence_college_inter_022',
        'position' => 22,
        'dimension_code' => 'INTER:+',
        'required' => true,
        'content' => 'Bạn chủ động trao đổi để cùng hoàn thành việc học.',
        'options' => $likertOptions,
    ],
    [
        'id' => '50aa507f-46be-4a14-b3a8-c8e333b66394',
        'code' => 'multiple_intelligence_college_intra_023',
        'position' => 23,
        'dimension_code' => 'INTRA:+',
        'required' => true,
        'content' => 'Bạn chủ động sắp xếp thời gian tự học của mình.',
        'options' => $likertOptions,
    ],
    [
        'id' => '507b3509-2433-4d6f-8bf9-26cb7b7f4791',
        'code' => 'multiple_intelligence_college_nat_024',
        'position' => 24,
        'dimension_code' => 'NAT:+',
        'required' => true,
        'content' => 'Bạn chú ý đến những thay đổi theo mùa trong môi trường xung quanh.',
        'options' => $likertOptions,
    ],
    [
        'id' => 'e38e4bdc-70fb-4ec6-84fe-68b4981684ff',
        'code' => 'multiple_intelligence_college_ling_025',
        'position' => 25,
        'dimension_code' => 'LING:-',
        'required' => true,
        'content' => 'Bạn gặp khó khăn khi tóm tắt một văn bản dài.',
        'options' => $likertOptions,
    ],
    [
        'id' => '078522f4-7a3b-4d11-a9d6-aadc73f9bcac',
        'code' => 'multiple_intelligence_college_logi_026',
        'position' => 26,
        'dimension_code' => 'LOGI:-',
        'required' => true,
        'content' => 'Bạn ít khi tự xây dựng quy trình phân tích logic trước khi tiếp cận một vấn đề mới.',
        'options' => $likertOptions,
    ],
    [
        'id' => '719633d5-7e15-4f73-a704-6301eeab8cf8',
        'code' => 'multiple_intelligence_college_spat_027',
        'position' => 27,
        'dimension_code' => 'SPAT:-',
        'required' => true,
        'content' => 'Bạn khó hình dung cách sắp xếp các thành phần trên một giao diện.',
        'options' => $likertOptions,
    ],
    [
        'id' => '689650e1-a303-410d-b78b-901c5d563b7e',
        'code' => 'multiple_intelligence_college_body_028',
        'position' => 28,
        'dimension_code' => 'BODY:-',
        'required' => true,
        'content' => 'Bạn khó phối hợp động tác khi thực hiện công việc thực hành.',
        'options' => $likertOptions,
    ],
    [
        'id' => '7cd037bf-7dc2-4814-bd39-a26952d91969',
        'code' => 'multiple_intelligence_college_music_029',
        'position' => 29,
        'dimension_code' => 'MUSIC:-',
        'required' => true,
        'content' => 'Bạn khó nhận ra sự khác nhau giữa hai giai điệu.',
        'options' => $likertOptions,
    ],
    [
        'id' => '269c2973-cfdc-4937-b0ae-1ae83386f297',
        'code' => 'multiple_intelligence_college_inter_030',
        'position' => 30,
        'dimension_code' => 'INTER:-',
        'required' => true,
        'content' => 'Bạn khó nhận ra nhu cầu của người khác trong dự án chung.',
        'options' => $likertOptions,
    ],
    [
        'id' => '05bf856a-0bab-4769-869e-63ed1da94cc3',
        'code' => 'multiple_intelligence_college_intra_031',
        'position' => 31,
        'dimension_code' => 'INTRA:-',
        'required' => true,
        'content' => 'Bạn khó nhận ra khi mình cần nghỉ ngơi trong thời gian học tập căng thẳng.',
        'options' => $likertOptions,
    ],
    [
        'id' => '456ccbd3-4db7-4baa-9713-fdae4bc1177a',
        'code' => 'multiple_intelligence_college_nat_032',
        'position' => 32,
        'dimension_code' => 'NAT:-',
        'required' => true,
        'content' => 'Bạn ít hứng thú quan sát các loài sinh vật quanh mình.',
        'options' => $likertOptions,
    ],
];

return ['metadata' => $metadata, 'questions' => $questions];
