<?php
declare(strict_types=1);
require dirname(__DIR__).'/bin/bootstrap.php';
use TalentHub\Auth\Session\SessionManager;
use TalentHub\Http\ApiException;
use TalentHub\Modules\Student\Service\PortfolioAccess;
$pdo=new PDO('sqlite::memory:',null,null,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);
$pdo->exec("CREATE TABLE users(id TEXT,roleId TEXT,status TEXT); CREATE TABLE roles(id TEXT,code TEXT); CREATE TABLE student_profiles(id TEXT,userId TEXT); CREATE TABLE teacher_profiles(id TEXT,userId TEXT);
INSERT INTO roles VALUES ('r1','student'),('r2','teacher'); INSERT INTO users VALUES ('u1','r1','active'),('u2','r2','active'),('u3','r1','disabled'); INSERT INTO student_profiles VALUES ('s1','u1'); INSERT INTO teacher_profiles VALUES ('t1','u2');");
$session=new SessionManager([]);
function denied(callable $fn,int $status): void { try { $fn(); } catch(ApiException $e) { if($e->status===$status) return; throw $e; } throw new RuntimeException('Expected denial '.$status); }
$_SESSION=[];
denied(fn()=>PortfolioAccess::identity($pdo,$session,'student'),401);
$_SESSION=['user'=>['id'=>'u1','role'=>'student']];
if(PortfolioAccess::identity($pdo,$session,'student')['studentId']!=='s1') throw new RuntimeException('Identity must come from DB');
denied(fn()=>PortfolioAccess::identity($pdo,$session,'teacher'),403);
$_SESSION=['user'=>['id'=>'u1','role'=>'teacher']];
denied(fn()=>PortfolioAccess::identity($pdo,$session,'teacher'),403);
$_SESSION=['user'=>['id'=>'u3','role'=>'student']];
denied(fn()=>PortfolioAccess::identity($pdo,$session,'student'),403);
$_SESSION=['user'=>['id'=>'u2','role'=>'teacher']];
if(PortfolioAccess::identity($pdo,$session,'teacher')['userId']!=='u2') throw new RuntimeException('Teacher identity');
echo "[PASS] Portfolio identity: guest, wrong role, spoofed role, disabled and valid owners\n";
$token=$session->csrfToken();
denied(fn()=>$session->assertCsrf(null),403);
$session->assertCsrf($token);
echo "[PASS] Mutation CSRF token validation\n";
$_SESSION=['user'=>['id'=>'u1','role'=>'student'],'csrfToken'=>'token'];
$request=static fn(array $body,string $token='token')=>new \TalentHub\Http\Request('POST','/portfolio',['content-type'=>'application/json','x-csrf-token'=>$token],json_encode($body));
$handle=static fn($request)=>\TalentHub\Modules\Student\Service\PortfolioHttp::handle($pdo,$session,$request,'student');
denied(fn()=>$handle($request(['kind'=>'project','expectedVersion'=>0],'invalid')),403);
denied(fn()=>$handle($request(['kind'=>'project','expectedVersion'=>0,'studentId'=>'other-student'])),422);
denied(fn()=>$handle($request(['kind'=>'project','expectedVersion'=>0,'decision'=>'verified'])),422);
denied(fn()=>$handle($request(['kind'=>'project','expectedVersion'=>'0'])),422);
denied(fn()=>$handle($request(['kind'=>['project'],'expectedVersion'=>0])),422);
denied(fn()=>$handle($request(['kind'=>'project','expectedVersion'=>0,'hours'=>['bad'] ])),422);
echo "[PASS] HTTP rejects forged ownership/approval fields, bad versions/types and invalid CSRF before writes\n";
