<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/app/learner/data/bootstrap.php';
require_once dirname(__DIR__).'/app/learner/ai/bootstrap.php';
use TalentHub\Learner\Ai\Queue\DatabaseAiRefreshJobRepository;
use TalentHub\Learner\Ai\Queue\DatabaseAiDataOutboxRepository;
use TalentHub\Learner\Ai\Queue\AiDataOutbox;
use TalentHub\Learner\Ai\Queue\AiDataOutboxConsumer;
use TalentHub\Learner\Ai\Queue\AiRefreshDispatcher;
use TalentHub\Learner\Ai\Persistence\DatabaseAiCapabilityProfileRepository;
use TalentHub\Learner\Ai\Queue\TransactionalAiOutboxPublisher;
use TalentHub\Learner\Ai\Provider\DatabaseCircuitBreakerStore;
use TalentHub\Learner\Ai\Provider\CircuitBreaker;
function p34p(bool $ok,string $m):void{if(!$ok)throw new RuntimeException($m);}
$pdo=new PDO('sqlite::memory:');$pdo->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);
foreach(['006_create_ai_refresh_jobs.php','007_create_ai_data_outbox.php','009_create_ai_capability_profiles.php','010_create_ai_provider_health.php'] as $file){$migration=require dirname(__DIR__).'/Database/migrations/learner/'.$file;foreach($migration->migration->statements('sqlite') as $sql)$pdo->exec($sql);}
$clock=1000;$circuitStore=new DatabaseCircuitBreakerStore($pdo);$circuitA=new CircuitBreaker(2,10,static function()use(&$clock):int{return $clock;},$circuitStore,'gemini');$circuitB=new CircuitBreaker(2,10,static function()use(&$clock):int{return $clock;},$circuitStore,'gemini');$circuitA->recordFailure();$circuitA->recordFailure();p34p(!$circuitB->allow(),'circuit state is shared through database');$clock=1011;p34p($circuitA->allow()&&!$circuitB->allow(),'only one half-open probe is admitted');$circuitA->recordSuccess();p34p($circuitB->allow(),'successful probe closes shared circuit');
$pdo->exec('CREATE TABLE source_mutation (id TEXT PRIMARY KEY)');$pdo->beginTransaction();$pdo->exec("INSERT INTO source_mutation VALUES ('rolled-back')");TransactionalAiOutboxPublisher::publish($pdo,'profile','rolled-back',1,['s1'],'profile.updated');$pdo->rollBack();p34p((int)$pdo->query('SELECT COUNT(*) FROM learner_ai_data_outbox')->fetchColumn()===0,'source mutation and outbox roll back atomically');
$pdo->beginTransaction();$pdo->exec("INSERT INTO source_mutation VALUES ('committed')");TransactionalAiOutboxPublisher::publish($pdo,'profile','committed',1,['s1'],'profile.updated');$pdo->commit();p34p((int)$pdo->query('SELECT COUNT(*) FROM learner_ai_data_outbox')->fetchColumn()===1,'source mutation and outbox commit atomically');
$jobs=new DatabaseAiRefreshJobRepository($pdo);$a=$jobs->enqueue('s1',str_repeat('a',64),'roadmap');$jobs->enqueue('s1',str_repeat('a',64),'roadmap');p34p((int)$pdo->query('SELECT COUNT(*) FROM learner_ai_refresh_jobs')->fetchColumn()===1,'DB queue idempotent');p34p($jobs->claimNext('worker')?->jobKey===$a->jobKey,'DB queue claim');
$leased=$pdo->query("SELECT lease_token FROM learner_ai_refresh_jobs WHERE job_key='{$a->jobKey}'")->fetchColumn();$pdo->exec("UPDATE learner_ai_refresh_jobs SET lease_until='2000-01-01 00:00:00' WHERE job_key='{$a->jobKey}'");$reclaimed=$jobs->claimNext('worker-2');p34p($reclaimed!==null&&$reclaimed->leaseToken!==$leased,'expired lease is reclaimed with a new token');$jobs->complete($a->jobKey,(string)$leased);p34p($pdo->query("SELECT status FROM learner_ai_refresh_jobs WHERE job_key='{$a->jobKey}'")->fetchColumn()==='processing','expired worker cannot complete reclaimed job');$jobs->complete($a->jobKey,$reclaimed->leaseToken);
$leaseJob=$jobs->enqueue('s1',str_repeat('f',64),'roadmap');$leaseJob=$jobs->claimNext('lease-worker');p34p($leaseJob!==null&&$jobs->renewLease($leaseJob->jobKey,(string)$leaseJob->leaseToken,240),'active worker renews its lease');p34p($jobs->ownsLease($leaseJob->jobKey,(string)$leaseJob->leaseToken),'active lease token is validated');p34p(!$jobs->renewLease($leaseJob->jobKey,'stale-token',240),'stale token cannot renew lease');$jobs->complete($leaseJob->jobKey,$leaseJob->leaseToken);
$outbox=new DatabaseAiDataOutboxRepository($pdo);$outbox->append(AiDataOutbox::create('checkin','c1',1,['s1'],'checkin.confirmed',[]));$capabilityHashes=['roadmap'=>str_repeat('b',64),'recommendation'=>str_repeat('c',64),'profile_analysis'=>str_repeat('d',64)];$consumer=new AiDataOutboxConsumer($outbox,new AiRefreshDispatcher($jobs),static fn(string $id,string $capability):string=>$capabilityHashes[$capability],static fn(string $id):bool=>$id==='s1');p34p($consumer->consume()===2,'outbox consumed');foreach($capabilityHashes as $capability=>$hash)p34p((int)$pdo->query("SELECT COUNT(*) FROM learner_ai_refresh_jobs WHERE capability='{$capability}' AND snapshot_hash='{$hash}'")->fetchColumn()===1,"{$capability} queues its exact canonical input hash");
$profiles=new DatabaseAiCapabilityProfileRepository($pdo);$profile=['talent_map'=>[],'strengths'=>[['label'=>'logic']],'improvements'=>[],'potential_paths'=>[],'trend_signals'=>[],'evidence'=>[['source'=>'assessment']]];$profiles->publish('s1',$profile,str_repeat('c',64),'gemini-test','2026-08-27 00:00:00');$latest=$profiles->publish('s1',$profile,str_repeat('d',64),'gemini-test','2026-08-27 01:00:00');p34p((int)$latest['version_number']===2,'capability profile versioned');p34p((int)$pdo->query("SELECT COUNT(*) FROM learner_ai_capability_profiles WHERE superseded_at IS NOT NULL")->fetchColumn()===1,'previous profile superseded');
$same=$profiles->publish('s1',$profile,str_repeat('d',64),'gemini-test','2026-08-27 01:00:00');p34p((int)$same['version_number']===2,'same snapshot/model publish is idempotent');$late=$profiles->publish('s1',$profile,str_repeat('e',64),'gemini-test','2026-08-26 01:00:00');p34p((int)$late['version_number']===2,'late older job cannot supersede active profile');
$rolled=$profiles->rollback('s1',1,'2026-08-27 02:00:00');p34p((int)($rolled['version_number']??0)===1,'database capability profile rollback');
$afterRollback=$profiles->publish('s1',$profile,str_repeat('9',64),'gemini-test','2026-08-27 03:00:00');p34p((int)($afterRollback['version_number']??0)===3,'publish after rollback allocates max retained version plus one');
$profiles->markPending('s1',str_repeat('8',64),'profile-job');$pendingProfile=$profiles->latest('s1');p34p(($pendingProfile['status']??null)==='stale_model'&&($pendingProfile['refresh_job_id']??null)==='profile-job','profile pending freshness is persisted on last known good');$profiles->markFailed('s1','rate_limited','2026-08-27 04:00:00');$failedProfile=$profiles->latest('s1');p34p(($failedProfile['last_refresh_error']??null)==='rate_limited'&&($failedProfile['next_retry_at']??null)==='2026-08-27 04:00:00','profile refresh error and retry schedule are persisted');
$circuitStore->recordFailure('race-safe',2,2000);$raceState=$circuitStore->recordFailure('race-safe',2,2001);p34p($raceState['failures']===2&&$raceState['state']==='open','circuit failure increment and opening are atomic in the store');
echo "learner_ai_phase34_persistence_test: OK\n";
