<?php
declare(strict_types=1);

use TalentHub\Modules\School\Repository\SchoolAiAggregateRepository;
use TalentHub\Modules\School\Repository\DatabaseSchoolAiInsightRepository;
use TalentHub\Modules\School\Service\SchoolAiInsightService;

require_once dirname(__DIR__).'/src/Modules/School/Repository/SchoolAiAggregateRepository.php';
require_once dirname(__DIR__).'/src/Modules/School/Repository/DatabaseSchoolAiInsightRepository.php';
require_once dirname(__DIR__).'/src/Modules/School/Service/SchoolAiInsightService.php';
function school_ai_assert(bool $ok,string $message):void{if(!$ok){fwrite(STDERR,"Assertion failed: {$message}\n");exit(1);}}
$pdo=new PDO('sqlite::memory:');$pdo->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);
$pdo->exec('CREATE TABLE classes (id TEXT PRIMARY KEY,schoolId TEXT,name TEXT,gradeLevel INTEGER)');
$pdo->exec('CREATE TABLE student_profiles (id TEXT PRIMARY KEY,classId TEXT,studyStatus TEXT DEFAULT \'active\')');
$pdo->exec('CREATE TABLE privacy_consents (id TEXT,studentId TEXT,scope TEXT,isGranted INTEGER,revokedAt TEXT)');
$pdo->exec('CREATE TABLE learner_ai_consent_events (id TEXT,studentId TEXT,scope TEXT,action TEXT,occurredAt TEXT,requestId TEXT)');
$pdo->exec('CREATE TABLE learner_ai_capability_profiles (id TEXT,student_id TEXT,status TEXT,talent_map_json TEXT,trend_signals_json TEXT,evidence_json TEXT DEFAULT \'[]\',generated_at TEXT,superseded_at TEXT)');
$pdo->exec('CREATE TABLE school_ai_insights (id TEXT PRIMARY KEY,school_id TEXT,aggregate_hash TEXT,payload_json TEXT,model_version TEXT,generated_at TEXT,stale_since TEXT,UNIQUE(school_id,aggregate_hash,model_version))');
$pdo->exec("INSERT INTO classes VALUES ('a1','school-a','10A1',10),('a2','school-a','10A2',10),('b1','school-b','10B1',10)");
for($i=1;$i<=8;$i++){ $class=$i<=6?'a1':'a2';$student="student-a{$i}";$pdo->prepare('INSERT INTO student_profiles VALUES (?,?,?)')->execute([$student,$class,'active']);$talent=$i===1?'[{"field":"Kỹ thuật","score":61},{"field":"Chỉ một học sinh","score":100}]':'[{"field":"Kỹ thuật","score":'.(60+$i).'}]';$trend=$i===1?'[{"label":"Tư duy logic tăng"},{"label":"Xu hướng riêng lẻ"}]':'[{"label":"Tư duy logic tăng"}]';$pdo->prepare('INSERT INTO learner_ai_capability_profiles (id,student_id,status,talent_map_json,trend_signals_json,generated_at,superseded_at) VALUES (?,?,?,?,?,?,NULL)')->execute(["profile-a{$i}",$student,$i===2?'stale_model':'ready_model',$talent,$trend,'2026-08-27 00:00:00']);foreach(['assessment','skills','activity','evaluation'] as $scope){$pdo->prepare('INSERT INTO privacy_consents VALUES (?,?,?,?,?)')->execute(["grant-{$i}-{$scope}",$student,$scope,1,null]);} }
$eventId=1;foreach(range(1,8) as $i){foreach(['assessment','skills','activity','evaluation'] as $scope){$action=$i===6?'revoked':'granted';$pdo->prepare('INSERT INTO learner_ai_consent_events VALUES (?,?,?,?,?,?)')->execute(["event-".$eventId++,"student-a{$i}",$scope,$action,'2026-08-27 00:00:00',"request-{$i}-{$scope}"]);}}
$pdo->exec("INSERT INTO student_profiles VALUES ('student-a10','a1','active')");$pdo->exec("INSERT INTO learner_ai_capability_profiles (id,student_id,status,talent_map_json,trend_signals_json,generated_at,superseded_at) VALUES ('profile-a10','student-a10','pending','[{\"field\":\"Đang chờ\",\"score\":100}]','[{\"label\":\"Đang chờ\"}]','2026-08-27 00:00:00',NULL)");
$pdo->exec("INSERT INTO student_profiles VALUES ('student-a9','a1','active')");$pdo->exec("INSERT INTO learner_ai_capability_profiles (id,student_id,status,talent_map_json,trend_signals_json,generated_at,superseded_at) VALUES ('profile-a9','student-a9','ready_model','[{\"field\":\"Hết hạn\",\"score\":100}]','[{\"label\":\"Xu hướng hết hạn\"}]','2024-01-01 00:00:00',NULL)");
$pdo->exec("INSERT INTO student_profiles VALUES ('student-b1','b1','active')");$pdo->exec("INSERT INTO learner_ai_capability_profiles (id,student_id,status,talent_map_json,trend_signals_json,generated_at,superseded_at) VALUES ('profile-b1','student-b1','ready_model','[{\"field\":\"Kỹ thuật\",\"score\":99}]','[]','2026-08-27 00:00:00',NULL)");
$pdo->exec("INSERT INTO privacy_consents VALUES ('revoke','student-a6','assessment',0,'2026-08-27')");
$repository=new SchoolAiAggregateRepository($pdo);$aggregate=$repository->aggregate('school-a',5,'2026-01-01');
school_ai_assert(count($aggregate['cohorts'])===3,'class with five consented learners plus grade and whole-school cohorts are visible while the two-person class is suppressed');
school_ai_assert($aggregate['suppressed_cohort_count']===1,'small cohort is counted only as suppressed');
$classA1=$aggregate['cohorts'][0];school_ai_assert(!str_contains(json_encode($classA1),'Chỉ một học sinh')&&!str_contains(json_encode($classA1),'Xu hướng riêng lẻ'),'individual talent and trend cells below minimum cohort are suppressed');
school_ai_assert(!str_contains(json_encode($aggregate),'Hết hạn'),'retention cutoff excludes expired profile evidence');
$eventId=100;foreach(['assessment','skills','activity','evaluation'] as $scope){$pdo->prepare('INSERT INTO learner_ai_consent_events VALUES (?,?,?,?,?,?)')->execute(["regrant-".$eventId++, 'student-a6',$scope,'granted','2026-08-27 01:00:00',"regrant-request-{$scope}"]);}$regranted=$repository->aggregate('school-a',5,'2026-01-01');$classAfterRegrant=array_values(array_filter($regranted['cohorts'],static fn(array $c):bool=>$c['cohort_key']==='class:a1'))[0]??null;school_ai_assert(($classAfterRegrant['student_count']??0)===6,'latest consent event supports grant after revoke without permanent exclusion');
$encoded=json_encode($aggregate);school_ai_assert(!str_contains($encoded,'student-a')&&!str_contains($encoded,'student-b'),'aggregate never exposes student identifiers');
$captured=[];$service=new SchoolAiInsightService($repository,static fn(string $user):array=>['id'=>$user==='school-user'?'school-a':'school-b'],static function(array $payload)use(&$captured):array{$captured=$payload;return ['summary'=>'Xu hướng kỹ thuật tích cực.','priorities'=>['Mở thêm dự án kỹ thuật'],'confidence'=>'high'];},null,5);
$result=$service->insight('school-user');school_ai_assert($result['state']==='ready_model'&&$result['analysis_origin']==='model','authorized school receives model explanation over aggregates');
school_ai_assert(is_array($result['evidence']??null)&&count($result['evidence'])===3,'school insight exposes only aggregate evidence references');
$gatedCalls=0;$gated=new SchoolAiInsightService($repository,static fn():array=>['id'=>'school-a'],static function()use(&$gatedCalls):array{$gatedCalls++;return ['summary'=>'must not run'];},null,5,null,static fn():bool=>false);$gatedResult=$gated->insight('school-user');school_ai_assert($gatedResult['state']==='ready_rule'&&$gatedCalls===0,'school model is gated by unified rollout policy');
$queued=[];$async=new SchoolAiInsightService($repository,static fn():array=>['id'=>'school-a'],static fn():array=>['summary'=>'queued'],null,5,null,static fn():bool=>true,'model-v1',false,604800,static function(string $school,string $hash)use(&$queued):void{$queued=[$school,$hash];});$asyncResult=$async->insight('school-user');school_ai_assert($asyncResult['state']==='pending'&&$queued[0]==='school-a','school GET never invokes Gemini synchronously and enqueues a deterministic refresh');
$oldAsync=new SchoolAiInsightService($repository,static fn():array=>['id'=>'school-a'],static fn():array=>['summary'=>'must not run'],static fn():?array=>['state'=>'ready_model','generated_at'=>'2020-01-01 00:00:00','model_version'=>'old'],5,null,static fn():bool=>true,'new',false,60);school_ai_assert($oldAsync->insight('school-user')['state']==='ai_unavailable','async path refuses an LKG beyond the stale SLA');
$prompt=json_encode($captured);school_ai_assert(!str_contains($prompt,'student-a')&&!str_contains($prompt,'student-b')&&!str_contains($prompt,'@'),'school prompt contains aggregate evidence only and no PII values');
$other=$service->insight('other-school-user');school_ai_assert(($other['state']??null)==='insufficient_data','tenant resolver cannot read another school aggregate');
$store=new DatabaseSchoolAiInsightRepository($pdo);$store->save('school-a',$result,'gemini-test');
$stale=new SchoolAiInsightService($repository,static fn():array=>['id'=>'school-a'],static function():array{throw new RuntimeException('google outage');},static fn(string $schoolId):?array=>$store->latest($schoolId),5);
$staleResult=$stale->insight('school-user');school_ai_assert($staleResult['state']==='stale_model'&&$staleResult['last_known_good']===true,'provider outage serves explicitly stale last-known-good insight');
$application=(string)file_get_contents(dirname(__DIR__).'/src/Bootstrap/Application.php');$matrix=(string)file_get_contents(dirname(__DIR__).'/src/Rbac/EndpointPermissionMatrix.php');$view=(string)file_get_contents(dirname(__DIR__).'/app/school/analytics.php');$client=(string)file_get_contents(dirname(__DIR__).'/assets/js/school-ai-insights.js');$migration=(string)file_get_contents(dirname(__DIR__).'/database/migrations/learner/012_create_school_ai_insights.php');$worker=(string)file_get_contents(dirname(__DIR__).'/bin/worker-school-ai-refresh.php');
school_ai_assert(str_contains($application,"/api/v1/schools/me/ai-insights")&&str_contains($application,"school_analytics.read_own"),'school AI endpoint requires authenticated school analytics permission');
school_ai_assert(str_contains($matrix,"GET /api/v1/schools/me/ai-insights")&&str_contains($view,'data-school-ai-insight')&&str_contains($view,'data-school-ai-cohorts')&&str_contains($client,"credentials:'same-origin'")&&str_contains($client,'data-school-ai-cohorts'),'RBAC matrix, aggregate view and same-origin endpoint client are wired');
school_ai_assert(str_contains($migration,'school_ai_insights')&&str_contains($migration,'stale_since')&&str_contains($migration,'aggregate_hash'),'Phase 6 insight persistence migration declares last-known-good fields');
school_ai_assert(str_contains($worker,'SchoolAiRefreshWorker')&&str_contains($worker,'runOnce'),'school insight Gemini work is executed by a queue worker, not the browser request');
school_ai_assert(!str_contains($client,'generativelanguage.googleapis')&&!str_contains($client,'x-goog-api-key'),'school browser never calls Gemini or contains provider credentials');
echo "school_ai_insight_test: OK\n";
