<?php
declare(strict_types=1);
namespace TalentHub\Modules\Business\Service;
use TalentHub\Http\ApiException;use TalentHub\Http\CollectionQuery;use TalentHub\Modules\Business\Repository\BusinessWorkflowRepository;

final class BusinessWorkflowService
{
    public function __construct(private readonly BusinessWorkflowRepository $repo){}
    public function enterprise(string $userId):string{return $this->repo->enterpriseId($userId)??throw new ApiException(404,'RESOURCE_NOT_FOUND','Không tìm thấy doanh nghiệp hiện tại.');}
    public function student(string $userId):string{return $this->repo->studentId($userId)??throw new ApiException(404,'RESOURCE_NOT_FOUND','Không tìm thấy hồ sơ học viên.');}
    public function posts(string $userId,CollectionQuery $q):array{return $this->repo->posts($this->enterprise($userId),$q);}
    public function createPost(string $userId,array $in,string $requestId):array{$d=$this->postData($in);$id=$this->repo->insertPost($this->enterprise($userId),$d);$this->repo->audit($userId,'internship_post.created','internship_post',$id,$requestId);return $this->repo->post($this->enterprise($userId),$id)??[];}
    public function updatePost(string $userId,string $id,array $in,string $requestId):array{$owner=$this->enterprise($userId);$current=$this->repo->post($owner,$id)??throw new ApiException(404,'RESOURCE_NOT_FOUND','Không tìm thấy tin thực tập.');$this->repo->updatePost($owner,$id,$this->postData(array_merge($current,$in)));$this->repo->audit($userId,'internship_post.updated','internship_post',$id,$requestId);return $this->repo->post($owner,$id)??[];}
    public function transitionPost(string $userId,string $id,string $action,string $requestId):array{$owner=$this->enterprise($userId);[$from,$to]=$action==='publish'?['draft','published']:['published','closed'];if(!$this->repo->transitionPost($owner,$id,$from,$to)){throw new ApiException(409,'INVALID_STATE_TRANSITION','Trạng thái tin thực tập không cho phép thao tác.');}$this->repo->audit($userId,"internship_post.{$action}ed",'internship_post',$id,$requestId);return $this->repo->post($owner,$id)??[];}
    public function publicPosts(CollectionQuery $q):array{return $this->repo->publicPosts($q);}
    public function apply(string $userId,string $postId,array $in,string $requestId):array{$cv=$this->text($in['cvUrl']??null,'cvUrl',5,500);$id=$this->repo->apply($this->student($userId),$postId,$cv);if($id===''){throw new ApiException(404,'RESOURCE_NOT_FOUND','Tin thực tập không khả dụng.');}$this->repo->audit($userId,'internship_application.created','internship_application',$id,$requestId);return ['id'=>$id,'status'=>'submitted'];}
    public function studentApplications(string $userId):array{return $this->repo->studentApplications($this->student($userId));}
    public function withdraw(string $userId,string $id,string $requestId):array{if(!$this->repo->withdraw($this->student($userId),$id)){throw new ApiException(409,'INVALID_STATE_TRANSITION','Không thể rút đơn ứng tuyển.');}$this->repo->audit($userId,'internship_application.withdrawn','internship_application',$id,$requestId);return ['id'=>$id,'status'=>'withdrawn'];}
    public function applications(string $userId,string $postId):array{return $this->repo->applications($this->enterprise($userId),$postId);}
    public function review(string $userId,string $id,array $in,string $requestId):array{$status=(string)($in['status']??'');if(!in_array($status,['reviewing','shortlisted','accepted','rejected'],true)){throw new ApiException(422,'VALIDATION_FAILED','Trạng thái review không hợp lệ.');}$note=isset($in['reviewerNote'])?$this->text($in['reviewerNote'],'reviewerNote',0,1000):null;if(!$this->repo->review($this->enterprise($userId),$userId,$id,$status,$note)){throw new ApiException(404,'RESOURCE_NOT_FOUND','Không tìm thấy đơn ứng tuyển.');}$this->repo->audit($userId,'internship_application.reviewed','internship_application',$id,$requestId);return ['id'=>$id,'status'=>$status];}
    public function projects(CollectionQuery $q):array{return $this->repo->projects($q);}
    public function sponsor(string $userId,array $in,string $requestId):array{$amount=(string)($in['amount']??'');if(!preg_match('/^\d+(\.\d{1,2})?$/',$amount)||(float)$amount<=0){throw new ApiException(422,'VALIDATION_FAILED','Số tiền tài trợ không hợp lệ.');}$currency=strtoupper((string)($in['currency']??'VND'));if(!preg_match('/^[A-Z]{3}$/',$currency)){throw new ApiException(422,'VALIDATION_FAILED','Currency không hợp lệ.');}$id=$this->repo->sponsor($this->enterprise($userId),(string)($in['projectId']??''),$amount,$currency,isset($in['note'])?$this->text($in['note'],'note',0,1000):null);if($id===''){throw new ApiException(404,'RESOURCE_NOT_FOUND','Dự án không khả dụng.');}$this->repo->audit($userId,'sponsorship.created','sponsorship',$id,$requestId);return ['id'=>$id,'status'=>'pledged'];}
    public function sponsorships(string $userId):array{return $this->repo->sponsorships($this->enterprise($userId));}
    public function cancelSponsorship(string $userId,string $id,string $requestId):array{if(!$this->repo->cancelSponsorship($this->enterprise($userId),$id)){throw new ApiException(409,'INVALID_STATE_TRANSITION','Không thể hủy tài trợ.');}$this->repo->audit($userId,'sponsorship.cancelled','sponsorship',$id,$requestId);return ['id'=>$id,'status'=>'cancelled'];}
    public function createPayment(string $userId,array $in,string $requestId):array{$provider=$this->text($in['provider']??'manual','provider',2,100);$id=$this->repo->createPayment($this->enterprise($userId),(string)($in['sponsorshipId']??''),$provider);if($id===''){throw new ApiException(409,'INVALID_STATE_TRANSITION','Không thể tạo payment order.');}$this->repo->audit($userId,'payment.created','payment_order',$id,$requestId);return ['id'=>$id,'status'=>'pending'];}
    public function payments(string $userId):array{return $this->repo->payments($this->enterprise($userId));}
    private function postData(array $in):array{$deadline=(string)($in['deadline']??'');$date=\DateTimeImmutable::createFromFormat('!Y-m-d',$deadline);if(!$date||$date->format('Y-m-d')!==$deadline){throw new ApiException(422,'VALIDATION_FAILED','Deadline không hợp lệ.');}$mode=(string)($in['workMode']??'onsite');if(!in_array($mode,['onsite','remote','hybrid'],true)){throw new ApiException(422,'VALIDATION_FAILED','Work mode không hợp lệ.');}$openings=filter_var($in['openings']??1,FILTER_VALIDATE_INT,['options'=>['min_range'=>1,'max_range'=>1000]]);if($openings===false){throw new ApiException(422,'VALIDATION_FAILED','Openings không hợp lệ.');}return ['title'=>$this->text($in['title']??null,'title',2,255),'description'=>isset($in['description'])?$this->text($in['description'],'description',0,10000):null,'location'=>$this->text($in['location']??null,'location',2,255),'workMode'=>$mode,'openings'=>$openings,'deadline'=>$deadline];}
    private function text(mixed $v,string $field,int $min,int $max):string{if(!is_string($v)){throw new ApiException(422,'VALIDATION_FAILED',"{$field} không hợp lệ.");}$v=trim($v);if(mb_strlen($v)<$min||mb_strlen($v)>$max){throw new ApiException(422,'VALIDATION_FAILED',"{$field} không hợp lệ.");}return $v;}
}
