<?php
declare(strict_types=1);
namespace TalentHub\Modules\Business\Repository;
use PDO;use TalentHub\Http\CollectionQuery;use TalentHub\Support\Uuid;

final class BusinessWorkflowRepository
{
    public function __construct(private readonly PDO $pdo){}
    public function enterpriseId(string $userId):?string{$s=$this->pdo->prepare('SELECT enterpriseId FROM enterprise_members WHERE userId=? LIMIT 1');$s->execute([$userId]);$id=$s->fetchColumn();return is_string($id)?$id:null;}
    public function studentId(string $userId):?string{$s=$this->pdo->prepare('SELECT id FROM student_profiles WHERE userId=? LIMIT 1');$s->execute([$userId]);$id=$s->fetchColumn();return is_string($id)?$id:null;}
    /** @return list<array<string,mixed>> */
    public function posts(string $enterpriseId,CollectionQuery $q):array{$order=['createdAt'=>'createdAt','title'=>'title','deadline'=>'deadline'][$q->sort];$where='enterpriseId=:owner';$p=['owner'=>$enterpriseId];if(isset($q->filters['status'])){$where.=' AND status=:status';$p['status']=$q->filters['status'];}$s=$this->pdo->prepare("SELECT * FROM internship_posts WHERE {$where} ORDER BY {$order} ".strtoupper($q->direction)." LIMIT {$q->limit} OFFSET {$q->offset}");$s->execute($p);return array_values($s->fetchAll());}
    public function post(string $enterpriseId,string $id):?array{$s=$this->pdo->prepare('SELECT * FROM internship_posts WHERE id=? AND enterpriseId=?');$s->execute([$id,$enterpriseId]);$r=$s->fetch();return is_array($r)?$r:null;}
    public function insertPost(string $enterpriseId,array $d):string{$id=Uuid::v4();$s=$this->pdo->prepare('INSERT INTO internship_posts(id,enterpriseId,title,description,location,workMode,openings,deadline,status) VALUES(?,?,?,?,?,?,?,?,?)');$s->execute([$id,$enterpriseId,$d['title'],$d['description'],$d['location'],$d['workMode'],$d['openings'],$d['deadline'],'draft']);return $id;}
    public function updatePost(string $enterpriseId,string $id,array $d):void{$s=$this->pdo->prepare('UPDATE internship_posts SET title=?,description=?,location=?,workMode=?,openings=?,deadline=? WHERE id=? AND enterpriseId=? AND status="draft"');$s->execute([$d['title'],$d['description'],$d['location'],$d['workMode'],$d['openings'],$d['deadline'],$id,$enterpriseId]);}
    public function transitionPost(string $enterpriseId,string $id,string $from,string $to):bool{$s=$this->pdo->prepare('UPDATE internship_posts SET status=? WHERE id=? AND enterpriseId=? AND status=?');$s->execute([$to,$id,$enterpriseId,$from]);return $s->rowCount()===1;}
    /** @return list<array<string,mixed>> */
    public function publicPosts(CollectionQuery $q):array{$order=['createdAt'=>'createdAt','title'=>'title','deadline'=>'deadline'][$q->sort];$s=$this->pdo->prepare("SELECT id,enterpriseId,title,description,location,workMode,openings,deadline,createdAt FROM internship_posts WHERE status='published' AND deadline>=CURRENT_DATE ORDER BY {$order} ".strtoupper($q->direction)." LIMIT {$q->limit} OFFSET {$q->offset}");$s->execute();return array_values($s->fetchAll());}
    public function apply(string $studentId,string $postId,string $cvUrl):string{$id=Uuid::v4();$s=$this->pdo->prepare("INSERT INTO internship_applications(id,postId,studentId,cvUrl) SELECT ?,id,?,? FROM internship_posts WHERE id=? AND status='published' AND deadline>=CURRENT_DATE");$s->execute([$id,$studentId,$cvUrl,$postId]);return $s->rowCount()===1?$id:'';}
    /** @return list<array<string,mixed>> */
    public function studentApplications(string $studentId):array{$s=$this->pdo->prepare('SELECT ia.*,ip.title,ip.enterpriseId FROM internship_applications ia JOIN internship_posts ip ON ip.id=ia.postId WHERE ia.studentId=? ORDER BY ia.appliedAt DESC');$s->execute([$studentId]);return array_values($s->fetchAll());}
    public function withdraw(string $studentId,string $id):bool{$s=$this->pdo->prepare("UPDATE internship_applications SET status='withdrawn' WHERE id=? AND studentId=? AND status IN ('submitted','reviewing','shortlisted')");$s->execute([$id,$studentId]);return $s->rowCount()===1;}
    /** @return list<array<string,mixed>> */
    public function applications(string $enterpriseId,string $postId):array{$s=$this->pdo->prepare('SELECT ia.* FROM internship_applications ia JOIN internship_posts ip ON ip.id=ia.postId WHERE ip.enterpriseId=? AND ip.id=? ORDER BY ia.appliedAt DESC');$s->execute([$enterpriseId,$postId]);return array_values($s->fetchAll());}
    public function review(string $enterpriseId,string $userId,string $id,string $status,?string $note):bool{$s=$this->pdo->prepare("UPDATE internship_applications ia JOIN internship_posts ip ON ip.id=ia.postId SET ia.status=?,ia.reviewerId=?,ia.reviewerNote=?,ia.reviewedAt=UTC_TIMESTAMP(6) WHERE ia.id=? AND ip.enterpriseId=? AND ia.status<>'withdrawn'");$s->execute([$status,$userId,$note,$id,$enterpriseId]);return $s->rowCount()===1;}
    /** @return list<array<string,mixed>> */
    public function projects(CollectionQuery $q):array{$order=['createdAt'=>'createdAt','title'=>'title','fundingGoal'=>'fundingGoal'][$q->sort];$s=$this->pdo->prepare("SELECT * FROM projects WHERE status='open' ORDER BY {$order} ".strtoupper($q->direction)." LIMIT {$q->limit} OFFSET {$q->offset}");$s->execute();return array_values($s->fetchAll());}
    public function sponsor(string $enterpriseId,string $projectId,string $amount,string $currency,?string $note):string{$id=Uuid::v4();$s=$this->pdo->prepare("INSERT INTO project_sponsorships(id,enterpriseId,projectId,amount,currency,note) SELECT ?,?,id,?,?,? FROM projects WHERE id=? AND status='open'");$s->execute([$id,$enterpriseId,$amount,$currency,$note,$projectId]);return $s->rowCount()===1?$id:'';}
    /** @return list<array<string,mixed>> */ public function sponsorships(string $enterpriseId):array{$s=$this->pdo->prepare('SELECT ps.*,p.title AS projectTitle FROM project_sponsorships ps JOIN projects p ON p.id=ps.projectId WHERE ps.enterpriseId=? ORDER BY ps.createdAt DESC');$s->execute([$enterpriseId]);return array_values($s->fetchAll());}
    public function cancelSponsorship(string $enterpriseId,string $id):bool{$s=$this->pdo->prepare("UPDATE project_sponsorships SET status='cancelled',cancelledAt=UTC_TIMESTAMP(6) WHERE id=? AND enterpriseId=? AND status='pledged'");$s->execute([$id,$enterpriseId]);return $s->rowCount()===1;}
    public function createPayment(string $enterpriseId,string $sponsorshipId,string $provider):string{$id=Uuid::v4();$this->pdo->beginTransaction();try{$s=$this->pdo->prepare("INSERT INTO payment_orders(id,enterpriseId,sponsorshipId,amount,currency,provider) SELECT ?,enterpriseId,id,amount,currency,? FROM project_sponsorships WHERE id=? AND enterpriseId=? AND status='pledged'");$s->execute([$id,$provider,$sponsorshipId,$enterpriseId]);if($s->rowCount()!==1){$this->pdo->rollBack();return '';}$u=$this->pdo->prepare("UPDATE project_sponsorships SET status='pending_payment' WHERE id=? AND enterpriseId=?");$u->execute([$sponsorshipId,$enterpriseId]);$this->pdo->commit();return $id;}catch(\Throwable $e){if($this->pdo->inTransaction()){$this->pdo->rollBack();}throw $e;}}
    /** @return list<array<string,mixed>> */ public function payments(string $enterpriseId):array{$s=$this->pdo->prepare('SELECT * FROM payment_orders WHERE enterpriseId=? ORDER BY createdAt DESC');$s->execute([$enterpriseId]);return array_values($s->fetchAll());}
    public function audit(string $userId,string $action,string $type,string $id,string $requestId):void{$s=$this->pdo->prepare('INSERT INTO audit_logs(id,userId,action,entityType,entityId,requestId,metadata) VALUES(?,?,?,?,?,?,?)');$s->execute([Uuid::v4(),$userId,$action,$type,$id,$requestId,'{}']);}
}
