<?php
declare(strict_types=1);
use TalentHub\Database\Migration\AbstractMigration;
use TalentHub\Database\Migration\MigrationContext;
return new class extends AbstractMigration {
 public function description():string{return 'Create expiring organization registration request queue';}
 public function preflight(MigrationContext $c):void{$c->assertTableAbsent('organization_registration_requests');}
 public function up(MigrationContext $c):void{$c->execute("CREATE TABLE organization_registration_requests (id CHAR(36) NOT NULL,type VARCHAR(20) NOT NULL,organizationName VARCHAR(255) NOT NULL,fullName VARCHAR(150) NOT NULL,email VARCHAR(255) NOT NULL,phone VARCHAR(30) NOT NULL,address VARCHAR(500) NOT NULL,passwordHash VARCHAR(255) NOT NULL,status VARCHAR(20) NOT NULL DEFAULT 'pending',expiresAt DATETIME(6) NOT NULL,reviewedAt DATETIME(6) NULL,reviewedBy CHAR(36) NULL,reviewNote VARCHAR(1000) NULL,createdUserId CHAR(36) NULL,createdOrganizationId CHAR(36) NULL,createdAt DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),updatedAt DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),PRIMARY KEY(id),KEY idx_org_registration_status_expiry(status,expiresAt),KEY idx_org_registration_email_status(email,status),KEY idx_org_registration_reviewer(reviewedBy),CONSTRAINT fk_org_registration_reviewer FOREIGN KEY(reviewedBy) REFERENCES users(id) ON DELETE SET NULL,CONSTRAINT chk_org_registration_type CHECK(type IN('school','enterprise')),CONSTRAINT chk_org_registration_status CHECK(status IN('pending','approved','rejected'))) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");if(!$c->tableExists('school_members')){$c->execute("CREATE TABLE school_members (id CHAR(36) NOT NULL,schoolId CHAR(36) NOT NULL,userId CHAR(36) NOT NULL,memberRole VARCHAR(50) NOT NULL DEFAULT 'member',createdAt DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),PRIMARY KEY(id),UNIQUE KEY uq_school_members_user(userId),KEY idx_school_members_school(schoolId),CONSTRAINT fk_school_members_school FOREIGN KEY(schoolId) REFERENCES schools(id) ON DELETE CASCADE,CONSTRAINT fk_school_members_user FOREIGN KEY(userId) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");}}
 public function down(MigrationContext $c):void{$c->execute('DROP TABLE organization_registration_requests');}
};
