<?php
declare(strict_types=1);
use TalentHub\Database\Migration\AbstractMigration;use TalentHub\Database\Migration\MigrationContext;
return new class extends AbstractMigration {
    private const TABLES=['projects','internship_posts','internship_applications','project_sponsorships','notifications','payment_orders'];
    public function description(): string{return 'Create internship, sponsorship, notification and payment workflow tables';}
    public function preflight(MigrationContext $c):void{foreach(self::TABLES as $table){$c->assertTableAbsent($table);}}
    public function up(MigrationContext $c):void{
        $c->execute("CREATE TABLE projects (id CHAR(36) NOT NULL,schoolId CHAR(36) NOT NULL,title VARCHAR(255) NOT NULL,summary VARCHAR(1000) NULL,status VARCHAR(30) NOT NULL DEFAULT 'open',fundingGoal DECIMAL(12,2) NULL,createdAt DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),updatedAt DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),PRIMARY KEY(id),KEY idx_projects_school_status(schoolId,status),CONSTRAINT fk_projects_school FOREIGN KEY(schoolId) REFERENCES schools(id) ON DELETE RESTRICT ON UPDATE CASCADE,CONSTRAINT chk_projects_status CHECK(status IN ('draft','open','funded','closed')),CONSTRAINT chk_projects_goal CHECK(fundingGoal IS NULL OR fundingGoal>0)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
        $c->execute("CREATE TABLE internship_posts (id CHAR(36) NOT NULL,enterpriseId CHAR(36) NOT NULL,title VARCHAR(255) NOT NULL,description TEXT NULL,location VARCHAR(255) NOT NULL,workMode VARCHAR(20) NOT NULL DEFAULT 'onsite',openings INT UNSIGNED NOT NULL DEFAULT 1,deadline DATE NOT NULL,status VARCHAR(20) NOT NULL DEFAULT 'draft',createdAt DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),updatedAt DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),PRIMARY KEY(id),KEY idx_posts_enterprise_status_created(enterpriseId,status,createdAt),KEY idx_posts_public(status,deadline),CONSTRAINT fk_posts_enterprise FOREIGN KEY(enterpriseId) REFERENCES enterprises(id) ON DELETE RESTRICT ON UPDATE CASCADE,CONSTRAINT chk_posts_mode CHECK(workMode IN ('onsite','remote','hybrid')),CONSTRAINT chk_posts_status CHECK(status IN ('draft','published','closed')),CONSTRAINT chk_posts_openings CHECK(openings>0)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
        $c->execute("CREATE TABLE internship_applications (id CHAR(36) NOT NULL,postId CHAR(36) NOT NULL,studentId CHAR(36) NOT NULL,status VARCHAR(20) NOT NULL DEFAULT 'submitted',cvUrl VARCHAR(500) NOT NULL,reviewerId CHAR(36) NULL,reviewerNote VARCHAR(1000) NULL,appliedAt DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),reviewedAt DATETIME(6) NULL,updatedAt DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),PRIMARY KEY(id),UNIQUE KEY uq_application_post_student(postId,studentId),KEY idx_application_student_status(studentId,status),KEY idx_application_post_status(postId,status),CONSTRAINT fk_application_post FOREIGN KEY(postId) REFERENCES internship_posts(id) ON DELETE RESTRICT ON UPDATE CASCADE,CONSTRAINT fk_application_student FOREIGN KEY(studentId) REFERENCES student_profiles(id) ON DELETE RESTRICT ON UPDATE CASCADE,CONSTRAINT fk_application_reviewer FOREIGN KEY(reviewerId) REFERENCES users(id) ON DELETE SET NULL ON UPDATE CASCADE,CONSTRAINT chk_application_status CHECK(status IN ('submitted','reviewing','shortlisted','accepted','rejected','withdrawn'))) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
        $c->execute("CREATE TABLE project_sponsorships (id CHAR(36) NOT NULL,enterpriseId CHAR(36) NOT NULL,projectId CHAR(36) NOT NULL,amount DECIMAL(12,2) NOT NULL,currency CHAR(3) NOT NULL DEFAULT 'VND',status VARCHAR(20) NOT NULL DEFAULT 'pledged',note VARCHAR(1000) NULL,cancelledAt DATETIME(6) NULL,createdAt DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),updatedAt DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),PRIMARY KEY(id),KEY idx_sponsorship_enterprise_status(enterpriseId,status),KEY idx_sponsorship_project(projectId),CONSTRAINT fk_sponsorship_enterprise FOREIGN KEY(enterpriseId) REFERENCES enterprises(id) ON DELETE RESTRICT ON UPDATE CASCADE,CONSTRAINT fk_sponsorship_project FOREIGN KEY(projectId) REFERENCES projects(id) ON DELETE RESTRICT ON UPDATE CASCADE,CONSTRAINT chk_sponsorship_amount CHECK(amount>0),CONSTRAINT chk_sponsorship_status CHECK(status IN ('pledged','pending_payment','paid','cancelled','refunded'))) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
        $c->execute("CREATE TABLE notifications (id CHAR(36) NOT NULL,userId CHAR(36) NOT NULL,notificationType VARCHAR(50) NOT NULL,title VARCHAR(255) NOT NULL,message VARCHAR(2000) NOT NULL,relatedEntityType VARCHAR(100) NULL,relatedEntityId CHAR(36) NULL,isRead TINYINT UNSIGNED NOT NULL DEFAULT 0,readAt DATETIME(6) NULL,createdAt DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),PRIMARY KEY(id),KEY idx_notification_user_read_created(userId,isRead,createdAt),CONSTRAINT fk_notification_user FOREIGN KEY(userId) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,CONSTRAINT chk_notification_read CHECK(isRead IN (0,1))) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
        $c->execute("CREATE TABLE payment_orders (id CHAR(36) NOT NULL,enterpriseId CHAR(36) NOT NULL,sponsorshipId CHAR(36) NOT NULL,amount DECIMAL(12,2) NOT NULL,currency CHAR(3) NOT NULL DEFAULT 'VND',provider VARCHAR(100) NOT NULL,paymentStatus VARCHAR(20) NOT NULL DEFAULT 'pending',providerReference VARCHAR(255) NULL,paidAt DATETIME(6) NULL,createdAt DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),updatedAt DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),PRIMARY KEY(id),UNIQUE KEY uq_payment_sponsorship(sponsorshipId),KEY idx_payment_enterprise_status(enterpriseId,paymentStatus),CONSTRAINT fk_payment_enterprise FOREIGN KEY(enterpriseId) REFERENCES enterprises(id) ON DELETE RESTRICT ON UPDATE CASCADE,CONSTRAINT fk_payment_sponsorship FOREIGN KEY(sponsorshipId) REFERENCES project_sponsorships(id) ON DELETE RESTRICT ON UPDATE CASCADE,CONSTRAINT chk_payment_amount CHECK(amount>0),CONSTRAINT chk_payment_status CHECK(paymentStatus IN ('pending','paid','failed','cancelled','refunded'))) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
    }
    public function down(MigrationContext $c):void{foreach(array_reverse(self::TABLES) as $table){$c->execute("DROP TABLE {$table}");}}
};
