<?php
declare(strict_types=1);
use TalentHub\Database\Migration\AbstractMigration;
use TalentHub\Database\Migration\MigrationContext;
return new class extends AbstractMigration {
    public function description(): string { return 'Create profiles and organization memberships'; }
    public function preflight(MigrationContext $c): void { foreach(['student_profiles','teacher_profiles','school_members','enterprise_members'] as $t){$c->assertTableAbsent($t);} }
    public function up(MigrationContext $c): void {
        $c->execute("CREATE TABLE student_profiles (id CHAR(36) NOT NULL, userId CHAR(36) NOT NULL, classId CHAR(36) NOT NULL, dateOfBirth DATE NOT NULL, phone VARCHAR(30) NOT NULL, studyStatus VARCHAR(50) NOT NULL DEFAULT 'active', createdAt DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), updatedAt DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY(id), UNIQUE KEY uq_student_profiles_user(userId), KEY idx_student_profiles_class_status(classId,studyStatus), CONSTRAINT fk_student_profiles_user FOREIGN KEY(userId) REFERENCES users(id) ON DELETE CASCADE, CONSTRAINT fk_student_profiles_class FOREIGN KEY(classId) REFERENCES classes(id), CONSTRAINT chk_student_profiles_study_status CHECK(studyStatus IN('active','inactive','graduated','transferred'))) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
        $c->execute("CREATE TABLE teacher_profiles (id CHAR(36) NOT NULL, userId CHAR(36) NOT NULL, schoolId CHAR(36) NOT NULL, isSchoolAdmin TINYINT UNSIGNED NOT NULL DEFAULT 0, createdAt DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), updatedAt DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY(id), UNIQUE KEY uq_teacher_profiles_user(userId), KEY idx_teacher_profiles_school(schoolId), CONSTRAINT fk_teacher_profiles_user FOREIGN KEY(userId) REFERENCES users(id) ON DELETE CASCADE, CONSTRAINT fk_teacher_profiles_school FOREIGN KEY(schoolId) REFERENCES schools(id), CONSTRAINT chk_teacher_profiles_admin CHECK(isSchoolAdmin IN(0,1))) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
        $c->execute("CREATE TABLE school_members (id CHAR(36) NOT NULL, schoolId CHAR(36) NOT NULL, userId CHAR(36) NOT NULL, memberRole VARCHAR(50) NOT NULL DEFAULT 'member', createdAt DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), updatedAt DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY(id), UNIQUE KEY uq_school_members_user(userId), KEY idx_school_members_school(schoolId), CONSTRAINT fk_school_members_school FOREIGN KEY(schoolId) REFERENCES schools(id), CONSTRAINT fk_school_members_user FOREIGN KEY(userId) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
        $c->execute("CREATE TABLE enterprise_members (id CHAR(36) NOT NULL, enterpriseId CHAR(36) NOT NULL, userId CHAR(36) NOT NULL, memberRole VARCHAR(50) NOT NULL DEFAULT 'member', createdAt DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), updatedAt DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY(id), UNIQUE KEY uq_enterprise_members_user(userId), KEY idx_enterprise_members_enterprise(enterpriseId), CONSTRAINT fk_enterprise_members_enterprise FOREIGN KEY(enterpriseId) REFERENCES enterprises(id), CONSTRAINT fk_enterprise_members_user FOREIGN KEY(userId) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
    }
    public function down(MigrationContext $c): void { $c->execute('DROP TABLE enterprise_members');$c->execute('DROP TABLE school_members');$c->execute('DROP TABLE teacher_profiles');$c->execute('DROP TABLE student_profiles'); }
};
