<?php
declare(strict_types=1);
namespace TalentHub\Bootstrap;

use TalentHub\Auth\Repository\AuthRepository;
use TalentHub\Auth\Service\AuthService;
use TalentHub\Auth\Service\LoginRateLimiter;
use TalentHub\Auth\Session\SessionManager;
use TalentHub\Database\Connection;
use TalentHub\Database\Exception\DatabaseConnectionException;
use TalentHub\Http\ApiException;
use TalentHub\Http\CollectionQuery;
use TalentHub\Http\CorsPolicy;
use TalentHub\Http\JsonResponse;
use TalentHub\Http\Request;
use TalentHub\Http\Router;
use TalentHub\Modules\School\Repository\SchoolRepository;
use TalentHub\Modules\School\Service\SchoolAuthorization;
use TalentHub\Modules\School\Service\SchoolDashboardService;
use TalentHub\Modules\Business\Repository\BusinessRepository;
use TalentHub\Modules\Business\Repository\BusinessWorkflowRepository;
use TalentHub\Modules\Business\Repository\EnterpriseTalentRepository;
use TalentHub\Modules\Business\Repository\InternshipRepository;
use TalentHub\Modules\Business\Service\BusinessProfileService;
use TalentHub\Modules\Business\Service\BusinessWorkflowService;
use TalentHub\Modules\Business\Service\EnterpriseTalentService;
use TalentHub\Modules\Business\Service\InternshipService;
use TalentHub\Modules\Notification\Repository\NotificationRepository;
use TalentHub\Modules\Notification\Service\NotificationService;
use TalentHub\Modules\Admin\Repository\AdminRepository;
use TalentHub\Modules\Student\Repository\StudentRepository;
use TalentHub\Modules\Student\Service\StudentProfileService;
use TalentHub\Modules\Teacher\Repository\TeacherRepository;
use TalentHub\Modules\Teacher\Repository\TeacherActivityRepository;
use TalentHub\Modules\Teacher\Service\TeacherActivityService;
use TalentHub\Modules\Teacher\Service\TeacherProfileService;
use TalentHub\Rbac\Service\PermissionService;
use TalentHub\Rbac\RoleCodes;
use TalentHub\Support\Id\RequestId;
use Throwable;

final class Application
{
    public function run(): never
    {
        $request=Request::fromGlobals();$requestId=RequestId::make($request->header('x-request-id'));
        try{CorsPolicy::enforceSameOrigin($request,$_SERVER['HTTP_HOST']??null);$this->buildRouter($requestId)->dispatch($request)->send();}
        catch(ApiException $e){JsonResponse::error($e,$requestId)->send();}
        catch(\RuntimeException $e){JsonResponse::error(new ApiException(422,'VALIDATION_FAILED',$e->getMessage()),$requestId)->send();}
        catch(DatabaseConnectionException){JsonResponse::error(new ApiException(503,'SERVICE_UNAVAILABLE','Dịch vụ dữ liệu tạm thời không khả dụng.'),$requestId)->send();}
        catch(Throwable){JsonResponse::error(new ApiException(500,'INTERNAL_ERROR','Đã xảy ra lỗi hệ thống.'),$requestId)->send();}
    }

    /**
     * Builds the router with all dependencies persisted across the request.
     * Kept public so server-side tests can dispatch handlers without going
     * through the `exit()`-style CLI path used by `run()`.
     */
    public function buildRouter(string $requestId): Router
    {
        $config=require dirname(__DIR__,2).'/config/database.php';$pdo=(new Connection($config))->connect();
        $session=new SessionManager(require dirname(__DIR__,2).'/config/session.php');$session->start();
        $auth=new AuthService(new AuthRepository($pdo));$loginLimiter=new LoginRateLimiter($pdo);$permissions=new PermissionService($pdo);$teachers=new TeacherProfileService(new TeacherRepository($pdo));$teacherActivities=new TeacherActivityService(new TeacherActivityRepository($pdo));$schools=new SchoolDashboardService(new SchoolRepository($pdo),$pdo,new SchoolAuthorization($pdo));$students=new StudentProfileService(new StudentRepository($pdo));$businesses=new BusinessProfileService(new BusinessRepository($pdo));$internships=new InternshipService(new InternshipRepository($pdo));$workflows=new BusinessWorkflowService(new BusinessWorkflowRepository($pdo),$internships);$talents=new EnterpriseTalentService(new EnterpriseTalentRepository($pdo));$notifications=new NotificationService(new NotificationRepository($pdo));$admin=new AdminRepository($pdo);$router=new Router();
        $router->add('GET','/api/v1/health',fn()=>JsonResponse::success(['status'=>'ok','database'=>'available'],$requestId));
        $router->add('GET','/api/v1/auth/csrf',fn()=>JsonResponse::success(['csrfToken'=>$session->csrfToken()],$requestId));
        $router->add('POST','/api/v1/auth/register',function(Request $r)use($auth,$requestId){$user=$auth->registerStudent($r->json(),$requestId,$_SERVER['REMOTE_ADDR']??null);return JsonResponse::success(['user'=>$user],$requestId,201);});
        $router->add('POST','/api/v1/auth/login',function(Request $r)use($auth,$loginLimiter,$session,$requestId){$input=$r->json();$email=is_string($input['email']??null)?$input['email']:'';$ip=$_SERVER['REMOTE_ADDR']??null;$loginLimiter->assertAllowed($email,$ip);$session->assertLoginAllowed();try{$user=$auth->login($input,$requestId,$ip);}catch(ApiException $e){if($e->errorCode==='INVALID_CREDENTIALS'){$loginLimiter->recordFailure($email,$ip);$session->recordLoginFailure();}throw $e;}$loginLimiter->clearIdentity($email,$ip);$session->clearLoginFailures();$session->login($user);return JsonResponse::success(['user'=>$user,'csrfToken'=>$session->csrfToken()],$requestId);});
        $router->add('GET','/api/v1/auth/me',function()use($auth,$session,$requestId){$cached=$session->requireUser();$user=$auth->current($cached['id']);$session->refreshUser($user);return JsonResponse::success(['user'=>$user],$requestId);});
        $router->add('POST','/api/v1/auth/logout',function(Request $r)use($session,$requestId){$session->requireUser();$session->assertCsrf($r->header('x-csrf-token'));$session->destroy();return JsonResponse::success(['loggedOut'=>true],$requestId);});
        $router->add('PATCH','/api/v1/auth/password',function(Request $r)use($auth,$session,$requestId){$user=$session->requireUser();$session->assertCsrf($r->header('x-csrf-token'));$auth->changePassword($user['id'],$r->json());$session->destroy();return JsonResponse::success(['passwordChanged'=>true,'reauthenticationRequired'=>true],$requestId);});
        $router->add('GET','/api/v1/teachers/me',function()use($session,$permissions,$teachers,$requestId){$user=$this->requireTeacher($session);$permissions->require($user['id'],'teacher_profile.read_own');return JsonResponse::success($teachers->get($user['id']),$requestId);});
        $router->add('PATCH','/api/v1/teachers/me',function(Request $r)use($session,$permissions,$teachers,$auth,$requestId){$user=$this->requireTeacher($session);$session->assertCsrf($r->header('x-csrf-token'));$permissions->require($user['id'],'teacher_profile.update_own');$profile=$teachers->update($user['id'],$r->json());$session->refreshUser($auth->current($user['id']));return JsonResponse::success($profile,$requestId);});
        $router->add('GET','/api/v1/teachers/me/dashboard',function()use($session,$permissions,$teachers,$requestId){$user=$this->requireTeacher($session);$permissions->require($user['id'],'teacher_dashboard.read_own');return JsonResponse::success($teachers->dashboard($user['id']),$requestId);});
        $router->add('PATCH','/api/v1/teachers/me/activities/{activityId}/registrations/{registrationId}',function(Request $r)use($session,$permissions,$teacherActivities,$requestId){$user=$this->requireTeacher($session);$session->assertCsrf($r->header('x-csrf-token'));$permissions->require($user['id'],'activity_registration.update_managed');$teacherId=$teacherActivities->teacherIdForUser($user['id']);return JsonResponse::success($teacherActivities->transitionRegistration($teacherId,$user['id'],$requestId,(string)$r->pathParam('activityId'),(string)$r->pathParam('registrationId'),$r->json()),$requestId);});
        $router->add('GET','/api/v1/schools/me',function()use($session,$permissions,$schools,$requestId){$user=$this->requireSchool($session);$permissions->require($user['id'],'school_profile.read_own');return JsonResponse::success($schools->getByUser($user['id']),$requestId);});
        $router->add('PATCH','/api/v1/schools/me',function(Request $r)use($session,$permissions,$schools,$requestId){$user=$this->requireSchool($session);$session->assertCsrf($r->header('x-csrf-token'));$permissions->require($user['id'],'school_profile.update_own');return JsonResponse::success($schools->update($user['id'],$r->json()),$requestId);});
        $router->add('GET','/api/v1/schools/me/dashboard',function()use($session,$permissions,$schools,$requestId){$user=$this->requireSchool($session);$permissions->require($user['id'],'school_dashboard.read_own');return JsonResponse::success($schools->dashboard($user['id']),$requestId);});
        $router->add('GET','/api/v1/schools/me/analytics',function()use($session,$permissions,$schools,$requestId){$user=$this->requireSchool($session);$permissions->require($user['id'],'school_analytics.read_own');return JsonResponse::success($schools->analytics($user['id']),$requestId);});
        $router->add('GET','/api/v1/schools/me/classes',function(Request $r)use($session,$permissions,$schools,$requestId){$user=$this->requireSchool($session);$permissions->require($user['id'],'class.read_own_school');$limit=$this->parseInt($r->queryParam('limit'),1,200,50);$offset=$this->parseInt($r->queryParam('offset'),0,1000000,0);return JsonResponse::success($schools->classes($user['id']),$requestId);});
        $router->add('POST','/api/v1/schools/me/classes',function(Request $r)use($session,$permissions,$schools,$requestId){$user=$this->requireSchool($session);$session->assertCsrf($r->header('x-csrf-token'));$permissions->require($user['id'],'class.create_own_school');return JsonResponse::success($schools->createClass($user['id'],$r->json()),$requestId,201);});
        $router->add('PATCH','/api/v1/schools/me/classes/{classId}',function(Request $r)use($session,$permissions,$schools,$requestId){$user=$this->requireSchool($session);$session->assertCsrf($r->header('x-csrf-token'));$classId=(string)$r->pathParam('classId');$permissions->require($user['id'],'class.update_own_school');return JsonResponse::success($schools->updateClass($user['id'],$classId,$r->json()),$requestId);});
        $router->add('POST','/api/v1/schools/me/classes/{classId}/archive',function(Request $r)use($session,$permissions,$schools,$requestId){$user=$this->requireSchool($session);$session->assertCsrf($r->header('x-csrf-token'));$classId=(string)$r->pathParam('classId');$permissions->require($user['id'],'class.archive_own_school');return JsonResponse::success($schools->archiveClass($user['id'],$classId),$requestId);});
        $router->add('GET','/api/v1/schools/me/teachers',function()use($session,$permissions,$schools,$requestId){$user=$this->requireSchool($session);$permissions->require($user['id'],'teacher_profile.read_own_school');return JsonResponse::success($schools->teachers($user['id']),$requestId);});
        $router->add('GET','/api/v1/schools/me/teachers/{profileId}',function(Request $r)use($session,$permissions,$schools,$requestId){$user=$this->requireSchool($session);$permissions->require($user['id'],'teacher_profile.read_own_school');$profileId=(string)$r->pathParam('profileId');return JsonResponse::success($schools->getTeacher($user['id'],$profileId),$requestId);});
        $router->add('POST','/api/v1/schools/me/teachers',function(Request $r)use($session,$permissions,$schools,$requestId){$user=$this->requireSchool($session);$session->assertCsrf($r->header('x-csrf-token'));$permissions->require($user['id'],'teacher_profile.invite_own_school');return JsonResponse::success($schools->inviteTeacher($user['id'],$r->json()),$requestId,201);});
        $router->add('PATCH','/api/v1/schools/me/teachers/{profileId}/admin',function(Request $r)use($session,$permissions,$schools,$requestId){$user=$this->requireSchool($session);$session->assertCsrf($r->header('x-csrf-token'));$profileId=(string)$r->pathParam('profileId');$permissions->require($user['id'],'teacher_profile.update_role_own_school');$input=$r->json();$isAdmin=!empty($input['isSchoolAdmin']);return JsonResponse::success($schools->setTeacherAdmin($user['id'],$profileId,$isAdmin),$requestId);});
        $router->add('PATCH','/api/v1/schools/me/teachers/{profileId}/status',function(Request $r)use($session,$permissions,$schools,$requestId){$user=$this->requireSchool($session);$session->assertCsrf($r->header('x-csrf-token'));$profileId=(string)$r->pathParam('profileId');$permissions->require($user['id'],'teacher_profile.deactivate_own_school');$input=$r->json();$active=!empty($input['active']);return JsonResponse::success($schools->setTeacherActive($user['id'],$profileId,$active),$requestId);});
        $router->add('GET','/api/v1/schools/me/students',function()use($session,$permissions,$schools,$requestId){$user=$this->requireSchool($session);$permissions->require($user['id'],'student_profile.read_own_school');return JsonResponse::success($schools->students($user['id']),$requestId);});
        $router->add('GET','/api/v1/schools/me/students/{profileId}',function(Request $r)use($session,$permissions,$schools,$requestId){$user=$this->requireSchool($session);$permissions->require($user['id'],'student_profile.read_own_school');$profileId=(string)$r->pathParam('profileId');return JsonResponse::success($schools->getStudent($user['id'],$profileId),$requestId);});
        $router->add('POST','/api/v1/schools/me/students',function(Request $r)use($session,$permissions,$schools,$requestId){$user=$this->requireSchool($session);$session->assertCsrf($r->header('x-csrf-token'));$permissions->require($user['id'],'student_profile.create_own_school');return JsonResponse::success($schools->createStudent($user['id'],$r->json()),$requestId,201);});
        $router->add('PATCH','/api/v1/schools/me/students/{profileId}',function(Request $r)use($session,$permissions,$schools,$requestId){$user=$this->requireSchool($session);$session->assertCsrf($r->header('x-csrf-token'));$profileId=(string)$r->pathParam('profileId');$permissions->require($user['id'],'student_profile.update_own_school');return JsonResponse::success($schools->updateStudent($user['id'],$profileId,$r->json()),$requestId);});
        $router->add('GET','/api/v1/students/me',function()use($session,$permissions,$students,$requestId){$user=$this->requireRole($session,'student','học viên');$permissions->require($user['id'],'student_profile.read_own');return JsonResponse::success($students->get($user['id']),$requestId);});
        $router->add('PATCH','/api/v1/students/me',function(Request $r)use($session,$permissions,$students,$auth,$requestId){$user=$this->requireRole($session,'student','học viên');$session->assertCsrf($r->header('x-csrf-token'));$permissions->require($user['id'],'student_profile.update_own');$profile=$students->update($user['id'],$r->json());$session->refreshUser($auth->current($user['id']));return JsonResponse::success($profile,$requestId);});
        $router->add('GET','/api/v1/students/me/dashboard',function()use($session,$permissions,$students,$requestId){$user=$this->requireRole($session,'student','học viên');$permissions->require($user['id'],'student_dashboard.read_own');return JsonResponse::success($students->dashboard($user['id']),$requestId);});
        $router->add('GET','/api/v1/businesses/me',function()use($session,$permissions,$businesses,$requestId){$user=$this->requireRole($session,RoleCodes::ENTERPRISE,'doanh nghiệp');$permissions->require($user['id'],'business_profile.read_own');return JsonResponse::success($businesses->get($user['id']),$requestId);});
        $router->add('PATCH','/api/v1/businesses/me',function(Request $r)use($session,$permissions,$businesses,$requestId){$user=$this->requireRole($session,RoleCodes::ENTERPRISE,'doanh nghiệp');$session->assertCsrf($r->header('x-csrf-token'));$permissions->require($user['id'],'business_profile.update_own');return JsonResponse::success($businesses->update($user['id'],$r->json()),$requestId);});
        $router->add('POST','/api/v1/businesses/me/logo',function(Request $r)use($session,$permissions,$businesses,$requestId){$user=$this->requireRole($session,RoleCodes::ENTERPRISE,'doanh nghiệp');$session->assertCsrf($r->header('x-csrf-token'));$permissions->require($user['id'],'business_profile.update_own');$url=$businesses->uploadLogo($user['id'],$r->json());return JsonResponse::success(['logoUrl'=>$url],$requestId);});
        $router->add('GET','/api/v1/businesses/me/dashboard',function()use($session,$permissions,$businesses,$requestId){$user=$this->requireRole($session,RoleCodes::ENTERPRISE,'doanh nghiệp');$permissions->require($user['id'],'business_dashboard.read_own');return JsonResponse::success($businesses->dashboard($user['id']),$requestId);});
        $router->add('GET','/api/v1/businesses/me/internships',function()use($session,$permissions,$internships,$requestId){$user=$this->requireRole($session,RoleCodes::ENTERPRISE,'doanh nghiệp');$permissions->require($user['id'],'internship_post.read_own_business');return JsonResponse::success($internships->listPosts($user['id']),$requestId);});
        $router->add('POST','/api/v1/businesses/me/internships',function(Request $r)use($session,$permissions,$internships,$requestId){$user=$this->requireRole($session,RoleCodes::ENTERPRISE,'doanh nghiệp');$session->assertCsrf($r->header('x-csrf-token'));$permissions->require($user['id'],'internship_post.create_own_business');return JsonResponse::success(['post'=>$internships->createPost($user['id'],$r->json())],$requestId,201);});
        $router->add('PATCH','/api/v1/businesses/me/internships/{postId}',function(Request $r)use($session,$permissions,$internships,$requestId){$user=$this->requireRole($session,RoleCodes::ENTERPRISE,'doanh nghiệp');$session->assertCsrf($r->header('x-csrf-token'));$permissions->require($user['id'],'internship_post.update_own_business');return JsonResponse::success(['post'=>$internships->updatePost($user['id'],(string)$r->pathParam('postId'),$r->json())],$requestId);});
        $router->add('POST','/api/v1/businesses/me/internships/{postId}/publish',function(Request $r)use($session,$permissions,$internships,$requestId){$user=$this->requireRole($session,RoleCodes::ENTERPRISE,'doanh nghiệp');$session->assertCsrf($r->header('x-csrf-token'));$permissions->require($user['id'],'internship_post.publish_own_business');$input=$r->json();if(array_diff(array_keys($input),['expectedCurrentStatus'])!==[]){throw new ApiException(422,'VALIDATION_FAILED','Request chứa field không được phép.');}return JsonResponse::success(['post'=>$internships->publish($user['id'],(string)$r->pathParam('postId'),(string)($input['expectedCurrentStatus']??''))],$requestId);});
        $router->add('POST','/api/v1/businesses/me/internships/{postId}/close',function(Request $r)use($session,$permissions,$internships,$requestId){$user=$this->requireRole($session,RoleCodes::ENTERPRISE,'doanh nghiệp');$session->assertCsrf($r->header('x-csrf-token'));$permissions->require($user['id'],'internship_post.close_own_business');$input=$r->json();if(array_diff(array_keys($input),['expectedCurrentStatus'])!==[]){throw new ApiException(422,'VALIDATION_FAILED','Request chứa field không được phép.');}return JsonResponse::success(['post'=>$internships->close($user['id'],(string)$r->pathParam('postId'),(string)($input['expectedCurrentStatus']??''))],$requestId);});
        $router->add('GET','/api/v1/businesses/me/internship-applications',function()use($session,$permissions,$internships,$requestId){$user=$this->requireRole($session,RoleCodes::ENTERPRISE,'doanh nghiệp');$permissions->require($user['id'],'internship_application.read_own_business');return JsonResponse::success($internships->listApplications($user['id']),$requestId);});
        $router->add('GET','/api/v1/businesses/me/internship-applications/{applicationId}',function(Request $r)use($session,$permissions,$internships,$requestId){$user=$this->requireRole($session,RoleCodes::ENTERPRISE,'doanh nghiệp');$permissions->require($user['id'],'internship_application.read_own_business');$permissions->require($user['id'],'internship_application.read_cv_own_business');return JsonResponse::success(['application'=>$internships->application($user['id'],(string)$r->pathParam('applicationId'))],$requestId);});
        $router->add('PATCH','/api/v1/businesses/me/internship-applications/{applicationId}',function(Request $r)use($session,$permissions,$internships,$requestId){$user=$this->requireRole($session,RoleCodes::ENTERPRISE,'doanh nghiệp');$session->assertCsrf($r->header('x-csrf-token'));$permissions->require($user['id'],'internship_application.review_own_business');return JsonResponse::success(['application'=>$internships->review($user['id'],(string)$r->pathParam('applicationId'),$r->json())],$requestId);});
        $router->add('GET','/api/v1/businesses/me/talents',function(Request $r)use($session,$permissions,$talents,$requestId){$user=$this->requireRole($session,RoleCodes::ENTERPRISE,'doanh nghiệp');$permissions->require($user['id'],'talent.search_consented');$params=['search'=>$r->queryParam('search'),'school'=>$r->queryParam('school'),'skills'=>$r->queryParam('skills'),'sort'=>$r->queryParam('sort'),'limit'=>$r->queryParam('limit'),'offset'=>$r->queryParam('offset')];return JsonResponse::success($talents->listTalents($user['id'],$params),$requestId);});
        $router->add('GET','/api/v1/businesses/me/talents/{studentId}',function(Request $r)use($session,$permissions,$talents,$requestId){$user=$this->requireRole($session,RoleCodes::ENTERPRISE,'doanh nghiệp');$permissions->require($user['id'],'talent.read_consented');$studentId=(string)$r->pathParam('studentId');return JsonResponse::success(['talent'=>$talents->getTalent($user['id'],$studentId)],$requestId);});
        $router->add('POST','/api/v1/businesses/me/talents/{studentId}/contact-requests',function(Request $r)use($session,$permissions,$talents,$requestId){$user=$this->requireRole($session,RoleCodes::ENTERPRISE,'doanh nghiệp');$session->assertCsrf($r->header('x-csrf-token'));$permissions->require($user['id'],'contact_request.create_own_business');$studentId=(string)$r->pathParam('studentId');return JsonResponse::success($talents->requestContact($user['id'],$studentId,$r->json(),$requestId),$requestId,201);});
        $router->add('GET','/api/v1/students/me/enterprise-profile-grants',function()use($session,$permissions,$talents,$requestId){$user=$this->requireRole($session,'student','học viên');$permissions->require($user['id'],'privacy_consent.read_own');return JsonResponse::success($talents->listGrants($user['id']),$requestId);});
        $router->add('POST','/api/v1/students/me/enterprise-profile-grants',function(Request $r)use($session,$permissions,$talents,$requestId){$user=$this->requireRole($session,'student','học viên');$session->assertCsrf($r->header('x-csrf-token'));$permissions->require($user['id'],'privacy_consent.manage_own');return JsonResponse::success($talents->grantAccess($user['id'],$r->json()),$requestId,201);});
        $router->add('DELETE','/api/v1/students/me/enterprise-profile-grants/{grantId}',function(Request $r)use($session,$permissions,$talents,$requestId){$user=$this->requireRole($session,'student','học viên');$session->assertCsrf($r->header('x-csrf-token'));$permissions->require($user['id'],'privacy_consent.manage_own');$grantId=(string)$r->pathParam('grantId');return JsonResponse::success($talents->revokeGrant($user['id'],$grantId),$requestId);});
        $router->add('GET','/api/v1/schools/me/reports',function(Request $r)use($session,$permissions,$schools,$requestId){$u=$this->requireSchool($session);$permissions->require($u['id'],'report.read_own_school');$q=CollectionQuery::fromRequest($r,['createdAt'],[],20,100);return JsonResponse::success(['items'=>$schools->listReports($u['id'],$q->limit),'page'=>$q->meta()],$requestId);});
        $router->add('POST','/api/v1/schools/me/reports',function(Request $r)use($session,$permissions,$schools,$requestId){$u=$this->requireSchool($session);$session->assertCsrf($r->header('x-csrf-token'));$permissions->require($u['id'],'report.create_own_school');$in=$r->json();return JsonResponse::success($schools->generateReport($u['id'],(string)($in['reportType']??''),isset($in['periodStart'])?(string)$in['periodStart']:null,isset($in['periodEnd'])?(string)$in['periodEnd']:null),$requestId,201);});
        $router->add('GET','/api/v1/schools/me/reports/{reportId}',function(Request $r)use($session,$permissions,$schools,$requestId){$u=$this->requireSchool($session);$permissions->require($u['id'],'report.download_own_school');return JsonResponse::success(['id'=>$r->pathParam('reportId'),'encoding'=>'base64','content'=>base64_encode($schools->readReportFile($u['id'],(string)$r->pathParam('reportId')))],$requestId);});
        $router->add('GET','/api/v1/businesses/me/internship-posts',function(Request $r)use($session,$permissions,$workflows,$requestId){$u=$this->requireRole($session,RoleCodes::ENTERPRISE,'doanh nghiệp');$permissions->require($u['id'],'internship_post.read_own_business');$q=CollectionQuery::fromRequest($r,['createdAt','title','deadline'],['status'=>['draft','active','closed','cancelled']]);return JsonResponse::success(['items'=>$workflows->posts($u['id'],$q),'page'=>$q->meta()],$requestId);});
        $router->add('POST','/api/v1/businesses/me/internship-posts',function(Request $r)use($session,$permissions,$workflows,$requestId){$u=$this->requireRole($session,RoleCodes::ENTERPRISE,'doanh nghiệp');$session->assertCsrf($r->header('x-csrf-token'));$permissions->require($u['id'],'internship_post.create_own_business');return JsonResponse::success($workflows->createPost($u['id'],$r->json(),$requestId),$requestId,201);});
        $router->add('PATCH','/api/v1/businesses/me/internship-posts/{postId}',function(Request $r)use($session,$permissions,$workflows,$requestId){$u=$this->requireRole($session,RoleCodes::ENTERPRISE,'doanh nghiệp');$session->assertCsrf($r->header('x-csrf-token'));$permissions->require($u['id'],'internship_post.update_own_business');return JsonResponse::success($workflows->updatePost($u['id'],(string)$r->pathParam('postId'),$r->json(),$requestId),$requestId);});
        foreach(['publish','close'] as $action){$router->add('POST',"/api/v1/businesses/me/internship-posts/{postId}/{$action}",function(Request $r)use($session,$permissions,$workflows,$requestId,$action){$u=$this->requireRole($session,RoleCodes::ENTERPRISE,'doanh nghiệp');$session->assertCsrf($r->header('x-csrf-token'));$permissions->require($u['id'],"internship_post.{$action}_own_business");return JsonResponse::success($workflows->transitionPost($u['id'],(string)$r->pathParam('postId'),$action,$requestId),$requestId);});}
        $router->add('GET','/api/v1/internship-posts',function(Request $r)use($session,$permissions,$workflows,$requestId){$u=$this->requireRole($session,'student','học viên');$permissions->require($u['id'],'internship_post.read_available');$q=CollectionQuery::fromRequest($r,['createdAt','title','deadline']);return JsonResponse::success(['items'=>$workflows->publicPosts($q),'page'=>$q->meta()],$requestId);});
        $router->add('POST','/api/v1/internship-posts/{postId}/applications',function(Request $r)use($session,$permissions,$workflows,$requestId){$u=$this->requireRole($session,'student','học viên');$session->assertCsrf($r->header('x-csrf-token'));$permissions->require($u['id'],'internship_application.create_own');return JsonResponse::success($workflows->apply($u['id'],(string)$r->pathParam('postId'),$r->json(),$requestId),$requestId,201);});
        $router->add('GET','/api/v1/students/me/internship-applications',function()use($session,$permissions,$workflows,$requestId){$u=$this->requireRole($session,'student','học viên');$permissions->require($u['id'],'internship_application.read_own');return JsonResponse::success($workflows->studentApplications($u['id']),$requestId);});
        $router->add('POST','/api/v1/students/me/internship-applications/{applicationId}/withdraw',function(Request $r)use($session,$permissions,$workflows,$requestId){$u=$this->requireRole($session,'student','học viên');$session->assertCsrf($r->header('x-csrf-token'));$permissions->require($u['id'],'internship_application.withdraw_own');return JsonResponse::success($workflows->withdraw($u['id'],(string)$r->pathParam('applicationId'),$requestId),$requestId);});
        $router->add('GET','/api/v1/businesses/me/internship-posts/{postId}/applications',function(Request $r)use($session,$permissions,$workflows,$requestId){$u=$this->requireRole($session,RoleCodes::ENTERPRISE,'doanh nghiệp');$permissions->require($u['id'],'internship_application.read_own_business');return JsonResponse::success($workflows->applications($u['id'],(string)$r->pathParam('postId')),$requestId);});
        $router->add('PATCH','/api/v1/businesses/me/internship-applications/{applicationId}/review',function(Request $r)use($session,$permissions,$workflows,$requestId){$u=$this->requireRole($session,RoleCodes::ENTERPRISE,'doanh nghiệp');$session->assertCsrf($r->header('x-csrf-token'));$permissions->require($u['id'],'internship_application.review_own_business');return JsonResponse::success($workflows->review($u['id'],(string)$r->pathParam('applicationId'),$r->json(),$requestId),$requestId);});
        $router->add('GET','/api/v1/projects',function(Request $r)use($session,$permissions,$workflows,$requestId){$u=$this->requireRole($session,RoleCodes::ENTERPRISE,'doanh nghiệp');$permissions->require($u['id'],'project.read_sponsorable');$q=CollectionQuery::fromRequest($r,['createdAt','title','fundingGoal']);return JsonResponse::success(['items'=>$workflows->projects($q),'page'=>$q->meta()],$requestId);});
        $router->add('POST','/api/v1/businesses/me/sponsorships',function(Request $r)use($session,$permissions,$workflows,$requestId){$u=$this->requireRole($session,RoleCodes::ENTERPRISE,'doanh nghiệp');$session->assertCsrf($r->header('x-csrf-token'));$permissions->require($u['id'],'sponsorship.create_own_business');return JsonResponse::success($workflows->sponsor($u['id'],$r->json(),$requestId),$requestId,201);});
        $router->add('GET','/api/v1/businesses/me/sponsorships',function()use($session,$permissions,$workflows,$requestId){$u=$this->requireRole($session,RoleCodes::ENTERPRISE,'doanh nghiệp');$permissions->require($u['id'],'sponsorship.read_own_business');return JsonResponse::success($workflows->sponsorships($u['id']),$requestId);});
        $router->add('POST','/api/v1/businesses/me/sponsorships/{sponsorshipId}/cancel',function(Request $r)use($session,$permissions,$workflows,$requestId){$u=$this->requireRole($session,RoleCodes::ENTERPRISE,'doanh nghiệp');$session->assertCsrf($r->header('x-csrf-token'));$permissions->require($u['id'],'sponsorship.cancel_own_business');return JsonResponse::success($workflows->cancelSponsorship($u['id'],(string)$r->pathParam('sponsorshipId'),$requestId),$requestId);});
        $router->add('POST','/api/v1/businesses/me/payments',function(Request $r)use($session,$permissions,$workflows,$requestId){$u=$this->requireRole($session,RoleCodes::ENTERPRISE,'doanh nghiệp');$session->assertCsrf($r->header('x-csrf-token'));$permissions->require($u['id'],'payment.create_own_business');return JsonResponse::success($workflows->createPayment($u['id'],$r->json(),$requestId),$requestId,201);});
        $router->add('GET','/api/v1/businesses/me/payments',function()use($session,$permissions,$workflows,$requestId){$u=$this->requireRole($session,RoleCodes::ENTERPRISE,'doanh nghiệp');$permissions->require($u['id'],'payment.read_own_business');return JsonResponse::success($workflows->payments($u['id']),$requestId);});
        $router->add('GET','/api/v1/notifications',function(Request $r)use($session,$permissions,$notifications,$requestId){$u=$session->requireUser();$permissions->require($u['id'],'notification.read_own');$q=CollectionQuery::fromRequest($r,['createdAt'],['read'=>['true','false']]);return JsonResponse::success(['items'=>$notifications->list($u['id'],$q),'page'=>$q->meta()],$requestId);});
        $router->add('POST','/api/v1/notifications/{notificationId}/read',function(Request $r)use($session,$permissions,$notifications,$requestId){$u=$session->requireUser();$session->assertCsrf($r->header('x-csrf-token'));$permissions->require($u['id'],'notification.mark_read_own');return JsonResponse::success($notifications->markRead($u['id'],(string)$r->pathParam('notificationId')),$requestId);});
        $router->add('GET','/api/v1/admin/dashboard',function()use($session,$permissions,$admin,$requestId){$u=$this->requireRole($session,RoleCodes::PLATFORM_ADMIN,'quản trị viên');$permissions->require($u['id'],'admin.dashboard.read');return JsonResponse::success($admin->dashboard(),$requestId);});
        $router->add('GET','/api/v1/admin/users',function(Request $r)use($session,$permissions,$admin,$requestId){$u=$this->requireRole($session,RoleCodes::PLATFORM_ADMIN,'quản trị viên');$permissions->require($u['id'],'admin.user.read');return JsonResponse::success(['items'=>$admin->users((string)($r->queryParam('search')??''),(string)($r->queryParam('role')??''),(string)($r->queryParam('status')??''))],$requestId);});
        $router->add('POST','/api/v1/admin/users',function(Request $r)use($session,$permissions,$admin,$requestId){$u=$this->requireRole($session,RoleCodes::PLATFORM_ADMIN,'quản trị viên');$session->assertCsrf($r->header('x-csrf-token'));$permissions->require($u['id'],'admin.user.create');return JsonResponse::success($admin->createUser($u['id'],$r->json(),$requestId),$requestId,201);});
        $router->add('PATCH','/api/v1/admin/users/{userId}',function(Request $r)use($session,$permissions,$admin,$requestId){$u=$this->requireRole($session,RoleCodes::PLATFORM_ADMIN,'quản trị viên');$session->assertCsrf($r->header('x-csrf-token'));$permissions->require($u['id'],'admin.user.update');return JsonResponse::success($admin->updateUser($u['id'],(string)$r->pathParam('userId'),$r->json(),$requestId),$requestId);});
        $router->add('DELETE','/api/v1/admin/users/{userId}',function(Request $r)use($session,$permissions,$admin,$requestId){$u=$this->requireRole($session,RoleCodes::PLATFORM_ADMIN,'quản trị viên');$session->assertCsrf($r->header('x-csrf-token'));$permissions->require($u['id'],'admin.user.delete');$in=$r->json();return JsonResponse::success($admin->deleteUser($u['id'],(string)$r->pathParam('userId'),(string)($in['reason']??''),$requestId),$requestId);});
        $router->add('PATCH','/api/v1/admin/users/{userId}/status',function(Request $r)use($session,$permissions,$admin,$requestId){$u=$this->requireRole($session,RoleCodes::PLATFORM_ADMIN,'quản trị viên');$session->assertCsrf($r->header('x-csrf-token'));$in=$r->json();$status=(string)($in['status']??'');$permissions->require($u['id'],$status==='active'?'admin.user.restore':'admin.user.suspend');return JsonResponse::success($admin->setUserStatus($u['id'],(string)$r->pathParam('userId'),$status,(string)($in['reason']??''),$requestId),$requestId);});
        $router->add('GET','/api/v1/admin/organizations',function(Request $r)use($session,$permissions,$admin,$requestId){$u=$this->requireRole($session,RoleCodes::PLATFORM_ADMIN,'quản trị viên');$permissions->require($u['id'],'admin.organization.read');return JsonResponse::success(['items'=>$admin->organizations((string)($r->queryParam('type')??''))],$requestId);});
        $router->add('PATCH','/api/v1/admin/organizations/{type}/{organizationId}/verification',function(Request $r)use($session,$permissions,$admin,$requestId){$u=$this->requireRole($session,RoleCodes::PLATFORM_ADMIN,'quản trị viên');$session->assertCsrf($r->header('x-csrf-token'));$permissions->require($u['id'],'admin.organization.verify');$in=$r->json();return JsonResponse::success($admin->verifyOrganization($u['id'],(string)$r->pathParam('type'),(string)$r->pathParam('organizationId'),(string)($in['decision']??''),(string)($in['reason']??''),$requestId),$requestId);});
        $router->add('GET','/api/v1/admin/audit',function(Request $r)use($session,$permissions,$admin,$requestId){$u=$this->requireRole($session,RoleCodes::PLATFORM_ADMIN,'quản trị viên');$permissions->require($u['id'],'admin.audit.read');return JsonResponse::success(['items'=>$admin->audits((string)($r->queryParam('search')??''))],$requestId);});
        $router->add('GET','/api/v1/admin/rbac',function()use($session,$permissions,$admin,$requestId){$u=$this->requireRole($session,RoleCodes::PLATFORM_ADMIN,'quản trị viên');$permissions->require($u['id'],'admin.rbac.read');return JsonResponse::success($admin->rbac(),$requestId);});
        $router->add('GET','/api/v1/admin/system',function()use($session,$permissions,$admin,$requestId){$u=$this->requireRole($session,RoleCodes::PLATFORM_ADMIN,'quản trị viên');$permissions->require($u['id'],'admin.system.health.read');return JsonResponse::success($admin->system(),$requestId);});
        $router->add('GET','/api/v1/admin/resources/{resource}',function(Request $r)use($session,$permissions,$admin,$requestId){$u=$this->requireRole($session,RoleCodes::PLATFORM_ADMIN,'quản trị viên');$resource=(string)$r->pathParam('resource');$permissions->require($u['id'],$resource==='payments'?'admin.payment.read':'admin.dashboard.read');return JsonResponse::success(['items'=>$admin->resource($resource)],$requestId);});
        return $router;
    }

    /** @return array{id:string,email:string,fullName:string,role:string,status:string} */
    private function requireTeacher(SessionManager $session): array{$user=$session->requireUser();if($user['role']!=='teacher'){throw new ApiException(403,'PERMISSION_DENIED','Endpoint chỉ dành cho giáo viên.');}return $user;}
    /** @return array{id:string,email:string,fullName:string,role:string,status:string} */
    private function requireSchool(SessionManager $session): array{$user=$session->requireUser();if($user['role']!=='school'){throw new ApiException(403,'PERMISSION_DENIED','Endpoint chỉ dành cho nhà trường.');}return $user;}
    /** @return array{id:string,email:string,fullName:string,role:string,status:string} */
    private function requireRole(SessionManager $session,string $role,string $label): array{$user=$session->requireUser();if(!RoleCodes::matches($user['role'],$role)){throw new ApiException(403,'PERMISSION_DENIED',"Endpoint chỉ dành cho {$label}.");}return $user;}

    private function parseInt(?string $value, int $min, int $max, int $default): int
    {
        if ($value === null || $value === '' || !is_numeric($value)) {
            return $default;
        }
        $intVal = (int) $value;
        if ($intVal < $min || $intVal > $max) {
            throw new ApiException(422, 'VALIDATION_FAILED', 'Tham số query không hợp lệ.');
        }
        return $intVal;
    }
}
